import { LESSON_BY_ID } from '../data/curriculum';

export const LESSON_ART = {
  campus: { src:'/lessons/ngoc-dien/campus.webp', alt:'Sinh viên trao đổi trong khuôn viên trường' },
  city: { src:'/lessons/ngoc-dien/city.webp', alt:'Tình huống giao tiếp trong khu phố' },
  work: { src:'/lessons/ngoc-dien/work.webp', alt:'Đồng nghiệp trao đổi công việc' },
  reading: { src:'/lessons/ngoc-dien/reading.webp', alt:'Không gian đọc và suy ngẫm' },
  sound: { src:'/lessons/ngoc-dien/sound.webp', alt:'Góc luyện nghe và phát âm' },
} as const;
export type LessonArtKey = keyof typeof LESSON_ART;
export function lessonPresentation(lessonId?: string) {
  const lesson=lessonId?LESSON_BY_ID.get(lessonId):undefined;
  const text=`${lesson?.unitId} ${lesson?.title} ${lesson?.objective}`.toLocaleLowerCase('vi');
  const family = /boot|phát âm|thanh điệu/.test(text)?'sound':/viết|lập luận|trình bày|tóm tắt/.test(text)?'writing':/đọc|văn bản|suy luận/.test(text)?'reading':/ngữ pháp|bổ ngữ|cấu trúc|so sánh/.test(text)?'grammar':'conversation';
  const art:LessonArtKey=family==='sound'?'sound':/trường học|sinh viên|học sinh|khuôn viên/.test(text)?'campus':/công việc|nghề|kinh doanh|dự án/.test(text)?'work':family==='reading'||family==='writing'?'reading':/ăn|uống|mua|đường|du lịch|thời gian|daily/.test(text)?'city':'campus';
  return {lesson,family,art,contextTitle:family==='reading'?'Đọc và tìm bằng chứng':family==='writing'?'Quan sát cách triển khai ý':family==='sound'?'Nghe và nhận ra âm':'Gặp trong tình huống',taskTitle:family==='writing'?'Tự viết và chỉnh sửa':family==='reading'?'Tóm lược bằng lời của bạn':'Đổi vai và vận dụng'};
}

/** Original scene assets; editors can assign these to any appropriate page. */
export const LESSON_SCENES = [
  {"src":"/lessons/ngoc-dien/hsk2-red-white-ownership-v1.webp","alt":"Mai chỉ áo đỏ của mình; áo trắng của Lan nằm cạnh đó","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-10-01 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-sisters-comparison-v1.webp","alt":"Hai chị em đứng cạnh nhau, người chị cao hơn","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-10-01 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-hotel-message-v1.webp","alt":"Người học sửa tin nhắn về khách sạn bên sách ôn thi","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-10-01 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-unpacked-trip-v1.webp","alt":"Hai bạn bàn chuyến đi; vé đã mua, vali còn trống","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-10-01 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-study-help-v1.webp","alt":"Minh họa lời đề nghị giúp bạn ôn tại nhà trước kỳ thi","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-10-01 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-school-gate-directions-v1.webp","alt":"Hỏi đường trước cổng trường và chỉ hướng đi thẳng","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-10-01 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-stairs-return-v1.webp","alt":"A đứng ngoài cửa, B đi vào về phía cầu thang bên phải","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-10-01 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-basketball-meeting-v1.webp","alt":"Hai bạn bàn giờ hẹn chơi bóng rổ trước cổng trường","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-10-01 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-tea-three-v1.webp","alt":"Ba người tự chọn trà, mỗi người cầm hai gói","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-10-01 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-office-phone-v1.webp","alt":"Linh tan làm rồi gọi điện cho mẹ trong ngày lạnh","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-10-01 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-subway-wait-v1.webp","alt":"Lâm đã có vé và đang đợi người bạn chưa tới ngoài ga","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-club-open-door-v1.webp","alt":"Ba giáo viên đứng cạnh cửa câu lạc bộ đang mở","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-rain-reading-v1.webp","alt":"Hai bạn ở trong nhà đọc sách vì mưa, chưa ăn trước khi về","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-exam-home-v1.webp","alt":"Người học mệt nhưng mở sách ôn tại nhà buổi tối","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-enter-class-v1.webp","alt":"Nam từ cửa bước vào phía giáo viên đang ở trong lớp","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-door-book-gift-v1.webp","alt":"Hai bạn trao sách ngoài cửa; giáo viên ở trong lớp gọi vào","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-club-portrait-v1.webp","alt":"Ba phụ nữ từ trái sang phải cao dần; người bên trái tóc dài, người giữa tóc ngắn","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-bus-delay-v1.webp","alt":"Người học đợi xe buýt chưa tới, có taxi trên đường","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-red-green-shirts-v1.webp","alt":"Áo đỏ dài hơn áo xanh lá treo cạnh nhau trong cửa hàng","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-weather-plan-v1.webp","alt":"Hai bạn xem dự báo ngày mai; trời hiện tại âm u, ô còn đóng","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-bedroom-window-v1.webp","alt":"Một giường và bàn học cạnh cửa sổ trong phòng","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-study-questions-v1.webp","alt":"Người học ghi lại hai chỗ chưa hiểu trong bài tập","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-school-art-v1.webp","alt":"Lớp học chuẩn bị vở bút và đồ vẽ cho ngày khai giảng","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-teacher-prepares-v1.webp","alt":"Giáo viên chuẩn bị tài liệu cho tiết chiều ở phòng làm việc","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-new-year-dumplings-v1.webp","alt":"Minh họa một lần cùng gia đình bạn ăn sủi cảo dịp Tết","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-teacher-greeting-v1.webp","alt":"Người học gặp giáo viên mới và hỏi cách xưng hô","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-headache-v1.webp","alt":"Người đau đầu và khó chịu ở mắt trao đổi với bạn trước khi đi khám","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-family-v1.webp","alt":"Lan nấu cơm, chồng chơi với con, ông bà nội của Lan nghỉ trên ghế","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-flight-v1.webp","alt":"Hai bạn chuẩn bị hành lý và bàn cách đi sân bay cho chuyến bay sắp tới","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-football-v1.webp","alt":"Minh họa cuộc hẹn ở cửa công viên với bóng đá và đường chạy","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-help-open-door-v1.webp","alt":"Người đau tay nhờ bạn mở một trong hai cánh cửa","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-plan-restaurant-dinner-v1.webp","alt":"Hai người bạn bàn chọn bữa tối khi chưa chuẩn bị cơm ở nhà","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {"src":"/lessons/ngoc-dien/hsk2-black-blue-trousers-v1.webp","alt":"So quần đen dài với quần xanh lam ngắn hơn trong cửa hàng","provenance":"OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false"},
  {src:'/lessons/ngoc-dien/first-class-greeting-v1.webp',alt:'Hai người học chào nhau trước cửa lớp bằng lời và cử chỉ thân thiện',provenance:'OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false'},
  {src:'/lessons/ngoc-dien/cinema-home-music-v1.webp',alt:'Một người xem phim ở rạp, người khác nghe nhạc tại nhà',provenance:'OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false'},
  {src:'/lessons/ngoc-dien/classmate-introduction-v1.webp',alt:'Ba học viên làm quen và giới thiệu bạn học sau giờ học',provenance:'OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false'},
  {src:'/lessons/ngoc-dien/book-beside-computer-v1.webp',alt:'Hai người tìm quyển sách đặt ngay cạnh máy tính',provenance:'OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false'},
  {src:'/lessons/ngoc-dien/office-evening-class-v1.webp',alt:'Một người tan làm ở công ty rồi học tại lớp buổi tối',provenance:'OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false'},
  {src:'/lessons/ngoc-dien/calendar-meeting-plan-v1.webp',alt:'Hai người đối chiếu sổ lịch để hẹn ngày gặp',provenance:'OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false'},
  {src:'/lessons/ngoc-dien/class-start-eight-v1.webp',alt:'Lớp bắt đầu buổi sáng, đồng hồ chỉ 8 giờ',provenance:'OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false'},
  {src:'/lessons/ngoc-dien/near-far-cups-location-v1.webp',alt:'Người chỉ cốc gần mình, cốc thứ hai ở xa; sách trên bàn và mèo dưới bàn',provenance:'OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false'},
  {src:'/lessons/ngoc-dien/two-books-room-203-v1.webp',alt:'Hai quyển sách trên bàn, phía sau là cửa phòng mang số 203',provenance:'OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false'},
  {src:'/lessons/ngoc-dien/weekly-study-rest-meeting-v1.webp',alt:'Ba cảnh đi học, nghỉ ở nhà và gặp bạn trong công viên',provenance:'OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false'},
  {src:'/lessons/ngoc-dien/rainy-home-residence-v1.webp',alt:'Người mặc áo ấm đang ở nhà bên cửa sổ có mưa',provenance:'OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false'},
  {src:'/lessons/ngoc-dien/book-desk-cat-location-v1.webp',alt:'Sách trên mặt bàn, mèo ngồi dưới cùng chiếc bàn',provenance:'OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false'},
  {src:'/lessons/ngoc-dien/book-return-thanks-v1.webp',alt:'Một người trả cuốn sách tìm thấy cho người đối diện và nhận lời cảm ơn',provenance:'OpenAI imagegen · nguyên bản HANZI.OS · 2026-09-30 · AI-assisted, humanReviewed:false'},
  {src:'/lessons/ngoc-dien/apple-market-prices-v1.webp',alt:'Khách hỏi người bán về táo tại quầy trái cây, không có giá ghi trên tranh'},
  {src:'/lessons/ngoc-dien/shirt-shop-change-v1.webp',alt:'Khách chọn áo và người bán trả tiền thừa tại cửa hàng, không thể đọc mệnh giá từ tranh'},
  {src:'/lessons/ngoc-dien/clinic-waiting-room-v1.webp',alt:'Khách đến phòng chờ khám có bác sĩ, bàn và ghế'},
  {src:'/lessons/ngoc-dien/hsk3-season-preparation-v1.webp',alt:'Chuẩn bị áo khoác và áo mưa theo thời tiết'},
  {src:'/lessons/ngoc-dien/hsk3-stairwell-cleanup-v1.webp',alt:'Hàng xóm cùng quét cầu thang và lau tay vịn'},
  {src:'/lessons/ngoc-dien/hsk3-green-commute-v1.webp',alt:'Đồng nghiệp trao đổi cách đi làm cạnh bãi xe đạp'},
  {src:'/lessons/ngoc-dien/hsk3-mountain-town-v1.webp',alt:'Cảnh thành phố núi có hồ và vườn hoa'},
  {src:'/lessons/ngoc-dien/hsk3-community-garden-v1.webp',alt:'Người lớn và trẻ quan sát cây trong vườn cộng đồng'},
  {src:'/lessons/ngoc-dien/hsk3-reading-notes-v1.webp',alt:'Đọc sách và ghi ý chính ở thư viện'},
  {src:'/lessons/ngoc-dien/hsk3-campus-visit-v1.webp',alt:'Học sinh hỏi giáo viên khi tham quan trường cùng mẹ'},
  {src:'/lessons/ngoc-dien/hsk3-office-library-v1.webp',alt:'Tìm lại từ điển trong phòng thu'},
  {src:'/lessons/ngoc-dien/hsk3-team-handoff-v1.webp',alt:'Đồng nghiệp gọi điện và đối chiếu bảng thông tin'},
  {src:'/lessons/ngoc-dien/hsk3-fashion-career-v1.webp',alt:'Nhân viên cửa hàng phác thảo trang phục khi nghe khách kể'},
  {src:'/lessons/ngoc-dien/hsk3-shopping-choice-v1.webp',alt:'So sánh hai chiếc quần trong cửa hàng'},
  {src:'/lessons/ngoc-dien/hsk3-clinic-conversation-v1.webp',alt:'Họa sĩ trao đổi với bác sĩ tại phòng khám'},
  {src:'/lessons/ngoc-dien/hsk3-moving-neighbors-v1.webp',alt:'Hai người chuyển đồ tới nhà mới và chào hàng xóm'},
  {src:'/lessons/ngoc-dien/hsk3-office-request-v1.webp',alt:'Nhân viên trao đơn cho quản lý tại văn phòng'},
  {src:'/lessons/ngoc-dien/hsk3-travel-detour-v1.webp',alt:'Hành khách và tài xế trao đổi đường đi khi xe dừng trước đèn đỏ'},
  {src:'/lessons/ngoc-dien/pond-observation-v1.webp',alt:'Một người cao tuổi ngồi bên trái, ô khép cạnh ghế và hồ cá bên phải'},
  {src:'/lessons/ngoc-dien/rainy-station-observation-v1.webp',alt:'Người phụ nữ cầm ô đang đi về cửa ga bên trái trong trời mưa'},
  {src:'/lessons/ngoc-dien/study-preparation-v1.webp',alt:'Chuẩn bị sách vở và đồ dùng cho buổi học nhóm'},
  {src:'/lessons/ngoc-dien/station-meeting-v1.webp',alt:'Hai người bạn tìm gặp nhau trước cửa nhà ga'},
  {src:'/lessons/ngoc-dien/classroom-change-v1.webp',alt:'Giáo viên hướng dẫn học viên chuyển sang phòng học khác'},
  {src:'/lessons/ngoc-dien/polite-help-v1.webp',alt:'Xin lỗi và nhặt giúp chiếc bút rơi ở quầy thông tin'},
  {src:'/lessons/ngoc-dien/clothes-opinion-v1.webp',alt:'Hai người bạn nhận xét độ rộng của áo trong cửa hàng'},
  {src:'/lessons/ngoc-dien/phone-callback-v1.webp',alt:'Người nhận cuộc gọi đang bận chuẩn bị bữa ăn'},
  {src:'/lessons/ngoc-dien/pets-introduction-v1.webp',alt:'Giới thiệu người bạn và vật nuôi trong phòng khách'},
  {src:'/lessons/ngoc-dien/conversation-invitation-v1.webp',alt:'Nhóm học trò chuyện và một người bạn cần rời đi'},
  {src:'/lessons/ngoc-dien/morning-routine-v1.webp',alt:'Thức dậy và ra khỏi giường trong buổi sáng'},
  {src:'/lessons/ngoc-dien/pronoun-group-v1.webp',alt:'Nhóm học sinh giới thiệu với giáo viên, có mô hình mèo trên bàn'},
  {src:'/lessons/ngoc-dien/fictional-profile-v1.webp',alt:'Hai học viên trao đổi thẻ tên và tập điền hồ sơ giả định'},
  {src:'/lessons/ngoc-dien/family-album-v1.webp',alt:'Các thành viên gia đình cùng xem album ảnh'},
  {src:'/lessons/ngoc-dien/breakfast-water-order-v1.webp',alt:'Ở quán ăn sáng, khách gọi hai bánh bao, một quả trứng và nước thay trà'},
  {src:'/lessons/ngoc-dien/home-school-taxi-call-v1.webp',alt:'Một học viên gọi từ nhà, taxi chờ ngoài cửa và bạn học nghe máy ở trường'},
  {src:'/lessons/ngoc-dien/secondary-school-introduction-v1.webp',alt:'Hai học sinh làm quen trước trường trung học'},
].map(scene=>({...scene,provenance:scene.provenance??`OpenAI imagegen · nguyên bản HANZI.OS · ${/apple-market-prices|shirt-shop-change|clinic-waiting-room|breakfast-water-order|home-school-taxi-call|secondary-school-introduction/.test(scene.src)?'2026-09-29':/hsk3-(season-preparation|stairwell-cleanup|green-commute|mountain-town|community-garden)/.test(scene.src)?'2026-09-23':/hsk3-|observation|pronoun-group|fictional-profile|family-album/.test(scene.src)?'2026-09-22':'2026-09-21'} · AI-assisted, humanReviewed:false`}));
