import {writeFileSync} from 'node:fs';
import {LESSON_BY_ID} from '../../src/data/curriculum';
import {getRichLessonContent} from '../../src/learning/richLessonContent';
import {emptyLessonBlock,validateLessonPages,type LessonBlock,type LessonPageDocument} from '../../src/learning/lessonPages';
import {emptyLessonActivity} from '../../src/learning/lessonActivities';
const lesson=LESSON_BY_ID.get('professional-3')!;
const rich=getRichLessonContent(lesson.id)!;
const b=(id:string,fields:Partial<LessonBlock>):LessonBlock=>({...emptyLessonBlock(`professional-3:v2:block:${id}`),...fields});
const ex=(id:string,title:string,hanzi:string,pinyin:string,meaningVi:string)=>b(id,{kind:'dialogue',title,hanzi,pinyin,meaningVi});
const dialogue=[
  {speaker:'Bạn A',hanzi:'你学习汉语吗？',pinyin:'Nǐ xuéxí Hànyǔ ma?',meaningVi:'Bạn học tiếng Trung phải không?'},
  {speaker:'Bạn B',hanzi:'是，我读书，也写汉字。',pinyin:'Shì, wǒ dú shū, yě xiě Hànzì.',meaningVi:'Đúng, tôi đọc sách, cũng viết chữ Hán.'},
  {speaker:'Bạn A',hanzi:'我有一个问题。这本书在哪里？',pinyin:'Wǒ yǒu yí ge wèntí. Zhè běn shū zài nǎlǐ?',meaningVi:'Tôi có một câu hỏi. Quyển sách này ở đâu?'},
  {speaker:'Bạn B',hanzi:'在电脑旁边。',pinyin:'Zài diànnǎo pángbiān.',meaningVi:'Ở bên cạnh máy tính.'},
];
const pages:LessonPageDocument={version:1,art:'reading',pages:[
  {id:'professional-3:v2:mission',title:'Chuẩn bị góc học cùng một người bạn',layout:'scene',stage:'context',blocks:[b('mission',{title:'Việc cần làm trong bài',body:'Bạn và một người bạn chuẩn bị học tiếng Trung. Bạn cần nói mình học bằng hoạt động nào, tìm đúng sách và hỏi khi chưa biết thông tin. Bài chia thành hai phần nhỏ: hoạt động học; tài liệu và câu hỏi. Không cần nhớ cả mười hai từ cùng lúc.'}),b('support',{title:'Từ hỗ trợ dùng trong mẫu',body:'有 (yǒu) — có; 一 (yī) — một; 个 (ge) — lượng từ; 这 (zhè) — này; 在 (zài) — ở; 哪里 (nǎlǐ) — đâu; 旁边 (pángbiān) — bên cạnh; 也 (yě) — cũng. 汉语/汉字 đã được giải thích ở bài trước. Có thể mở lại nghĩa bất cứ lúc nào.'})]},
  {id:'professional-3:v2:actions',title:'Học là việc lớn, đọc và viết là hoạt động cụ thể',layout:'focus',stage:'understand',blocks:[b('actions-map',{kind:'diagram',title:'Chọn động từ theo điều bạn làm',diagram:{type:'comparison',description:'学/学习 nói học một nội dung; 读 là đọc, 写 là viết. Đọc và viết có thể là cách học, nhưng không phải cùng một hành động.',nodes:[
    {id:'learn',label:'学 / 学习',pinyin:'xué / xuéxí',meaningVi:'học / học tập',note:'我学汉语 hoặc 我学习汉语 đều phù hợp trong mẫu này.',x:0,y:0},
    {id:'read',label:'读 / 读书',pinyin:'dú / dúshū',meaningVi:'đọc / đọc sách',note:'读书 trong bối cảnh này là đọc sách; ở ngữ cảnh khác có thể nói việc theo học.',x:1,y:0},
    {id:'write',label:'写',pinyin:'xiě',meaningVi:'viết',note:'写汉字 — viết chữ Hán. Không nhầm với việc chỉ đọc chữ.',x:2,y:0},
  ]}}),ex('learning','Nội dung đang học','我学汉语。','Wǒ xué Hànyǔ.','Tôi học tiếng Trung.'),ex('reading','Một hoạt động cụ thể','我读书。','Wǒ dú shū.','Tôi đọc sách.'),ex('writing','Hoạt động khác','我写汉字。','Wǒ xiě Hànzì.','Tôi viết chữ Hán.')]},
  {id:'professional-3:v2:action-check',title:'Thử phân biệt trước khi học tiếp',layout:'focus',stage:'practice',blocks:[b('write-choice',{kind:'activity',title:'Nói đúng hoạt động',body:'Bạn đang viết chữ Hán vào vở, không phải đọc sách. Câu nào khớp thông tin?',activity:{...emptyLessonActivity(),options:[{id:'read',text:'我读书。',feedback:'读书 là đọc sách, khác hoạt động được cho.'},{id:'write',text:'我写汉字。',feedback:'Đúng. 写 diễn tả viết, 汉字 là chữ Hán.'}],answerIds:['write'],explanation:'Chọn theo hành động: 读 là đọc, 写 là viết. Cả hai có thể phục vụ 学习 — học tập.',hint:''}}),b('learning-cloze',{kind:'activity',title:'Hai cách nói đều được',body:'Điền “học” để nói tôi học tiếng Trung: 我___汉语。',activity:{...emptyLessonActivity(),type:'cloze',acceptedAnswers:['学','学习'],explanation:'我学汉语 và 我学习汉语 đều phù hợp ở đây. Không suy ra rằng 学 và 学习 thay nhau trong mọi cụm cố định.',hint:''}})]},
  {id:'professional-3:v2:materials',title:'Sách, nơi bán sách và thiết bị học',layout:'split',stage:'understand',blocks:[ex('book','Tài liệu','这是一本书。','Zhè shì yì běn shū.','Đây là một quyển sách.'),ex('computer','Thiết bị','这是我的电脑。','Zhè shì wǒ de diànnǎo.','Đây là máy tính của tôi.'),ex('bookshop','Nơi bán sách','书店有书。','Shūdiàn yǒu shū.','Hiệu sách có sách.'),b('measure',{title:'本 nằm giữa số lượng và 书',body:'一本书 (yì běn shū) — một quyển sách; 两本书 (liǎng běn shū) — hai quyển sách; 这本书 (zhè běn shū) — quyển sách này. 两 (liǎng) dùng trước lượng từ trong mẫu đếm hai quyển. 本 không phải từ chỉ mọi đồ vật: không dùng 一本电脑. Bài này chưa yêu cầu học lượng từ của máy tính.'}),ex('class','Buổi học theo nội dung','今天有汉语课。','Jīntiān yǒu Hànyǔ kè.','Hôm nay có giờ học tiếng Trung.'),b('class-note',{title:'课 không phải quyển sách',body:'今天 (jīntiān) — hôm nay. 汉语课 là giờ/lớp học tiếng Trung. 书 là sách dùng học; 课 là buổi/tiết hoặc môn học tùy câu. Có sách không tự có nghĩa là đang ở trong một tiết học.'})]},
  {id:'professional-3:v2:conversation',title:'Theo dõi một câu hỏi về tài liệu',layout:'dialogue',stage:'context',blocks:dialogue.map((turn,i)=>b(`turn-${i}`,{kind:'dialogue',title:turn.speaker,...turn}))},
  {id:'professional-3:v2:ask',title:'Hỏi khi chưa biết',layout:'focus',stage:'understand',blocks:[ex('question','Báo mình có câu hỏi','我有一个问题。','Wǒ yǒu yí ge wèntí.','Tôi có một câu hỏi.'),ex('where','Hỏi nơi đặt sách','这本书在哪里？','Zhè běn shū zài nǎlǐ?','Quyển sách này ở đâu?'),ex('know','Nếu chưa biết câu trả lời','我不知道。','Wǒ bù zhīdào.','Tôi không biết.'),b('ask-rule',{title:'Không biết cũng có cách đáp đúng',body:'知道 (zhīdào) — biết một thông tin; 不知道 — không biết. 问题 trong tình huống này là câu hỏi, ở ngữ cảnh khác có thể là vấn đề. 我有一个问题 chưa nêu câu hỏi cụ thể: cần hỏi tiếp điều bạn muốn biết. 这本书在哪里？ hỏi nơi đặt sách; không thêm 吗 vì 哪里 đã hỏi “đâu”.'})]},
  {id:'professional-3:v2:apply',title:'Tự dùng tài liệu và câu hỏi',layout:'workshop',stage:'practice',blocks:[b('book-order',{kind:'activity',title:'Nói số lượng sách',body:'Sắp xếp thành “Tôi có hai quyển sách”.',activity:{...emptyLessonActivity(),type:'order',options:[{id:'book',text:'书',feedback:''},{id:'i',text:'我',feedback:''},{id:'two',text:'两',feedback:''},{id:'measure',text:'本',feedback:''},{id:'have',text:'有',feedback:''}],answerIds:['i','have','two','measure','book'],explanation:'我有两本书。Wǒ yǒu liǎng běn shū. 本 đứng giữa 两 và 书.',hint:'Người sở hữu + 有 + số lượng + 本 + 书.'}}),b('answer',{kind:'activity',title:'Đáp theo đúng thông tin bạn có',body:'Người bạn hỏi quyển sách ở đâu, nhưng bạn thật sự chưa biết. Chọn câu trả lời phù hợp.',activity:{...emptyLessonActivity(),options:[{id:'unknown',text:'我不知道。',feedback:'Đúng. Bạn nói rõ chưa biết thông tin.'},{id:'location',text:'在电脑旁边。',feedback:'Đây là một vị trí cụ thể, không được tự đoán khi đề nói bạn chưa biết.'},{id:'class',text:'今天有汉语课。',feedback:'Câu này nói lịch học, chưa trả lời câu hỏi về vị trí sách.'}],answerIds:['unknown'],explanation:'Biết câu mẫu chỉ vị trí không có nghĩa nên dùng khi không có thông tin. 我不知道 đáp đúng tình huống.',hint:''}})]},
  {id:'professional-3:v2:transfer',title:'Chuẩn bị buổi học ở chỗ mới',layout:'workshop',stage:'transfer',blocks:[b('new-context',{title:'Thông tin cho vai của bạn',body:'Bạn có hai quyển sách và sẽ học tiếng Trung cùng một người mới. Bạn đọc sách và viết chữ Hán. Người đó hỏi máy tính ở đâu, nhưng bạn chưa biết. Viết ba hoặc bốn câu để nói tài liệu/hoạt động và đáp đúng câu hỏi. Có thể quay lại từ hỗ trợ; không phải kiểm nhớ độc lập.'}),b('produce',{kind:'activity',title:'Tạo lời nói từ thông tin mới',body:'Viết câu của bạn trước khi đối chiếu.',activity:{...emptyLessonActivity(),type:'rubric',rubric:[{id:'materials',label:'Nói đúng số lượng và đồ vật',guidance:'我有两本书. Dùng 两本书, không bỏ 本 hoặc đổi sách thành máy tính.'},{id:'actions',label:'Phân biệt hai hoạt động',guidance:'我读书，也写汉字. 读 và 写 diễn tả hai hành động khác nhau.'},{id:'answer',label:'Không tự đoán thông tin chưa biết',guidance:'Khi được hỏi máy tính ở đâu, đáp 我不知道 theo đúng tình huống.'}],explanation:'Một phương án: 我有两本书。我读书，也写汉字。我不知道电脑在哪里。Wǒ yǒu liǎng běn shū. Wǒ dú shū, yě xiě Hànzì. Wǒ bù zhīdào diànnǎo zài nǎlǐ. Tôi có hai quyển sách. Tôi đọc sách, cũng viết chữ Hán. Tôi không biết máy tính ở đâu. Có thể đáp câu cuối ngắn hơn: 我不知道。Không bắt buộc dùng cấu trúc dài chưa luyện.',hint:''}})]},
  {id:'professional-3:v2:recap',title:'Tự kiểm trước buổi học tiếp theo',layout:'focus',stage:'transfer',blocks:[b('recap',{title:'Gom lại hai phần của bài',body:'Hoạt động: 学/学习 — học; 读/读书 — đọc/đọc sách; 写 — viết.\nTài liệu và bối cảnh: 书 — sách; 本 — lượng từ của sách; 书店 — hiệu sách; 电脑 — máy tính; 课 — giờ/môn học.\nHỏi đáp: 问题 — câu hỏi/vấn đề; 知道 — biết.\nTự nói mình học gì, có bao nhiêu sách và hỏi một thông tin còn thiếu. Nếu vướng, quay lại đúng phần; sau đó vào Thử Luyện. Đọc hết trang chưa tự chứng minh đã nhớ đủ mười hai từ.'})]},
]};
const studioContent={targetLessonId:lesson.id,titleZh:lesson.chineseTitle,objectiveVi:lesson.objective,conceptVi:'Phân biệt hoạt động học/đọc/viết, tài liệu/thiết bị/nơi học; hỏi điều chưa biết.',ruleVi:'我学/学习汉语; 我读书; 我写汉字. Số lượng + 本 + 书. 我有一个问题 mở lời; 哪里 hỏi nơi chốn; 我不知道 đáp khi không biết.',pitfallVi:'本 không dùng cho mọi đồ vật; 书 khác 书店 và 课. Không thêm 吗 vào mẫu có 哪里. Không tự đoán vị trí khi không biết.',checkpointVi:'Nói có hai quyển sách, đọc và viết trong buổi học, đáp đúng khi chưa biết máy tính ở đâu.',prerequisites:lesson.prerequisiteIds,vocabulary:lesson.wordIds,skills:lesson.skills,dialogue,grammar:[
  {pattern:'Số lượng + 本 + 书',explanationVi:'本 là lượng từ sách. 两本书 nói hai quyển; 这本书 nói quyển này.',modelExample:{hanzi:'我有两本书。',pinyin:'Wǒ yǒu liǎng běn shū.',meaningVi:'Tôi có hai quyển sách.'},guidedPractice:{promptVi:'Nói bạn có một quyển sách.',modelAnswerHanzi:'我有一本书。',modelAnswerPinyin:'Wǒ yǒu yì běn shū.',modelAnswerMeaningVi:'Tôi có một quyển sách.'}},
  {pattern:'这本书在哪里？ / 我不知道。',explanationVi:'哪里 hỏi ở đâu; 不知道 nói chưa biết thông tin. Không thêm 吗 trong mẫu 哪里.',modelExample:{hanzi:'这本书在哪里？',pinyin:'Zhè běn shū zài nǎlǐ?',meaningVi:'Quyển sách này ở đâu?'},guidedPractice:{promptVi:'Bạn chưa biết câu trả lời. Nói rõ điều đó.',modelAnswerHanzi:'我不知道。',modelAnswerPinyin:'Wǒ bù zhīdào.',modelAnswerMeaningVi:'Tôi không biết.'}},
],exercises:[
  {promptVi:'Nói bạn có hai quyển sách.',answer:'我有两本书。',answerPinyin:'Wǒ yǒu liǎng běn shū.',answerMeaningVi:'Tôi có hai quyển sách.',distractors:['我有两书。','我有两本电脑。'],explanationVi:'Cần 本 trước 书. Không đổi sách thành máy tính hoặc áp 本 cho máy tính.'},
  {promptVi:'Bạn chưa biết sách ở đâu. Đáp phù hợp.',answer:'我不知道。',answerPinyin:'Wǒ bù zhīdào.',answerMeaningVi:'Tôi không biết.',distractors:['在电脑旁边。','我知道。'],explanationVi:'Không đoán vị trí hoặc nói biết khi đề cho chưa biết.'},
],lessonPages:pages,sourceVocabularyIds:lesson.wordIds,sourceLessonIds:[lesson.id],sourceGrammarIds:rich.grammar.map(g=>g.id),sourceTaskIds:rich.tasks.map(t=>t.id),sourceTopicIds:rich.topics.map(t=>t.id),review:{humanReviewed:false,aiSelfReview:{accuracy:false,levelFit:false,pedagogy:false,answerIntegrity:false,originality:false}}};
const errors=validateLessonPages(pages);if(errors.length)throw new Error(errors.join('\n'));
writeFileSync('content/drafts/thien-lo-professional-3-v2.json',JSON.stringify({schemaVersion:1,lessonId:lesson.id,title:lesson.title,objective:lesson.objective,status:'authored-draft-not-published',humanReviewed:false,source:{wordIds:lesson.wordIds,prerequisiteIds:lesson.prerequisiteIds},lessonPages:pages,studioContent},null,2)+'\n');
console.log({lessonId:lesson.id,pages:pages.pages.length,status:'draft'});
