import {buildGrammarNarrativeBatch,type GrammarDecision,type NarrativeVisual} from './build-grammar-narrative-batch';
import {discourseNarratives} from './hsk3-discourse-narratives';
const rows:Array<[string,string,string,string,string,string,string]>=[
 ['020','Hai hành động đồng thời','Vừa giới thiệu vừa nhắc giờ: 主持人一边介绍节目，___提醒大家注意时间。','一边','yìbiān','vừa','一边…一边… cùng chủ thể và cùng thời điểm.'],
 ['029','Liệt kê phương án','Có thể mua trực tuyến hoặc tại chỗ; dùng liên từ văn viết 或: 可以在网上___现场买票。','或','huò','hoặc','Câu trần thuật đưa khả năng; hỏi người nghe chọn trực tiếp thường dùng 还是.'],
 ['030','Chuyển ý trái kỳ vọng','Muốn xem nhiều, nhưng chỉ đủ giờ dự hai mục: 我们想多看一些，___时间不够。（用“可是”）','可是','kěshì','nhưng','可是 nối ý chuyển hướng; 而且 sẽ thành bổ sung.'],
 ['044','Bổ sung ngoài một hoạt động','Ngoài hòa nhạc còn có múa: 除了音乐会以外，___有舞蹈表演。','还','hái','còn','还 cho biết hòa nhạc vẫn được tính và thêm múa.'],
 ['082','Trước rồi sau','Mua trước, lấy vé sau: 先买票，___取票。（用“然后”）','然后','ránhòu','sau đó','然后 nêu bước sau, không phải hành động đồng thời.'],
 ['083','Hai phương án còn mở','Hoặc tàu điện hoặc xe buýt: 或者坐地铁，___坐公共汽车。','或者','huòzhě','hoặc','或者…或者… chưa xác nhận phương án nào đã chọn.'],
 ['084','Luân phiên trạng thái','Lúc dẫn, lúc lại bị gỡ hòa: 主队一会儿领先，___又被追平。','一会儿','yíhuìr','lúc thì','一会儿…一会儿… nói thay đổi qua lại trong trận.'],
 ['085','Hai đặc điểm cùng có','Vừa nghiêm túc vừa bình tĩnh: 两队又认真___冷静。','又','yòu','vừa','又…又… đặt hai tính chất song song.'],
 ['086','Làm và giới thiệu cùng lúc','Vừa nấu vừa nói: 厨师一边做菜，___介绍做法。','一边','yìbiān','vừa','Hai hành động có thể cùng diễn ra; không dùng cho ăn xong rồi rửa bát.'],
 ['087','Bổ sung thông tin','Không chỉ thơm mà còn có chuyện: 这道菜不但很香，___还有一个故事。','而且','érqiě','mà còn','而且 thêm ý cùng hướng, không báo kết quả trái kỳ vọng.'],
 ['088','Nhượng bộ và kết quả','Dù chủ nhà ghi điểm trước, đội khách thắng: 虽然主队先得分，___客队最后赢了。（用“可是”）','可是','kěshì','nhưng','Việc trước đúng nhưng kết quả không theo kỳ vọng.'],
 ['089','Giả thiết và phương án','Nếu không ăn cay được, có thể chọn món khác: 如果不能吃辣，___可以选别的菜。','就','jiù','thì','如果…就… không có nghĩa đây là điều kiện duy nhất được chọn món khác.'],
 ['090','Đóng khung điều kiện','Nếu lần đầu làm khách: 第一次去朋友家做客___，就先问清楚。（用“的话”）','的话','dehuà','nếu','的话 đứng sau mệnh đề điều kiện, trước kết quả.'],
 ['091','Điều kiện cần','Chỉ được dự khi có lời mời: 只有收到邀请，___能参加。','才','cái','mới','只有…才… nêu yêu cầu cần; thực đơn không thay lời mời.'],
 ['092','Điều kiện đủ để nhận thực đơn','Chỉ cần nhắn tin thì chủ nhà gửi thực đơn: 只要发消息，主人___会发菜单。','就','jiù','thì','Kết quả là nhận thực đơn, không phải nhận lời mời.'],
 ['093','Mục đích hành động','Để thể hiện tôn trọng, hỏi giờ đến trước: ___表示尊重，我们提前问了到达时间。','为了','wèile','để','为了 dẫn mục đích, không xác nhận mọi kết quả mong muốn đã đạt.'],
 ['094','Mốc trước dẫn bước sau','Chủ nhà chỉ chỗ rồi chúng tôi ngồi: 主人介绍了座位，我们___坐下了。（用“就”）','就','jiù','liền/rồi','就 nối trình tự; không tự chứng minh quan hệ nhân quả phổ quát.'],
];
const decisions:GrammarDecision[]=rows.map(([row,title,prompt,answer,answerPinyin,answerVi,feedback])=>({row,title,prompt,answer,answerPinyin,answerVi,feedback}));
Object.assign(decisions.find(d=>d.row==='044')!,{boundary:'除了A以外…还/也… ở ví dụ này bổ sung ngoài A. Với 除了小林以外，大家都来了, phạm vi “đều đến” loại Tiểu Lâm ra. Đọc cả vị ngữ và từ liên kết để xác định phạm vi, không suy từ 除了 một mình.'});
Object.assign(decisions.find(d=>d.row==='084')!,{example:['比赛中，主队一会儿领先，一会儿又被追平。','Bǐsài zhōng, zhǔduì yíhuìr lǐngxiān, yíhuìr yòu bèi zhuīpíng.','Trong trận, đội chủ nhà lúc dẫn trước, lúc lại bị gỡ hòa.']});
Object.assign(decisions.find(d=>d.row==='089')!,{example:['如果不能吃辣，就可以选旁边清淡的菜。','Rúguǒ bù néng chī là, jiù kěyǐ xuǎn pángbiān qīngdàn de cài.','Nếu không ăn cay được thì có thể chọn món thanh đạm bên cạnh.']});
Object.assign(decisions.find(d=>d.row==='091')!,{example:['只有收到邀请，才能参加这次家庭聚会。','Zhǐyǒu shōudào yāoqǐng, cái néng cānjiā zhè cì jiātíng jùhuì.','Chỉ khi nhận lời mời mới được dự buổi họp mặt gia đình này.'],boundary:'Lời mời là điều kiện cần do chủ nhà đặt cho buổi này. Câu không nói cứ có lời mời là mọi điều kiện khác đều được đáp ứng; không biến quy định một buổi thành phong tục chung.'});
Object.assign(decisions.find(d=>d.row==='092')!,{example:['只要给我发消息，我就把菜单发给你。','Zhǐyào gěi wǒ fā xiāoxi, wǒ jiù bǎ càidān fā gěi nǐ.','Chỉ cần nhắn cho tôi, tôi sẽ gửi thực đơn cho bạn.'],boundary:'Đây là lời chủ nhà cam kết về việc gửi thực đơn. Không được thay kết quả thành “được dự họp mặt”; không nói nhắn tin là cách duy nhất để biết thực đơn.'});
const visuals:Record<string,NarrativeVisual>={
 'lesson-01':{type:'timeline',title:'Khả năng, thứ tự và việc đã làm',description:'Hai phương tiện mới là khả năng. Hai bước mua–lấy vé có thứ tự. Cuối cùng nhóm dự hai hoạt động, chưa nêu tên cụ thể.',nodes:[['options','地铁或者公共汽车','dìtiě huòzhě gōnggòng qìchē','tàu điện hoặc xe buýt','Chưa biết lựa chọn cuối.'],['steps','先买票，然后取票','xiān mǎipiào, ránhòu qǔpiào','mua vé trước rồi lấy vé','Hai bước nối tiếp.'],['actual','只参加了两项','zhǐ cānjiā le liǎng xiàng','chỉ dự hai mục','Không phải tất cả hoạt động.']]},
 'lesson-02':{type:'timeline',title:'Trận đấu rồi tới nấu ăn',description:'Đội chủ nhà ghi điểm trước nhưng đội khách thắng cuối trận. Hoạt động nấu ăn diễn ra sau trận; nấu và giới thiệu diễn ra đồng thời.',nodes:[['first','主队先得分','zhǔduì xiān défēn','chủ nhà ghi điểm trước','Chưa phải kết quả cuối.'],['winner','客队最后赢了','kèduì zuìhòu yíng le','đội khách thắng','Giữ kết quả sau 可是.'],['cooking','一边做菜，一边介绍','yìbiān zuò cài, yìbiān jièshào','vừa nấu vừa giới thiệu','Hai việc cùng lúc sau trận.']]},
 'lesson-03':{type:'comparison',title:'Hai điều kiện, hai kết quả khác nhau',description:'Lời mời cần để tham gia. Nhắn tin đủ để chủ nhà gửi thực đơn. Có thực đơn chưa chứng minh có lời mời.',nodes:[['needed','收到邀请 → 才能参加','shōudào yāoqǐng → cái néng cānjiā','nhận lời mời → mới được dự','Điều kiện cần của buổi này.'],['enough','发消息 → 收到菜单','fā xiāoxi → shōudào càidān','nhắn tin → nhận thực đơn','Lời chủ nhà hứa gửi thực đơn.'],['limit','菜单不等于邀请','càidān bù děngyú yāoqǐng','thực đơn không phải lời mời','Không đổi kết quả giữa hai quy tắc.']]},
};
buildGrammarNarrativeBatch({lessonPrefix:'hsk3-discourse-linking',level:'hsk3',sourcePack:'hsk3-discourse-linking-narration-grammar-2026.07',outputFile:'thien-lo-hsk3-discourse-v2',manuscripts:discourseNarratives,decisions,visuals,answerReadings:{'lesson-01':['Hái bù zhīdào tāmen zuìhòu xuǎnzé le nǎ zhǒng jiāotōng gōngjù.','Chưa biết cuối cùng họ đã chọn phương tiện nào.'],'lesson-02':['Kèduì zuìhòu yíng le.','Đội khách thắng cuối trận.'],'lesson-03':['Hái bù néng quèdìng, shōudào càidān bù děngyú shōudào yāoqǐng.','Chưa xác định được; nhận thực đơn không đồng nghĩa nhận lời mời.']},targets:{'lesson-01':{reading:['083'],guided:['082'],writing:['083','082','044']},'lesson-02':{reading:['088'],guided:['088'],writing:['086','087','088','089']},'lesson-03':{reading:['091','092'],guided:['091'],writing:['091','092']}}});
