import {writeFileSync} from 'node:fs';
import {buildAuthoredBatch} from './build-authored-batch';
import type {SurvivalManuscript} from './survival-batch-manuscripts';
import {getRichLessonContent} from '../../src/learning/richLessonContent';
import {emptyLessonBlock,validateLessonPages} from '../../src/learning/lessonPages';
import {validateLessonActivitySources} from '../../src/learning/lessonActivitySources';
const motion='hsk2-travel-leisure-lesson-02',meeting='hsk2-travel-leisure-lesson-05';
const manuscripts:SurvivalManuscript[]=[{
 id:motion,focus:'Đến gần hay đi xa vị trí người nói?',scene:'A đứng ngoài cửa tầng một và ở nguyên đó. B đi lấy sách ở tầng hai rồi quay lại gặp A. Mọi lời chỉ đường của A trong hội thoại đều lấy vị trí ngoài cửa tầng một làm mốc.',support:'楼梯 lóutī: cầu thang · 拿书 ná shū: lấy sách · 等 děng: đợi · 再 zài: rồi/sau đó · 然后 ránhòu: sau đó. 进/出: vào/ra; 上/下: lên/xuống; 来/去 cho biết hướng về mốc hay rời mốc. Trong bài này mốc là chỗ người đang nói.',rule:'A đứng ngoài: gọi B đi vào tòa nhà là 进去; gọi B từ trong ra chỗ A là 出来. A đứng tầng một: B lên tầng hai xa A là 上去, B xuống về phía A là 下来.\n进/出、上/下 mô tả hướng không gian. 来/去 bổ sung quan hệ với vị trí làm mốc: 进来 là vào phía người nói đang ở bên trong; 进去 là vào phía xa người nói ở ngoài. Chỉ biết “vào” chưa đủ chọn 来/去.\n先…再…然后… nối các bước. 回来/回去 có nghĩa trở lại một nơi; 来/去 vẫn phụ thuộc góc nhìn. Bài giới hạn tình huống trực tiếp với mốc rõ, chưa xét các góc nhìn kể chuyện chuyển dịch.',pitfall:'Không dịch mọi chữ “vào” thành 进来. Nếu người nói chuyển từ ngoài vào trong, cùng một chuyển động có thể cần cách gọi khác. 下来 không có nghĩa lên, dù đều kết thúc bằng 来.',dialogue:[
 ['我在门外等你。你先进去。','Wǒ zài mén wài děng nǐ. Nǐ xiān jìnqu.','Tôi đợi bạn ngoài cửa. Bạn vào trong trước đi.'],
 ['进去以后怎么走？','Jìnqu yǐhòu zěnme zǒu?','Vào trong rồi đi thế nào?'],
 ['往前走，再从右边的楼梯上去。','Wǎng qián zǒu, zài cóng yòubian de lóutī shàngqu.','Đi thẳng, rồi lên bằng cầu thang bên phải.'],
 ['上二楼拿书，对吗？','Shàng èr lóu ná shū, duì ma?','Lên tầng hai lấy sách, đúng không?'],
 ['对，拿到书以后从那边下来。','Duì, ná dào shū yǐhòu cóng nàbiān xiàlái.','Đúng, lấy được sách rồi xuống theo lối đó.'],
 ['然后在哪儿找你？','Ránhòu zài nǎr zhǎo nǐ?','Rồi tôi gặp bạn ở đâu?'],
 ['对，出来以后到我这里来。','Duì, chūlái yǐhòu dào wǒ zhèlǐ lái.','Đúng, ra ngoài rồi đến chỗ tôi.'],
 ['好，我先进去，一会儿回来。','Hǎo, wǒ xiān jìnqu, yíhuìr huílái.','Được, tôi vào trước, lát nữa quay lại.'],
 ],question:'A vẫn đứng ngoài cửa tầng một. Câu A nói nào đúng cả mốc vị trí và thứ tự lấy sách?',choices:[['先进来，再上来，最后出去找我。','进来/上来 đặt người nói phía trong/trên, trái với vị trí A đang đứng ngoài tầng một.'],['先进去，再上去，拿到书以后下来、出来找我。','Đúng: đi vào/lên xa A, rồi xuống/ra về phía A đang đợi ngoài cửa.'],['先进去，再下来到二楼。','下来 là đi xuống; từ tầng một đến tầng hai phải lên.']],answer:1,transfer:'Đổi mốc: A ở trong phòng tầng hai và không rời phòng; B ở ngoài cửa tầng một. Viết ít nhất sáu lượt: hỏi A ở đâu, A trả lời, B hỏi cách đến, A bảo đi vào tòa nhà rồi lên chỗ A, B hỏi cửa nào, A mời vào phòng. Dùng 进去 cho bước vào tòa nhà, 上来 cho bước lên chỗ A và 进来 khi tới cửa phòng. Hỗ trợ: 房间 fángjiān: phòng.',model:['B：你在哪儿？ A：我在二楼的房间里。 B：我在一楼门外，怎么去找你？ A：先进去，再从右边的楼梯上来。 B：到二楼以后进哪个房间？ A：右边的房间，我在里面，你进来吧。','B: Nǐ zài nǎr? A: Wǒ zài èr lóu de fángjiān lǐ. B: Wǒ zài yī lóu mén wài, zěnme qù zhǎo nǐ? A: Xiān jìnqu, zài cóng yòubian de lóutī shànglái. B: Dào èr lóu yǐhòu jìn nǎ ge fángjiān? A: Yòubian de fángjiān, wǒ zài lǐmiàn, nǐ jìnlái ba.','B: Bạn ở đâu? A: Tôi ở trong phòng tầng hai. B: Tôi ngoài cửa tầng một, đến chỗ bạn thế nào? A: Vào tòa nhà trước rồi lên bằng cầu thang bên phải. B: Lên tầng hai thì vào phòng nào? A: Phòng bên phải, tôi ở trong, bạn vào đi.'],criteria:['A ở trong phòng tầng hai xuyên suốt; B bắt đầu ngoài tầng một.','Dùng 上来 khi A gọi B lên phía mình, không chép 上去 của mốc cũ.','Phân biệt bước vào tòa nhà với bước vào phòng nơi A đang ở.','Ít nhất sáu lượt hỏi/đáp có chỉ tầng, cầu thang và phòng rõ ràng.']
},{
 id:meeting,focus:'Thống nhất lịch hẹn, không dừng ở “lát nữa”',scene:'Hai bạn nói chuyện lúc 8:20 sáng. A đề nghị chơi bóng lúc 9:00 nhưng B chỉ rảnh từ 9:30. Cần đổi giờ, chọn đúng cửa gặp và xác nhận hoạt động. “Lát nữa” không thay được một giờ hẹn rõ.',support:'有空 yǒu kòng: rảnh · 半 bàn: rưỡi · 东门 dōngmén: cổng đông · 西门 xīmén: cổng tây · 篮球 lánqiú: bóng rổ · 还是 háishi: hay là (câu hỏi lựa chọn). Giờ 8:20 là lúc trò chuyện, không phải giờ gặp.',rule:'几点起来 hỏi giờ thức dậy; không phải giờ gặp. 九点有空吗？ hỏi khả năng theo đề xuất, chưa phải cuộc hẹn đã được đồng ý. 九点半以后才有空 giới hạn thời gian rảnh từ sau 9:30.\n那我们九点四十分… dùng 那 để điều chỉnh theo câu trả lời. 问东门还是西门 yêu cầu chọn một địa điểm. 我站在东门外面等你 xác định phía ngoài cổng, không phải bên trong hoặc cổng còn lại.\n一会儿 là một lát/lát nữa tùy ngữ cảnh, không có số phút cố định. Sau khi đồng ý cần nhắc lại giờ + nơi + hoạt động; 好，一会儿见 chỉ hợp khi các chi tiết đã rõ.',pitfall:'Không lấy 起来 lúc bảy giờ làm giờ gặp. Không giữ đề xuất chín giờ khi bạn nói chưa rảnh. 有空 yǒu kòng là rảnh; 空 trong nghĩa trống có cách đọc khác.',dialogue:[
 ['你今天几点起来的？','Nǐ jīntiān jǐ diǎn qǐlái de?','Hôm nay bạn dậy lúc mấy giờ?'],
 ['七点。你一会儿想做什么？','Qī diǎn. Nǐ yíhuìr xiǎng zuò shénme?','Bảy giờ. Lát nữa bạn muốn làm gì?'],
 ['九点一起去打篮球，好吗？','Jiǔ diǎn yìqǐ qù dǎ lánqiú, hǎo ma?','Chín giờ cùng đi chơi bóng rổ nhé?'],
 ['九点不行，我九点半以后才有空。','Jiǔ diǎn bù xíng, wǒ jiǔ diǎn bàn yǐhòu cái yǒu kòng.','Chín giờ không được, sau chín rưỡi tôi mới rảnh.'],
 ['那我们九点四十分在学校门口见。','Nà wǒmen jiǔ diǎn sìshí fēn zài xuéxiào ménkǒu jiàn.','Vậy chín giờ bốn mươi gặp ở cổng trường.'],
 ['东门还是西门？','Dōngmén háishi xīmén?','Cổng đông hay cổng tây?'],
 ['东门。我站在东门外面等你。','Dōngmén. Wǒ zhàn zài dōngmén wàimiàn děng nǐ.','Cổng đông. Tôi đứng ngoài cổng đông đợi bạn.'],
 ['好，九点四十分，东门外面，一起去打篮球。','Hǎo, jiǔ diǎn sìshí fēn, dōngmén wàimiàn, yìqǐ qù dǎ lánqiú.','Được, chín giờ bốn mươi, ngoài cổng đông, cùng đi chơi bóng rổ.'],
 ],question:'Thông báo nhắc lịch nào khớp cuộc hẹn cuối cùng?',choices:[['九点在学校东门外面见，一起打篮球。','Địa điểm/hoạt động đúng nhưng chín giờ là đề xuất đã bị từ chối.'],['九点四十分在学校西门见，一起打篮球。','Giờ đúng nhưng sai cổng: hai bạn chọn cổng đông.'],['九点四十分在学校东门外面见，一起打篮球。','Đúng đủ giờ đã điều chỉnh, ngoài cổng đông và chơi bóng rổ.']],answer:2,transfer:'Lịch mới: chiều nay A đề nghị 3:00 đi bơi; B chỉ rảnh sau 3:30. Hai người chốt 3:45, gặp bên ngoài cổng tây trường. Viết ít nhất sáu lượt có đề xuất, từ chối giờ đầu, đề xuất mới, hỏi lại cổng và xác nhận đủ giờ/nơi/hoạt động. Hỗ trợ: 下午 xiàwǔ: buổi chiều · 游泳 yóuyǒng: bơi.',model:['A：下午三点一起去游泳，好吗？ B：三点不行，我三点半以后才有空。 A：那三点四十五分在学校门口见。 B：东门还是西门？ A：西门外面。 B：好，下午三点四十五分，学校西门外面，一起去游泳。','A: Xiàwǔ sān diǎn yìqǐ qù yóuyǒng, hǎo ma? B: Sān diǎn bù xíng, wǒ sān diǎn bàn yǐhòu cái yǒu kòng. A: Nà sān diǎn sìshíwǔ fēn zài xuéxiào ménkǒu jiàn. B: Dōngmén háishi xīmén? A: Xīmén wàimiàn. B: Hǎo, xiàwǔ sān diǎn sìshíwǔ fēn, xuéxiào xīmén wàimiàn, yìqǐ qù yóuyǒng.','A: Ba giờ chiều cùng đi bơi nhé? B: Ba giờ không được, sau ba rưỡi tôi mới rảnh. A: Vậy ba giờ bốn mươi lăm gặp ở cổng trường. B: Cổng đông hay tây? A: Ngoài cổng tây. B: Được, ba giờ bốn mươi lăm chiều, ngoài cổng tây trường, cùng đi bơi.'],criteria:['Phân biệt 3:00 đề xuất đầu và 3:45 là giờ được chốt sau khi B từ chối.','Có buổi chiều, ngoài cổng tây trường; không chép cổng đông buổi sáng.','Hoạt động là đi bơi; câu cuối xác nhận đủ giờ/nơi/hoạt động.','Ít nhất sáu lượt, lời đề nghị mới đáp ứng giới hạn rảnh sau 3:30.']
}];
// Keep the transfer's reference point explicit for all three directional complements.
manuscripts[0].transfer='Đổi mốc: A ở trong phòng bên phải tầng hai và không rời phòng; B đã ở trong tòa nhà, dưới tầng một. Viết ít nhất tám lượt: hỏi A ở đâu và cách đến; A gọi B lên rồi vào phòng; B hỏi xong việc có cần xuống không; A bảo B xuống tầng một đợi trong khi A ở lại. Dùng 上来, 进来 và 下去 trong lời A. Hỗ trợ: 房间 fángjiān: phòng · 办完事 bàn wán shì: làm xong việc · 留 liú: ở lại.';
manuscripts[0].model=['B：你在哪儿？ A：我在二楼右边的房间里。 B：我在一楼，怎么去找你？ A：从右边的楼梯上来。 B：到房间门口以后呢？ A：我在里面，你进来吧。 B：办完事以后，我要下楼吗？ A：对，你下去，在一楼等我。我还要留在二楼。','B: Nǐ zài nǎr? A: Wǒ zài èr lóu yòubian de fángjiān lǐ. B: Wǒ zài yī lóu, zěnme qù zhǎo nǐ? A: Cóng yòubian de lóutī shànglái. B: Dào fángjiān ménkǒu yǐhòu ne? A: Wǒ zài lǐmiàn, nǐ jìnlái ba. B: Bàn wán shì yǐhòu, wǒ yào xià lóu ma? A: Duì, nǐ xiàqu, zài yī lóu děng wǒ. Wǒ hái yào liú zài èr lóu.','B: Bạn ở đâu? A: Tôi trong phòng bên phải tầng hai. B: Tôi ở tầng một, đến chỗ bạn thế nào? A: Lên đây bằng cầu thang bên phải. B: Tới cửa phòng rồi thì sao? A: Tôi ở trong, bạn vào đây đi. B: Xong việc tôi phải xuống tầng dưới không? A: Đúng, bạn xuống tầng một đợi tôi. Tôi còn ở lại tầng hai.'];
manuscripts[0].criteria=['A ở phòng tầng hai xuyên suốt; B xuất phát bên trong tầng một.','Lời A dùng 上来 và 进来 cho chuyển động về phía mình.','Lời A dùng 下去 khi B xuống xa A; không thay bằng 下来.','Ít nhất tám lượt liên kết, đủ tầng, cầu thang, phòng và nơi đợi sau khi xong việc.'];
const examples:Record<string,[string,string,string]>={
 '出':['请从这个门出。','Qǐng cóng zhège mén chū.','Hãy ra bằng cửa này.'],
 '出来':['我在外面，你出来吧。','Wǒ zài wàimiàn, nǐ chūlái ba.','Tôi ở ngoài, bạn ra đây đi.'],
 '出去':['我在里面，他出去买水了。','Wǒ zài lǐmiàn, tā chūqù mǎi shuǐ le.','Tôi ở trong, anh ấy ra ngoài mua nước rồi.'],
 '过来':['我在门口，你过来吧。','Wǒ zài ménkǒu, nǐ guòlái ba.','Tôi ở cửa, bạn qua đây đi.'],
 '过去':['我留在这里，你过去看看。','Wǒ liú zài zhèlǐ, nǐ guòqu kànkan.','Tôi ở lại đây, bạn qua đó xem đi.'],
 '回来':['我在家等你回来。','Wǒ zài jiā děng nǐ huílái.','Tôi ở nhà đợi bạn về.'],
 '回去':['我还在学校，他先回去了。','Wǒ hái zài xuéxiào, tā xiān huíqu le.','Tôi vẫn ở trường, anh ấy về trước rồi.'],
 '进':['请从右边的门进。','Qǐng cóng yòubian de mén jìn.','Hãy vào bằng cửa bên phải.'],
 '进来':['我在房间里，你进来吧。','Wǒ zài fángjiān lǐ, nǐ jìnlái ba.','Tôi ở trong phòng, bạn vào đây đi.'],
 '进去':['我在外面等，你先进去。','Wǒ zài wàimiàn děng, nǐ xiān jìnqu.','Tôi đợi ở ngoài, bạn vào trước đi.'],
 '上来':['我在二楼，你上来吧。','Wǒ zài èr lóu, nǐ shànglái ba.','Tôi ở tầng hai, bạn lên đây đi.'],
 '上去':['我在一楼等，你先上去。','Wǒ zài yī lóu děng, nǐ xiān shàngqu.','Tôi đợi ở tầng một, bạn lên trước đi.'],
 '下来':['我在楼下，你下来吧。','Wǒ zài lóuxià, nǐ xiàlái ba.','Tôi ở dưới tầng, bạn xuống đây đi.'],
 '下去':['我留在二楼，你先下去。','Wǒ liú zài èr lóu, nǐ xiān xiàqu.','Tôi ở lại tầng hai, bạn xuống trước đi.'],
 '走':['往前走，到门口等我。','Wǎng qián zǒu, dào ménkǒu děng wǒ.','Đi thẳng, đến cửa đợi tôi.'],
 '起来':['我今天七点起来。','Wǒ jīntiān qī diǎn qǐlái.','Hôm nay tôi dậy lúc bảy giờ.'],
 '一会儿':['等一会儿，我们一起走。','Děng yíhuìr, wǒmen yìqǐ zǒu.','Đợi một lát, chúng ta cùng đi.'],
 '一起':['下午我们一起去游泳。','Xiàwǔ wǒmen yìqǐ qù yóuyǒng.','Chiều chúng ta cùng đi bơi.'],
 '站':['我站在西门外面等你。','Wǒ zhàn zài xīmén wàimiàn děng nǐ.','Tôi đứng ngoài cổng tây đợi bạn.'],
};
const items=buildAuthoredBatch({level:'hsk2',manuscripts,examples,practiceByLesson:{
 [motion]:{pattern:'Người nói ở trong → 进来',example:['我在房间里，你进来吧。','Wǒ zài fángjiān lǐ, nǐ jìnlái ba.','Tôi ở trong phòng, bạn vào đây đi.'],prompt:'Người nói đang ở trong phòng, gọi bạn vào phía mình: 我在房间里，你进___吧。 Điền 来 hoặc 去.',answers:['来'],explanation:'来 diễn tả về phía người nói đang ở trong. 去 sẽ chỉ hướng xa mốc người nói.'},
 [meeting]:{pattern:'Giờ + 在 + nơi + 见',example:['九点四十分在东门外面见。','Jiǔ diǎn sìshí fēn zài dōngmén wàimiàn jiàn.','Chín giờ bốn mươi gặp ở ngoài cổng đông.'],prompt:'Cuộc hẹn cuối cùng: 九点___分在学校东门外面见。 Điền số phút bằng chữ Hán.',answers:['四十'],explanation:'Hai bạn chốt 9:40. 9:00 bị từ chối, 9:30 là mốc B bắt đầu rảnh, chưa phải giờ hẹn.'},
},answerReadings:{[motion]:['Xiān jìnqu, zài shàngqu, ná dào shū yǐhòu xiàlái, chūlái zhǎo wǒ.','Vào trước rồi lên, lấy sách xong xuống và ra chỗ tôi.'],[meeting]:['Jiǔ diǎn sìshí fēn zài xuéxiào dōngmén wàimiàn jiàn, yìqǐ dǎ lánqiú.','Chín giờ bốn mươi gặp ngoài cổng đông trường, cùng chơi bóng rổ.']}});
for(const item of items){
 const isMotion=item.lessonId===motion,rich=getRichLessonContent(item.lessonId)!;
 const labels=isMotion?[
 ['门外一楼','mén wài yī lóu','A ngoài cửa, tầng một','A ở nguyên vị trí này trong hội thoại.'],['进去 → 上去','jìnqu → shàngqu','B đi vào rồi lên','Di chuyển xa vị trí A.'],['下来 → 出来','xiàlái → chūlái','B xuống rồi ra','Trở về phía A đang đợi.'],
 ]:[['九点','jiǔ diǎn','9:00','Đề xuất bị từ chối.'],['九点半以后','jiǔ diǎn bàn yǐhòu','Sau 9:30','Khoảng B mới rảnh, chưa phải giờ hẹn.'],['九点四十分','jiǔ diǎn sìshí fēn','9:40','Đã chốt: ngoài cổng đông, chơi bóng rổ.']];
 item.lessonPages.pages.splice(2,0,{id:`${item.lessonId}:v2:facts`,title:isMotion?'Giữ cố định mốc người nói':'Từ đề nghị đến giờ đã chốt',layout:'focus',stage:'understand',blocks:[{...emptyLessonBlock(`${item.lessonId}:v2:block:facts`),kind:'diagram',title:isMotion?'A ở đâu, B đi hướng nào?':'Ba mốc giờ có vai trò khác nhau',diagram:{type:isMotion?'comparison':'timeline',description:isMotion?'Sơ đồ diễn giải góc nhìn, không phải bản đồ mặt bằng. Khi đổi vị trí người nói, cần xét lại 来/去.':'Không lấy giờ thức dậy hoặc đề xuất bị từ chối làm giờ gặp.',nodes:labels.map(([label,pinyin,meaningVi,note],i)=>({id:`fact-${i}`,label,pinyin,meaningVi,note,x:i,y:0}))}}]});
 for(const page of item.lessonPages.pages)for(const block of page.blocks)if(block.activity)block.activity.learningTarget={skill:'grammar',objective:block.id.endsWith(':guided')?(isMotion?'Chọn 来/去 theo vị trí người nói đã cho.':'Phân biệt giờ đề xuất, giờ rảnh và giờ đã chốt.'):block.id.endsWith(':produce')?(isMotion?'Viết chuỗi chỉ hướng khi đổi vị trí người nói; tự đối chiếu.':'Viết chuỗi thương lượng và xác nhận lịch hẹn mới; tự đối chiếu.'):(isMotion?'Kể đúng thứ tự chuyển động và mốc 来/去.':'Xác nhận đủ giờ, nơi và hoạt động sau thương lượng.'),sources:[{kind:block.id.endsWith(':guided')?'grammar':'task',id:block.id.endsWith(':guided')?rich.grammar[0].id:rich.tasks[0].id}]};
 const errors=[...validateLessonPages(item.lessonPages),...validateLessonActivitySources(item.lessonId,item.lessonPages)];if(errors.length)throw new Error(errors.join('\n'));
}
writeFileSync('content/drafts/thien-lo-hsk2-motion-meeting-v2.json',JSON.stringify({schemaVersion:1,humanReviewed:false,status:'draft-not-published',items},null,2)+'\n');
console.log(items.map(i=>({lesson:i.lessonId,pages:i.lessonPages.pages.length,published:false})));
