import {writeFileSync} from 'node:fs';
import {buildAuthoredBatch,type BatchPractice} from './build-authored-batch';
import type {SurvivalManuscript} from './survival-batch-manuscripts';
import {getRichLessonContent} from '../../src/learning/richLessonContent';
import {emptyLessonBlock,validateLessonPages} from '../../src/learning/lessonPages';
import {validateLessonActivitySources} from '../../src/learning/lessonActivitySources';
const food='hsk2-daily-needs-family-lesson-02',shopping='hsk2-daily-needs-family-lesson-03';
const manuscripts:SurvivalManuscript[]=[
 {id:food,focus:'Từ thói quen đến quyết định bữa tối',scene:'Hai bạn chọn bữa tối hôm nay. Một người thường ăn ở nhà nhưng hôm nay chưa chuẩn bị cơm. Cần chốt nơi ăn, món, đồ uống và giờ gặp; đừng lấy thói quen làm quyết định hôm nay.',support:'晚饭 wǎnfàn: bữa tối · 今天 jīntiān: hôm nay · 家 jiā: nhà · 六点 liù diǎn: sáu giờ · 鸡肉 jīròu: thịt gà. Có Pinyin và nghĩa để hỗ trợ; giọng nghe là tổng hợp.',rule:'经常 + hành động nêu thói quen: 我经常在家吃饭. 没准备晚饭 nói chưa chuẩn bị bữa tối trong tình huống hôm nay; không có nghĩa chẳng bao giờ nấu ăn.\nĐộng từ + 过 nói trải nghiệm: 我喝过红茶 (từng uống hồng trà), không đồng nghĩa 经常喝 (thường uống). Phủ định trải nghiệm: 没喝过. A 还是 B hỏi lựa chọn; hãy xác nhận một món hoặc đồ uống rồi chốt giờ/nơi.',pitfall:'Không suy ra thói quen từ một lần đã từng làm. 不吃鱼 nói không ăn cá trong ngữ cảnh này; 没吃过鱼 nói chưa từng ăn cá. Khi người kia hỏi đồ uống, trả lời món cá chưa giải quyết câu hỏi.',dialogue:[
 ['你经常在饭馆吃晚饭吗？','Nǐ jīngcháng zài fànguǎn chī wǎnfàn ma?','Bạn có thường ăn tối ở nhà hàng không?'],
 ['不，我经常在家吃。今天没准备晚饭。','Bù, wǒ jīngcháng zài jiā chī. Jīntiān méi zhǔnbèi wǎnfàn.','Không, tôi thường ăn ở nhà. Hôm nay tôi chưa chuẩn bị bữa tối.'],
 ['那我们去饭馆吧。你想吃肉还是鱼？','Nà wǒmen qù fànguǎn ba. Nǐ xiǎng chī ròu háishi yú?','Vậy chúng ta ra nhà hàng nhé. Bạn muốn ăn thịt hay cá?'],
 ['我想吃鱼。喝绿茶还是奶茶？','Wǒ xiǎng chī yú. Hē lǜchá háishi nǎichá?','Tôi muốn ăn cá. Uống trà xanh hay trà sữa?'],
 ['绿茶吧。我们六点在饭馆见，好吗？','Lǜchá ba. Wǒmen liù diǎn zài fànguǎn jiàn, hǎo ma?','Trà xanh nhé. Sáu giờ chúng ta gặp ở nhà hàng, được không?'],
 ['好，六点见。','Hǎo, liù diǎn jiàn.','Được, sáu giờ gặp nhé.'],
 ],question:'Vai B thường ăn ở nhà, hôm nay chưa chuẩn bị cơm và đã đồng ý ra nhà hàng. Chọn câu nói đúng hôm nay.',choices:[['我今天在饭馆吃晚饭。','Đúng: đây là quyết định hôm nay, không phủ nhận thói quen ở nhà.'],['我每天都在饭馆吃饭。','每天都 nói ngày nào cũng ăn nhà hàng, trái thói quen đã cho.'],['我没喝过绿茶。','Câu này nói chưa từng uống trà xanh, không xác nhận nơi ăn tối.']],answer:0,transfer:'Đổi vai: bạn thường ăn ở nhà, hôm nay muốn ăn thịt gà và uống hồng trà tại nhà hàng lúc bảy giờ. Viết ít nhất sáu lượt: hỏi thói quen, giải thích hôm nay, hỏi/chọn món, hỏi/chọn đồ uống, đề xuất và xác nhận giờ/nơi.',model:['A：你经常在家吃饭吗？ B：是，今天我想去饭馆。 A：吃鱼还是鸡肉？ B：鸡肉。我想喝红茶。 A：七点在饭馆见，好吗？ B：好，七点见。','A: Nǐ jīngcháng zài jiā chīfàn ma? B: Shì, jīntiān wǒ xiǎng qù fànguǎn. A: Chī yú háishi jīròu? B: Jīròu. Wǒ xiǎng hē hóngchá. A: Qī diǎn zài fànguǎn jiàn, hǎo ma? B: Hǎo, qī diǎn jiàn.','A: Bạn thường ăn ở nhà không? B: Đúng, hôm nay tôi muốn ra nhà hàng. A: Cá hay thịt gà? B: Thịt gà. Tôi muốn uống hồng trà. A: Gặp ở nhà hàng lúc bảy giờ nhé? B: Được, bảy giờ gặp.'],criteria:['Phân biệt 经常 với quyết định 今天, không biến thành 每天都 ở nhà hàng.','Món là thịt gà, đồ uống là hồng trà; câu trả lời khớp câu hỏi.','Chốt bảy giờ tại nhà hàng và có xác nhận; chuỗi vai nhất quán.']},
 {id:shopping,focus:'So đặc điểm và giá rồi mới quyết định',scene:'Bạn cần quần ngắn hơn chiếc đang thử, ngân sách tối đa 100 tệ. Quần A dài, giá 100; quần B ngắn hơn, giá 80. Cần hỏi, so đặc điểm, xác nhận giá rồi mới quyết định.',support:'长 cháng: dài · 短 duǎn: ngắn · 颜色 yánsè: màu sắc · 黑色 hēisè: màu đen · 蓝色 lánsè: màu xanh lam · 价钱 jiàqian: giá tiền · 块 kuài: đơn vị tiền trong lời nói.',rule:'这条裤子 có 条 làm lượng từ cho quần. 有点儿长 diễn tả hơi dài, thường hàm ý chưa phù hợp; không chỉ là đánh giá trung tính. 颜色不错，但是有点儿长 nối ưu điểm với vấn đề.\n多少钱 hỏi giá; 花 + số tiền nói khoản chi: 我花了八十块钱. 拿 trong 我拿这条吧 là chọn/lấy chiếc này ở quầy. Một món có thể đẹp nhưng không phù hợp kích thước hoặc ngân sách.',pitfall:'Không chọn chỉ vì giá nằm trong ngân sách: còn phải đáp ứng độ dài. 花 trong 花八十块钱 là tiêu tiền, không phải hoa. 坏了 là bị hỏng; không gọi chiếc quần hơi dài là hỏng.',dialogue:[
 ['这条裤子怎么样？','Zhè tiáo kùzi zěnmeyàng?','Chiếc quần này thế nào?'],
 ['颜色不错，但是有点儿长。有没有短一点儿的？','Yánsè búcuò, dànshì yǒudiǎnr cháng. Yǒu méiyǒu duǎn yìdiǎnr de?','Màu khá đẹp nhưng hơi dài. Có chiếc ngắn hơn một chút không?'],
 ['有，这条蓝色的短一点儿。','Yǒu, zhè tiáo lánsè de duǎn yìdiǎnr.','Có, chiếc màu xanh lam này ngắn hơn một chút.'],
 ['这条多少钱？','Zhè tiáo duōshao qián?','Chiếc này bao nhiêu tiền?'],
 ['八十块。那条黑色的一百块。','Bāshí kuài. Nà tiáo hēisè de yì bǎi kuài.','Tám mươi tệ. Chiếc màu đen kia một trăm tệ.'],
 ['好，我拿这条蓝色的。','Hǎo, wǒ ná zhè tiáo lánsè de.','Được, tôi lấy chiếc màu xanh lam này.'],
 ],question:'Ngân sách 100 tệ, cần quần ngắn hơn. A: đen/dài/100 tệ. B: xanh lam/ngắn hơn/80 tệ. Chọn quyết định thỏa cả hai điều kiện.',choices:[['我拿黑色的，一百块。','Đủ ngân sách nhưng chiếc đen vẫn dài, chưa đáp ứng điều kiện kích thước.'],['我拿蓝色的，八十块。','Đúng: chiếc xanh ngắn hơn và giá 80 không vượt 100.'],['我的手表坏了。','Nói đồng hồ hỏng, chưa quyết định mua quần.']],answer:1,transfer:'Tình huống mới: chọn túi để tặng bạn. Túi đỏ đẹp nhưng 120 tệ, túi đen cũng đẹp và 90 tệ; ngân sách 100. Viết sáu lượt có hỏi món, mô tả màu và giá, hỏi lại rồi chọn túi đen. Không chép lượng từ 条 của quần; dùng 个 cho túi. 红色 hóngsè: màu đỏ.',model:['A：你想买什么？ B：我想买一个包送给朋友。 A：这个红色的怎么样？ B：很好看，多少钱？ A：一百二十块。黑色的九十块。 B：我只有一百块，我拿黑色的吧。','A: Nǐ xiǎng mǎi shénme? B: Wǒ xiǎng mǎi yí ge bāo sòng gěi péngyou. A: Zhège hóngsè de zěnmeyàng? B: Hěn hǎokàn, duōshao qián? A: Yì bǎi èrshí kuai. Hēisè de jiǔshí kuai. B: Wǒ zhǐ yǒu yì bǎi kuai, wǒ ná hēisè de ba.','A: Bạn muốn mua gì? B: Tôi muốn mua túi tặng bạn. A: Túi đỏ này thế nào? B: Đẹp, giá bao nhiêu? A: 120 tệ. Túi đen 90. B: Tôi chỉ có 100 tệ, lấy túi đen nhé.'],criteria:['Nói túi tặng bạn, dùng 一个包 hoặc 这个包; không dùng 条 của quần.','Nêu rõ đỏ 120, đen 90, ngân sách 100; lựa chọn không vượt ngân sách.','Có hỏi giá và quyết định lấy túi đen; mô tả đẹp không đồng nghĩa đã mua.']},
];
const examples:Record<string,[string,string,string]>={
 '饭馆':['这家饭馆很近。','Zhè jiā fànguǎn hěn jìn.','Nhà hàng này rất gần.'],'过':['我喝过红茶。','Wǒ hē guo hóngchá.','Tôi từng uống hồng trà.'],'红茶':['我想喝一杯红茶。','Wǒ xiǎng hē yì bēi hóngchá.','Tôi muốn uống một cốc hồng trà.'],'经常':['我经常在家吃饭。','Wǒ jīngcháng zài jiā chīfàn.','Tôi thường ăn ở nhà.'],'咖啡':['这杯咖啡很热。','Zhè bēi kāfēi hěn rè.','Cốc cà phê này nóng.'],'绿茶':['你喝绿茶吗？','Nǐ hē lǜchá ma?','Bạn uống trà xanh không?'],'奶茶':['她想喝奶茶。','Tā xiǎng hē nǎichá.','Cô ấy muốn uống trà sữa.'],'肉':['我今天不想吃肉。','Wǒ jīntiān bù xiǎng chī ròu.','Hôm nay tôi không muốn ăn thịt.'],'鱼':['这条鱼很大。','Zhè tiáo yú hěn dà.','Con cá này rất to.'],'准备':['我在准备晚饭。','Wǒ zài zhǔnbèi wǎnfàn.','Tôi đang chuẩn bị bữa tối.'],
 '包':['这个包是给朋友的。','Zhège bāo shì gěi péngyou de.','Túi này dành cho bạn tôi.'],'花':['我买这个包花了九十块钱。','Wǒ mǎi zhège bāo huā le jiǔshí kuài qián.','Tôi mua túi này hết chín mươi tệ.'],'坏':['我的手表坏了。','Wǒ de shǒubiǎo huài le.','Đồng hồ của tôi hỏng rồi.'],'裤子':['这条裤子有点儿长。','Zhè tiáo kùzi yǒudiǎnr cháng.','Chiếc quần này hơi dài.'],'拿':['我拿这个黑色的包。','Wǒ ná zhège hēisè de bāo.','Tôi lấy túi màu đen này.'],'商场':['我们去商场买衣服。','Wǒmen qù shāngchǎng mǎi yīfu.','Chúng tôi đến trung tâm thương mại mua quần áo.'],'手表':['这块手表是新的。','Zhè kuài shǒubiǎo shì xīn de.','Chiếc đồng hồ này là đồ mới.'],'送':['我想送给你一本书。','Wǒ xiǎng sòng gěi nǐ yì běn shū.','Tôi muốn tặng bạn một cuốn sách.'],'位':['这位老师是我的朋友。','Zhè wèi lǎoshī shì wǒ de péngyou.','Vị giáo viên này là bạn tôi.'],
};
// The transfer prompt asks both the food and drink questions explicitly.
manuscripts[0].model=[
 'A：你经常在家吃饭吗？ B：是，今天我想去饭馆。 A：吃鱼还是鸡肉？ B：鸡肉。 A：喝绿茶还是红茶？ B：红茶。 A：七点在饭馆见，好吗？ B：好，七点见。',
 'A: Nǐ jīngcháng zài jiā chīfàn ma? B: Shì, jīntiān wǒ xiǎng qù fànguǎn. A: Chī yú háishi jīròu? B: Jīròu. A: Hē lǜchá háishi hóngchá? B: Hóngchá. A: Qī diǎn zài fànguǎn jiàn, hǎo ma? B: Hǎo, qī diǎn jiàn.',
 'A: Bạn thường ăn ở nhà không? B: Đúng, hôm nay tôi muốn ra nhà hàng. A: Cá hay thịt gà? B: Thịt gà. A: Trà xanh hay hồng trà? B: Hồng trà. A: Gặp ở nhà hàng lúc bảy giờ nhé? B: Được, bảy giờ gặp.',
];
const practiceByLesson:Record<string,BatchPractice>={
 [food]:{pattern:'没 + động từ + 过',example:['我没喝过红茶。','Wǒ méi hē guo hóngchá.','Tôi chưa từng uống hồng trà.'],prompt:'Điền đúng từ phủ định trải nghiệm theo mẫu: 我___喝过红茶。 (Tôi chưa từng uống hồng trà.)',answers:['没','没有'],explanation:'没/没有 + 喝过 diễn tả chưa từng uống. 不喝 thường là không uống, không mang nghĩa chưa từng.'},
 [shopping]:{pattern:'这 + lượng từ + danh từ',example:['这条裤子八十块。','Zhè tiáo kùzi bāshí kuai.','Chiếc quần này tám mươi tệ.'],prompt:'Điền đúng lượng từ cho quần trong mẫu đã học: 这___裤子八十块。',answers:['条'],explanation:'这条裤子: 条 dùng với quần. 个 dùng trong mẫu 一个包 của tình huống đổi sang mua túi.'},
};
const items=buildAuthoredBatch({manuscripts,examples,practiceByLesson,answerReadings:{[food]:['Wǒ jīntiān zài fànguǎn chī wǎnfàn.','Hôm nay tôi ăn tối ở nhà hàng.'],[shopping]:['Wǒ ná lánsè de, bāshí kuai.','Tôi lấy chiếc xanh lam, tám mươi tệ.']},level:'hsk2'});
for(const item of items){
 const rich=getRichLessonContent(item.lessonId)!;
 for(const page of item.lessonPages.pages)for(const block of page.blocks)if(block.activity)block.activity.learningTarget={skill:'grammar',objective:block.id.endsWith(':produce')?'Tự viết chuỗi trao đổi theo dữ kiện mới; rubric tự đối chiếu, không chấm nói/viết độc lập.':block.id.endsWith(':guided')?practiceByLesson[item.lessonId].prompt:manuscripts.find(m=>m.id===item.lessonId)!.question,sources:[{kind:block.id.endsWith(':guided')?'grammar':'task',id:block.id.endsWith(':guided')?rich.grammar[0].id:rich.tasks[0].id}]};
 const nodes=item.lessonId===food?[['Thói quen','经常在家吃饭','jīngcháng zài jiā chīfàn','Thường ăn ở nhà'],['Hôm nay','没准备晚饭','méi zhǔnbèi wǎnfàn','Chưa chuẩn bị bữa tối'],['Quyết định','六点在饭馆见','liù diǎn zài fànguǎn jiàn','Gặp ở nhà hàng lúc sáu giờ']]:[['A','黑色 · 长 · 一百块','hēisè · cháng · yì bǎi kuai','Đen, dài, 100 tệ'],['B','蓝色 · 短一点儿 · 八十块','lánsè · duǎn yìdiǎnr · bāshí kuai','Xanh lam, ngắn hơn, 80 tệ']];
 item.lessonPages.pages.splice(1,0,{id:`${item.lessonId}:v2:facts`,title:item.lessonId===food?'Tách ba lớp thông tin':'So hai chiếc quần',layout:'focus',stage:'understand',blocks:[{...emptyLessonBlock(`${item.lessonId}:v2:block:facts`),kind:'diagram',title:'Dữ kiện để quyết định',diagram:{type:item.lessonId===food?'sequence':'comparison',description:item.lessonId===food?'Thói quen không quyết định mọi ngày; nối lý do hôm nay với lịch đã chốt.':'Ngân sách tối đa 100, cần quần ngắn hơn. So đồng thời độ dài và giá.',nodes:nodes.map(([name,label,pinyin,meaningVi],i)=>({id:`fact-${i}`,label,pinyin,meaningVi,note:name,x:i,y:0}))}}]});
 const errors=[...validateLessonPages(item.lessonPages),...validateLessonActivitySources(item.lessonId,item.lessonPages)];if(errors.length)throw new Error(errors.join('\n'));
}
writeFileSync('content/drafts/thien-lo-hsk2-food-shopping-v2.json',JSON.stringify({schemaVersion:1,humanReviewed:false,status:'draft-not-published',items},null,2)+'\n');
console.log({lessons:items.length,pages:items.reduce((n,i)=>n+i.lessonPages.pages.length,0),published:false});
