/** Original supported transfer tasks; model answers are for self-comparison. */
export const characterTransfers:Record<string,{prompt:string;hanzi:string;pinyin:string;meaning:string;criteria:string[]}>={
 'characters-1':{prompt:'Giới thiệu bạn là sinh viên đại học. Dùng khung 我是… (tôi là…). Chọn đúng chữ chỉ đại học và thêm chữ chỉ người học.',hanzi:'我是大学生。',pinyin:'Wǒ shì dàxuéshēng.',meaning:'Tôi là sinh viên đại học.',criteria:['大学生 chỉ sinh viên đại học; 大学 chỉ trường đại học.','Giữ 大, không thêm chấm thành 太.','Đặt 我是 trước danh tính.']},
 'characters-2':{prompt:'Cuối buổi gặp, nói sẽ gặp lại vào ngày mai. Từ hỗ trợ: 明天 míngtiān = ngày mai. Ghép với chữ mang ý gặp.',hanzi:'明天见！',pinyin:'Míngtiān jiàn!',meaning:'Hẹn gặp ngày mai!',criteria:['Dùng 见 cho việc gặp; không dùng 贝.','Đặt 明天 trước 见.','Hiểu câu dùng khi kết thúc cuộc gặp.']},
 'characters-3':{prompt:'Nhìn ảnh gia đình, hỏi “Đây là mẹ của bạn phải không?”. Khung hỗ trợ: 这是你的…吗？ (Đây là … của bạn phải không?).',hanzi:'这是你的妈妈吗？',pinyin:'Zhè shì nǐ de māma ma?',meaning:'Đây là mẹ của bạn phải không?',criteria:['妈妈 chỉ mẹ, phần trái là 女.','吗 ở cuối tạo câu hỏi, phần trái là 口.','Không thay chữ 妈 trong danh từ bằng 吗.']},
 'characters-4':{prompt:'Hỏi thăm một người lớn tuổi bằng cách xưng hô lịch sự. Khung: …好吗？ (… khỏe không?).',hanzi:'您好吗？',pinyin:'Nín hǎo ma?',meaning:'Bác có khỏe không?',criteria:['Chọn 您 để thể hiện cách xưng hô lịch sự.','Giữ phần 心 phía dưới 您.','Đây là lời hỏi thăm thực sự, không bắt buộc nói trong mọi lời chào.']},
 'characters-5':{prompt:'Giới thiệu một cô giáo trong ảnh. Khung: …是老师。 (... là giáo viên). Từ hỗ trợ: 老师 lǎoshī.',hanzi:'她是老师。',pinyin:'Tā shì lǎoshī.',meaning:'Cô ấy là giáo viên.',criteria:['Dùng 她 cho người nữ đã xác định trong tình huống.','Không dùng 它 cho cô giáo.','Âm tā giống nhau nhưng khi viết phải chọn đúng hình.']},
 'characters-6':{prompt:'Nói bạn đang ở nhà rồi tạm biệt. Hỗ trợ: 我…家。 (Tôi ở nhà); 家 jiā = nhà. Viết hai câu.',hanzi:'我在家。再见！',pinyin:'Wǒ zài jiā. Zàijiàn!',meaning:'Tôi ở nhà. Tạm biệt!',criteria:['在 đi với vị trí 家.','再 đi trong lời tạm biệt 再见.','Không đổi 在 và 再 dù cùng âm zài.']},
 'characters-7':{prompt:'Nói bạn đi học vào ban ngày. Khung: 我…上学。 (Tôi đi học vào…). Hỗ trợ: 上学 shàngxué = đi học.',hanzi:'我白天上学。',pinyin:'Wǒ báitiān shàngxué.',meaning:'Tôi đi học vào ban ngày.',criteria:['Dùng 白天 để nói ban ngày.','Không thêm nét ngang thành 百.','Đặt thời gian 白天 trước hoạt động 上学.']},
 'characters-8':{prompt:'Hẹn gặp vào chủ nhật. Hỗ trợ: 星期…见！ (Hẹn gặp vào thứ…); 见 jiàn = gặp.',hanzi:'星期日见！',pinyin:'Xīngqīrì jiàn!',meaning:'Hẹn gặp chủ nhật!',criteria:['日 trong 星期日 có một nét ngang bên trong khung.','Không dùng 目 thay 日.','星期天见 cũng có nghĩa tương đương, nhưng lượt này luyện chữ 日.']},
 'characters-9':{prompt:'Đổi lời hẹn buổi sáng 上午见！ sang buổi chiều. Giữ phần “hẹn gặp” và đổi đúng phần thời gian.',hanzi:'下午见！',pinyin:'Xiàwǔ jiàn!',meaning:'Hẹn gặp buổi chiều!',criteria:['Đổi 上 thành 下 để chuyển buổi sáng sang buổi chiều.','Giữ 午 và 见.','Đọc cả cụm 下午, không chỉ nhớ hình riêng của 下.']},
 'characters-10':{prompt:'Trong quán ăn, nói bạn muốn ăn bánh bao. Khung: 我想吃…。 (Tôi muốn ăn…). Hỗ trợ: 想 xiǎng = muốn; 吃 chī = ăn.',hanzi:'我想吃包子。',pinyin:'Wǒ xiǎng chī bāozi.',meaning:'Tôi muốn ăn bánh bao.',criteria:['Viết 包子 với 包, không dùng 句.','Giữ thứ tự 我想吃 rồi đến món ăn.','子 đọc nhẹ trong bāozi.']},
 'characters-11':{prompt:'Nói bạn muốn mua sách. Khung: 我想…书。 (Tôi muốn … sách). Hỗ trợ: 想 xiǎng = muốn; 书 shū = sách.',hanzi:'我想买书。',pinyin:'Wǒ xiǎng mǎi shū.',meaning:'Tôi muốn mua sách.',criteria:['Chọn 买 để nói mua.','卖 là bán, sẽ đổi ý định của câu.','Không thêm phần 十 trên 买.']},
 'characters-12':{prompt:'Nói món đồ bạn muốn mua là quần áo. Khung: 我想买…。 (Tôi muốn mua…).',hanzi:'我想买衣服。',pinyin:'Wǒ xiǎng mǎi yīfu.',meaning:'Tôi muốn mua quần áo.',criteria:['Dùng 衣服 cho quần áo.','Không thay 衣 bằng 农.','服 đọc nhẹ trong yīfu của mẫu này.']},
 'characters-13':{prompt:'Nói bạn đi xe đến trường. Khung: 我…车去学校。 (Tôi đi xe đến trường). Hỗ trợ: 去 qù = đi đến; 学校 xuéxiào = trường học.',hanzi:'我坐车去学校。',pinyin:'Wǒ zuò chē qù xuéxiào.',meaning:'Tôi đi xe đến trường.',criteria:['坐车 nói đi xe; không viết 做车 trong ý này.','Giữ thứ tự phương tiện trước 去学校.','Cùng âm zuò không có nghĩa 坐 và 做 đổi được cho nhau.']},
 'characters-14':{prompt:'Nói bạn có hai quyển sách, đổi số lượng so với mẫu một quyển. Khung: 我有两…书。 Hỗ trợ: 有 yǒu = có; 两 liǎng = hai trước lượng từ.',hanzi:'我有两本书。',pinyin:'Wǒ yǒu liǎng běn shū.',meaning:'Tôi có hai quyển sách.',criteria:['Dùng 本 làm lượng từ cho sách, không dùng 木.','两 đặt trước 本 trong mẫu này.','Giữ 本 ngay trước 书 khi nói số lượng.']},
 'characters-15':{prompt:'Nói bạn đang học viết chữ Hán. Khung: 我学写…。 Hỗ trợ: 学 xué = học; 写 xiě = viết.',hanzi:'我学写汉字。',pinyin:'Wǒ xué xiě Hànzì.',meaning:'Tôi học viết chữ Hán.',criteria:['学 là học, 字 thuộc 汉字 là chữ Hán.','Không chọn chữ chỉ vì cùng phần 子 phía dưới.','Câu chỉ hoạt động học viết, chưa phải tuyên bố đã viết thành thạo.']},
};
