/** Original visual contrasts, not historical etymology or stroke-order claims. */
export const characterFocus=[
 {id:'characters-1',pair:['大','太'],words:['大','太'],note:'大 và 太 khác chấm nhỏ phía dưới. Trong 大学 là 大; 太 là chữ khác. Quan sát hình hiện đại, không suy nghĩa từ chấm.',target:'大',context:'大学',answer:'大',pinyin:'dà',meaning:'chữ 大 trong 大学 — đại học'},
 {id:'characters-2',pair:['见','贝'],words:['再见','贝'],note:'见 và 贝 có phần chân khác nhau. 再见 dùng 见; không thay bằng 贝. Chữ đối chiếu chỉ để nhận diện hình, chưa yêu cầu học nghĩa mới.',target:'见',context:'再见',answer:'见',pinyin:'jiàn',meaning:'chữ 见 trong 再见 — tạm biệt'},
 {id:'characters-3',pair:['妈','吗'],words:['妈妈','吗'],note:'妈 có 女 bên trái, 吗 có 口 bên trái. Cùng nhìn phần bên phải chưa đủ để chọn chữ. 妈妈 chỉ mẹ; 吗 dùng trong câu hỏi.',target:'妈',context:'妈妈',answer:'妈',pinyin:'mā',meaning:'chữ 妈 trong 妈妈 — mẹ'},
 {id:'characters-4',pair:['你','您'],words:['你','您'],note:'您 có phần 心 phía dưới so với 你. Đây là hai hình chữ khác nhau, không phải chỉ đổi giọng khi đọc cùng một chữ.',target:'您',context:'您好',answer:'您',pinyin:'nín',meaning:'chữ 您 trong 您好 — lời chào lịch sự'},
 {id:'characters-5',pair:['他','她','它'],words:['他','她','它'],note:'Ba chữ cùng âm tā nhưng khác hình và đối tượng. 他 có 亻, 她 có 女; 它 là chữ chỉ vật/động vật trong các mẫu đã học.',target:'她',context:'她们',answer:'她',pinyin:'tā',meaning:'chữ 她 trong 她们 — nhóm nữ'},
 {id:'characters-6',pair:['再','在'],words:['再见','在'],note:'再 trong 再见 nói lần gặp sau; 在 dùng trong mẫu vị trí. Cùng âm zài không có nghĩa dùng thay cho nhau.',target:'再',context:'再见',answer:'再',pinyin:'zài',meaning:'chữ 再 trong 再见 — tạm biệt'},
 {id:'characters-7',pair:['白','百'],words:['白天','百'],note:'百 có nét ngang phía trên phần 白. Đọc cả từ: 白天 là ban ngày; 百 là trăm. Đây là ghi nhớ hình chữ, không phải quy tắc đoán nghĩa mọi chữ.',target:'白',context:'白天',answer:'白',pinyin:'bái',meaning:'chữ 白 trong 白天 — ban ngày'},
 {id:'characters-8',pair:['日','目'],words:['日','目'],note:'日 có một nét ngang bên trong khung, 目 có hai. 星期日 dùng 日; không thêm một nét thành 目.',target:'日',context:'星期日',answer:'日',pinyin:'rì',meaning:'chữ 日 trong 星期日 — chủ nhật'},
 {id:'characters-9',pair:['上','下'],words:['上','下'],note:'上 và 下 có vị trí nét ngang dài khác nhau. 下午 là buổi chiều; 上午 là buổi sáng. Thay 下 bằng 上 làm đổi buổi trong ngày.',target:'下',context:'下午',answer:'下',pinyin:'xià',meaning:'chữ 下 trong 下午 — buổi chiều'},
 {id:'characters-10',pair:['包','句'],words:['包子','句'],note:'包 có phần bên trong khác 句. Trong 包子 phải giữ 包; nhìn nét bao bên ngoài không đủ nhận đúng chữ.',target:'包',context:'包子',answer:'包',pinyin:'bāo',meaning:'chữ 包 trong 包子 — bánh bao'},
 {id:'characters-11',pair:['买','卖'],words:['买','卖'],note:'卖 có phần 十 trên đầu so với 买. 买 là mua, 卖 là bán trong tình huống cửa hàng; đừng chỉ dựa âm gần nhau.',target:'买',context:'买东西',answer:'买',pinyin:'mǎi',meaning:'chữ 买 trong 买东西 — mua đồ'},
 {id:'characters-12',pair:['衣','农'],words:['衣服','农'],note:'衣 và 农 có phần đầu và nét bên trong khác nhau. 衣服 dùng 衣. Chữ đối chiếu 农 chỉ để phân biệt hình ở đây, chưa yêu cầu học nghĩa mới.',target:'衣',context:'衣服',answer:'衣',pinyin:'yī',meaning:'chữ 衣 trong 衣服 — quần áo'},
 {id:'characters-13',pair:['坐','做'],words:['坐','做'],note:'坐 và 做 cùng âm zuò. 坐 trong 坐车 là đi xe/ngồi; 做 trong 做饭 là làm/nấu. Chọn theo cả hình và từ.',target:'坐',context:'坐车',answer:'坐',pinyin:'zuò',meaning:'chữ 坐 trong 坐车 — đi xe'},
 {id:'characters-14',pair:['本','木'],words:['本','木'],note:'本 có nét ngang ngắn gần gốc so với 木. 一本书 dùng 本 làm lượng từ; không thay bằng 木.',target:'本',context:'一本书',answer:'本',pinyin:'běn',meaning:'chữ 本 trong 一本书 — một quyển sách'},
 {id:'characters-15',pair:['字','学'],words:['字','学'],note:'字 và 学 cùng có 子 phía dưới nhưng phần trên khác. 汉字 là chữ Hán; 学习 là học. Không chỉ nhìn phần 子 để đoán cả chữ.',target:'字',context:'汉字',answer:'字',pinyin:'zì',meaning:'chữ 字 trong 汉字 — chữ Hán'},
];
