import type {SurvivalManuscript} from './survival-batch-manuscripts';
export const grammarManuscripts:SurvivalManuscript[]=[{
 id:'hsk2-aspect-time-experience-lesson-01',focus:'Tách thói quen, hiện trạng, trải nghiệm và dự định',
 scene:'Lâm thường đi tàu điện ngầm đến lớp. Hôm nay 8:50, lớp bắt đầu 9:00; Lâm đã mua vé, đang đợi bạn ở cửa ga. Bạn có thể đến muộn, chưa chắc. Lâm từng đến ga này nhưng người bạn chưa từng đến.',
 support:'车站 chēzhàn: ga/trạm · 等 děng: đợi · 迟到 chídào: đến muộn · 以前 yǐqián: trước đây. Đọc mốc thời gian trước khi chọn từ.',
 rule:'Không dùng một trợ từ cho mọi loại thông tin. 经常 là tần suất, 正 là đang, 已经 là đã, 过 là trải nghiệm, 可能 là chưa chắc và 就要…了 là sắp. Các trang tiếp theo luyện từng cách dùng cùng phạm vi và ngoại lệ.',
 pitfall:'Thường đi tàu không chứng minh đang trên tàu; đã mua vé không có nghĩa đã đến lớp; có thể muộn không phải chắc chắn muộn.',
 dialogue:[['你经常坐地铁去上课吗？','Nǐ jīngcháng zuò dìtiě qù shàngkè ma?','Bạn thường đi tàu điện ngầm đến lớp không?'],['对。我已经买好票了，现在正等朋友。','Duì. Wǒ yǐjīng mǎihǎo piào le, xiànzài zhèng děng péngyou.','Đúng. Tôi đã mua vé xong, giờ đang đợi bạn.'],['还有十分钟就要上课了，他在哪儿？','Hái yǒu shí fēnzhōng jiùyào shàngkè le, tā zài nǎr?','Còn mười phút vào lớp, bạn ấy ở đâu?'],['他还没到，今天可能迟到。','Tā hái méi dào, jīntiān kěnéng chídào.','Bạn ấy chưa tới, hôm nay có thể đến muộn.'],['他来过这个车站吗？','Tā láiguo zhè ge chēzhàn ma?','Bạn ấy từng đến ga này chưa?'],['没有。我来过，他没来过。','Méiyǒu. Wǒ láiguo, tā méi láiguo.','Chưa. Tôi từng đến, bạn ấy chưa từng đến.']],
 question:'Theo cảnh lúc 8:50, kết luận nào đúng?',choices:[['他已经到教室了。','Mua vé xong không chứng minh đã tới lớp; Lâm đang ở cửa ga.'],['他正在等朋友，朋友可能迟到。','Đúng: hành động hiện tại và khả năng chưa chắc được giữ riêng.'],['他的朋友经常来这个车站。','Bạn chưa từng đến ga này, không phải thường đến.']],answer:1,
 transfer:'Đổi cảnh: 13:40 tại cửa thư viện, hẹn đọc sách 14:00. Bạn đã mượn sách, đang đợi chị; chị chưa tới, có thể đang trên xe buýt. Bạn thường đọc cuối tuần; chị chưa từng đến thư viện này. Viết bốn câu giữ đúng trạng thái, thời gian và mức chắc chắn.',
 model:['我已经借好书了，现在正等姐姐。还有二十分钟就要开始看书了。姐姐还没到，可能在公交车上。我经常周末看书，姐姐没来过这个图书馆。','Wǒ yǐjīng jièhǎo shū le, xiànzài zhèng děng jiějie. Hái yǒu èrshí fēnzhōng jiùyào kāishǐ kàn shū le. Jiějie hái méi dào, kěnéng zài gōngjiāochē shàng. Wǒ jīngcháng zhōumò kàn shū, jiějie méi láiguo zhè ge túshūguǎn.','Đã mượn sách, đang đợi chị; còn 20 phút đọc sách. Chị chưa tới, có thể trên xe buýt. Thường đọc cuối tuần; chị chưa từng đến thư viện này.'],criteria:['Giữ 20 phút còn lại, không dùng 10 phút.','Tách đã mượn với đang đợi.','Không bỏ 可能 khi đoán vị trí chị.','Giữ thói quen của mình và trải nghiệm của chị riêng.']
},{
 id:'hsk2-aspect-time-experience-lesson-02',focus:'Mô tả trạng thái và thời lượng, không suy năng lực từ trải nghiệm',
 scene:'Tại câu lạc bộ, cửa đang mở, ba giáo viên đứng ở cửa. Mai vừa kể đã học hai năm, chạy không nhanh và từng ăn sủi cảo một lần. Một bạn nghe nhạc trong khi viết chữ. Những thông tin này không tự thành điểm năng lực.',
 support:'俱乐部 jùlèbù: câu lạc bộ · 一次 yí cì: một lần · 同时 tóngshí: đồng thời · 小时 xiǎoshí: tiếng đồng hồ.',
 rule:'着 giữ trạng thái hoặc hành động làm nền; 得 nối cách thực hiện; thời lượng trả lời bao lâu, không phải lúc mấy giờ. 过 chỉ trải nghiệm từng có, không chứng minh tần suất hay giỏi. Đọc mẫu theo từng điểm ở các trang sau.',
 pitfall:'Học hai năm không tự bằng nói tốt; đã ăn sủi cảo không có nghĩa thường ăn hoặc thích ăn.',
 dialogue:[['门口站着几位老师？','Ménkǒu zhànzhe jǐ wèi lǎoshī?','Có mấy giáo viên đứng ở cửa?'],['三位。门开着，我们进去吧。','Sān wèi. Mén kāizhe, wǒmen jìnqù ba.','Ba người. Cửa đang mở, chúng ta vào nhé.'],['你学了多长时间汉语？','Nǐ xué le duō cháng shíjiān Hànyǔ?','Bạn đã học tiếng Trung bao lâu?'],['两年了，但是还有很多不懂的地方。','Liǎng nián le, dànshì hái yǒu hěn duō bù dǒng de dìfang.','Hai năm rồi nhưng vẫn còn nhiều chỗ chưa hiểu.'],['你吃过饺子吗？经常吃吗？','Nǐ chīguo jiǎozi ma? Jīngcháng chī ma?','Bạn từng ăn sủi cảo chưa? Có thường ăn không?'],['吃过一次，不经常吃。','Chīguo yí cì, bù jīngcháng chī.','Đã ăn một lần, không thường ăn.']],
 question:'Kết luận nào chỉ dựa vào thông tin đã có?',choices:[['她学了两年，所以汉语一定说得很好。','Thời lượng không chứng minh năng lực; người nói còn chỗ chưa hiểu.'],['她经常吃饺子。','Một lần không phải thường xuyên.'],['门开着，门口站着三位老师。','Đúng: trạng thái cửa và ba giáo viên được nêu rõ.']],answer:2,
 transfer:'Cảnh mới: cửa đóng, hai học sinh đứng ở cửa; bạn đã học sáu tháng, hôm qua luyện một tiếng; từng ăn sủi cảo hai lần, không thường ăn. Viết bốn câu; không kết luận trình độ từ thời lượng.',
 model:['门关着，门口站着两个学生。我学了六个月汉语。昨天我练习了一个小时。我吃过两次饺子，但是不经常吃。','Mén guānzhe, ménkǒu zhànzhe liǎng ge xuésheng. Wǒ xué le liù ge yuè Hànyǔ. Zuótiān wǒ liànxí le yí ge xiǎoshí. Wǒ chīguo liǎng cì jiǎozi, dànshì bù jīngcháng chī.','Cửa đóng, hai học sinh đứng ở cửa; đã học sáu tháng, hôm qua luyện một tiếng; từng ăn hai lần nhưng không thường ăn.'],criteria:['Đổi trạng thái cửa sang đóng và số người sang hai.','Sáu tháng khác một tiếng luyện hôm qua.','Hai lần trải nghiệm không thành thường xuyên.','Không tự khẳng định trình độ.']
},{
 id:'hsk2-clause-linking-lesson-01',focus:'Nối lời kể theo nguyên nhân, chuyển ý và chi tiết cần nhấn',
 scene:'Mưa làm nhóm không ra ngoài. Tuy mệt, An vẫn đọc sách, rồi dự định ăn xong mới về. An bắt đầu học tiếng Trung năm ngoái tại Hà Nội; câu hỏi nhắm vào thời điểm đã bắt đầu, không hỏi đã từng học chưa.',
 support:'河内 Hénèi: Hà Nội · 出去 chūqù: ra ngoài · 原因 yuányīn: nguyên nhân · 先后 xiānhòu: thứ tự trước sau.',
 rule:'因为 nêu lý do; 虽然…但是… nối điều trái kỳ vọng; 再 nói hành động tiếp theo; 跟 nối danh từ theo mẫu; 是…的 nhấn chi tiết của sự việc đã biết. Không thay từ nối chỉ vì dịch tiếng Việt gần giống.',
 pitfall:'“Vì mệt nên vẫn đọc” đổi quan hệ nhượng bộ; “vì không ra ngoài nên mưa” đảo nguyên nhân.',
 dialogue:[['你们为什么没出去？','Nǐmen wèishénme méi chūqù?','Vì sao các bạn không ra ngoài?'],['因为下雨，我们就在这里看书。','Yīnwèi xiàyǔ, wǒmen jiù zài zhèlǐ kàn shū.','Vì mưa nên chúng tôi đọc sách ở đây.'],['你不累吗？什么时候回家？','Nǐ bú lèi ma? Shénme shíhou huí jiā?','Bạn không mệt à? Khi nào về nhà?'],['虽然累，但是我还想看一会儿。吃完饭再走。','Suīrán lèi, dànshì wǒ hái xiǎng kàn yíhuìr. Chīwán fàn zài zǒu.','Tuy mệt nhưng tôi muốn đọc thêm chút. Ăn xong rồi đi.'],['你是什么时候开始学汉语的？','Nǐ shì shénme shíhou kāishǐ xué Hànyǔ de?','Bạn bắt đầu học tiếng Trung khi nào?'],['我是去年在河内开始学的。','Wǒ shì qùnián zài Hénèi kāishǐ xué de.','Tôi bắt đầu học năm ngoái ở Hà Nội.']],
 question:'Câu nào giữ đúng quan hệ của lời kể?',choices:[['因为下雨，所以没出去；虽然累，但是还想看书。','Đúng: mưa là lý do, mệt mà vẫn đọc là nhượng bộ.'],['因为没出去，所以下雨。','Đảo chiều nguyên nhân.'],['他已经吃完饭回家了。','Ăn xong rồi về là dự định, chưa nói đã thực hiện.']],answer:0,
 transfer:'Đổi cảnh: vì xe hỏng nên bạn đi bộ; tuy xa nhưng vẫn muốn đi; đến nơi rồi mới gọi điện. Bạn bắt đầu học năm kia ở Thành Đô. Viết bốn câu nối đúng quan hệ và nhấn thời điểm học.',
 model:['因为车坏了，所以我走路去。虽然很远，但是我还是想去。到了以后再打电话。我是前年在成都开始学汉语的。','Yīnwèi chē huài le, suǒyǐ wǒ zǒulù qù. Suīrán hěn yuǎn, dànshì wǒ háishi xiǎng qù. Dào le yǐhòu zài dǎ diànhuà. Wǒ shì qiánnián zài Chéngdū kāishǐ xué Hànyǔ de.','Xe hỏng nên đi bộ; tuy xa vẫn muốn đi; tới rồi mới gọi; bắt đầu học năm kia ở Thành Đô.'],criteria:['Không đảo lý do xe hỏng.','Giữ quan hệ tuy xa vẫn muốn đi.','Gọi sau khi tới, không nói đã gọi.','Nhấn năm kia tại Thành Đô bằng 是…的.']
},{
 id:'hsk2-clause-linking-lesson-02',focus:'Chọn quan hệ giữa hai vế trước khi nối câu',
 scene:'Ngày mai thi nên tối nay Lan cần học. Bạn hỏi học ở nhà hay thư viện; Lan chọn ở nhà. Tuy mệt Lan vẫn ôn. Lan dự định về tới nhà là mở sách ngay.',
 support:'复习 fùxí: ôn bài · 选择 xuǎnzé: lựa chọn · 马上 mǎshàng: ngay · 一…就… yī…jiù…: vừa…là…',
 rule:'还是 đặt hai lựa chọn trong câu hỏi; 虽然…但是… nối nhượng bộ; 因为…所以… nối lý do/hệ quả; 一…就… nối hai việc xảy ra liền nhau. Dùng ngữ cảnh để biết đó là thói quen, dự định hay sự việc đã xảy ra.',
 pitfall:'一到家就看书 không tự có nghĩa đã về nhà. Học vì ngày mai thi, không phải kỳ thi xuất hiện vì tối nay học.',
 dialogue:[['你今晚去图书馆，还是在家学习？','Nǐ jīnwǎn qù túshūguǎn, háishi zài jiā xuéxí?','Tối nay bạn đến thư viện hay học ở nhà?'],['在家。因为明天考试，所以今晚要复习。','Zài jiā. Yīnwèi míngtiān kǎoshì, suǒyǐ jīnwǎn yào fùxí.','Ở nhà. Vì mai thi nên tối nay cần ôn.'],['你今天累吗？','Nǐ jīntiān lèi ma?','Hôm nay bạn mệt không?'],['虽然累，但是我还是要复习。','Suīrán lèi, dànshì wǒ háishi yào fùxí.','Tuy mệt nhưng tôi vẫn cần ôn.'],['准备什么时候开始？','Zhǔnbèi shénme shíhou kāishǐ?','Bạn định bắt đầu khi nào?'],['我一到家就看书。','Wǒ yí dào jiā jiù kàn shū.','Tôi về tới nhà là đọc sách ngay.']],
 question:'Câu nào phản ánh đúng quyết định của Lan?',choices:[['她已经在图书馆复习了。','Lan chọn nhà và nói dự định, chưa nói đã ôn tại thư viện.'],['因为明天考试，她今晚在家复习。','Đúng: giữ lý do, thời gian và nơi được chọn.'],['因为今晚学习，所以明天才有考试。','Đã đảo quan hệ nhân quả.']],answer:1,
 transfer:'Ngày mai đi du lịch nên tối nay chuẩn bị hành lý. Tuy bận vẫn chuẩn bị; chọn ở nhà thay vì công ty; về tới nhà là lấy vé ngay. Viết một câu hỏi lựa chọn và ba câu trả lời nối quan hệ đúng.',
 model:['你在公司准备，还是回家准备？因为明天去旅行，所以我今晚在家准备。虽然很忙，但是我还是要准备。我一到家就拿机票。','Nǐ zài gōngsī zhǔnbèi, háishi huí jiā zhǔnbèi? Yīnwèi míngtiān qù lǚxíng, suǒyǐ wǒ jīnwǎn zài jiā zhǔnbèi. Suīrán hěn máng, dànshì wǒ háishi yào zhǔnbèi. Wǒ yí dào jiā jiù ná jīpiào.','Chuẩn bị tại công ty hay về nhà? Vì mai du lịch nên tối nay chuẩn bị ở nhà; tuy bận vẫn chuẩn bị; về tới nhà lấy vé ngay.'],criteria:['Có câu hỏi lựa chọn với 还是.','Du lịch là lý do chuẩn bị, không đảo lại.','Giữ tuy bận vẫn chuẩn bị.','一…就… nói lấy vé ngay khi về, không bịa đã về.']
},{
 id:'hsk2-complements-and-motion-lesson-01',focus:'Theo dõi đường đi, người thực hiện và kết quả',
 scene:'Người nói là giáo viên đang trong lớp. Nam từ cửa đi vào phía giáo viên. Giáo viên mời Nam đọc câu số ba. Nam đọc xong nhưng chưa hiểu; sau đó đi thư viện để tìm sách. Hướng phải được tính theo hướng Nam đang đi.',
 support:'第三题 dì sān tí: câu bài tập số ba · 读 dú: đọc thành tiếng · 找 zhǎo: tìm · 走廊 zǒuláng: hành lang.',
 rule:'从 nêu lối/điểm xuất phát, 往 nêu hướng. 完 là xong, 懂 là hiểu. 去图书馆找书 có cùng chủ thể đi và tìm; 老师请我读 có giáo viên mời nhưng tôi đọc. Mỗi cụm động từ cần xác định đúng người làm.',
 pitfall:'Đọc xong không chứng minh đã hiểu; người mời đọc không nhất thiết là người thực hiện việc đọc.',
 dialogue:[['老师，我可以进来吗？','Lǎoshī, wǒ kěyǐ jìnlái ma?','Thầy/cô, em vào được không?'],['请进来。请你读第三题。','Qǐng jìnlái. Qǐng nǐ dú dì sān tí.','Mời vào. Em hãy đọc câu số ba.'],['我读完了，但是没看懂。','Wǒ dúwán le, dànshì méi kàndǒng.','Em đọc xong nhưng chưa hiểu.'],['先看看这本书，再告诉我哪里不懂。','Xiān kànkan zhè běn shū, zài gàosu wǒ nǎlǐ bù dǒng.','Xem quyển sách này trước rồi nói chỗ nào chưa hiểu.'],['我想去图书馆找书，怎么走？','Wǒ xiǎng qù túshūguǎn zhǎo shū, zěnme zǒu?','Em muốn đến thư viện tìm sách, đi thế nào?'],['从教室出去，往右走。','Cóng jiàoshì chūqù, wǎng yòu zǒu.','Ra khỏi lớp rồi đi về phía phải.']],
 question:'Theo cảnh, ai đọc và kết quả đọc thế nào?',choices:[['老师读完了，所以南懂了。','Giáo viên yêu cầu, Nam đọc; chưa có kết quả hiểu.'],['南没有读完。','Nam nói đã đọc xong.'],['南读完了，但是还没看懂。','Đúng: giữ người thực hiện và tách xong với hiểu.']],answer:2,
 transfer:'Cảnh mới: giáo viên trong thư viện, Lan đi vào từ cửa. Giáo viên mời Lan đọc câu hai; Lan đọc xong và hiểu rồi. Lan ra khỏi thư viện, đi trái đến lớp để học. Viết bốn câu, giữ ai làm gì và kết quả khác mẫu.',
 model:['兰从门口走进来了。老师请她读第二题。她读完了，也看懂了。她从图书馆出去，往左走，去教室学习。','Lán cóng ménkǒu zǒu jìnlái le. Lǎoshī qǐng tā dú dì èr tí. Tā dúwán le, yě kàndǒng le. Tā cóng túshūguǎn chūqù, wǎng zuǒ zǒu, qù jiàoshì xuéxí.','Lan đi vào từ cửa; giáo viên mời đọc câu hai; đã đọc xong và hiểu; ra thư viện, đi trái đến lớp học.'],criteria:['Giáo viên mời, Lan đọc câu hai.','Giữ đã hiểu, không chép chưa hiểu của mẫu.','Hướng trái, không phải phải.','Đi lớp để học, cùng chủ thể Lan.']
},{
 id:'hsk2-complements-and-motion-lesson-02',focus:'Giữ điểm nhìn và vai người cho, người nhận, người làm',
 scene:'An đứng ngoài lớp và nói chuyện với Bình ở trong lớp. An gọi Bình chạy ra phía mình. Bình tặng An một sách. Sau đó giáo viên đứng trong lớp gọi cả hai vào; vì đổi người nói nên hướng về phía giáo viên là 进来.',
 support:'外面 wàimiàn: bên ngoài · 里面 lǐmiàn: bên trong · 送给 sònggěi: tặng cho · 说话的人 shuōhuà de rén: người nói.',
 rule:'出/进 nói ra/vào, 来/去 nói về/xa điểm nhìn. Đổi người nói cần xác định lại vị trí. 请/让 + người + hành động: người đó làm hành động sau. 送给 + người nhận + vật: không đổi người nhận thành người tặng.',
 pitfall:'Cùng một lần đi vào lớp, người ngoài nói 进去 còn giáo viên trong nói 进来. Không giữ 来 chỉ vì đã dùng ở câu trước.',
 dialogue:[['平，我在教室外面，你出来一下吧。','Píng, wǒ zài jiàoshì wàimiàn, nǐ chūlái yíxià ba.','Bình, tôi ở ngoài lớp, bạn ra đây chút nhé.'],['好，我出来了。这本书送给你。','Hǎo, wǒ chūlái le. Zhè běn shū sònggěi nǐ.','Được, tôi ra rồi. Tặng bạn quyển sách này.'],['谢谢！老师在教室里叫我们。','Xièxie! Lǎoshī zài jiàoshì lǐ jiào wǒmen.','Cảm ơn! Giáo viên đang gọi chúng ta trong lớp.'],['你们进来吧！','Nǐmen jìnlái ba!','Các em vào đây nhé!'],['老师让我们进去，我们走吧。','Lǎoshī ràng wǒmen jìnqù, wǒmen zǒu ba.','Giáo viên bảo chúng ta vào trong, đi thôi.'],['好，我跟你一起进去。','Hǎo, wǒ gēn nǐ yìqǐ jìnqù.','Được, tôi cùng bạn vào trong.']],
 question:'Giáo viên đang ở trong lớp nói với hai bạn ở ngoài. Chọn lời gọi phù hợp điểm nhìn.',choices:[['你们进来吧！','Đúng: đi vào và về phía giáo viên trong lớp.'],['你们出去吧！','Đổi thành đi ra xa giáo viên, sai hướng yêu cầu.'],['你们出来吧！','Ra ngoài không đúng việc vào lớp.']],answer:0,
 transfer:'Đổi vị trí: Mai ở trong phòng, Long ở ngoài. Mai nhờ Long mang sách vào phía mình. Long tặng sách cho Mai. Sau đó Mai bảo Long ra ngoài lấy bút; từ vị trí Mai, Long đi ra xa. Viết bốn câu có mốc, lời nhờ, người nhận và hướng ra.',
 model:['梅在房间里，龙在外面。梅请龙拿着书进来。龙送给梅一本书。梅让龙出去拿笔。','Méi zài fángjiān lǐ, Lóng zài wàimiàn. Méi qǐng Lóng názhe shū jìnlái. Lóng sònggěi Méi yì běn shū. Méi ràng Lóng chūqù ná bǐ.','Mai trong phòng, Long ngoài; Mai nhờ Long cầm sách vào; Long tặng Mai một sách; Mai bảo Long ra ngoài lấy bút.'],criteria:['Mai trong, Long ngoài là điểm nhìn mới.','Vào phía Mai dùng 进来.','Long tặng, Mai nhận, sách là vật.','Ra xa Mai dùng 出去; Long lấy bút.']
}];
