/** Keyed by vocabulary identity, never by Hanzi: 过 has two distinct entries. */
export const grammarWordExamples:Record<string,[string,string,string]>={
 'hsk-vocab-00304':['我们班有二十个学生。','Wǒmen bān yǒu èrshí ge xuésheng.','Lớp chúng tôi có hai mươi học sinh.'],
 'hsk-vocab-00314':['这条裤子有点儿长。','Zhè tiáo kùzi yǒudiǎnr cháng.','Chiếc quần này hơi dài.'],
 'hsk-vocab-00321':['床上放着一本书。','Chuáng shàng fàngzhe yì běn shū.','Trên giường có đặt một quyển sách.'],
 'hsk-vocab-00327':['我们周末一起打球。','Wǒmen zhōumò yìqǐ dǎqiú.','Cuối tuần chúng tôi cùng chơi bóng.'],
 'hsk-vocab-00330':['我很累，但还要工作。','Wǒ hěn lèi, dàn hái yào gōngzuò.','Tôi mệt nhưng vẫn phải làm việc.'],
 'hsk-vocab-00336':['我想点两个菜。','Wǒ xiǎng diǎn liǎng ge cài.','Tôi muốn gọi hai món ăn.'],
 'hsk-vocab-00347':['过马路时要小心。','Guò mǎlù shí yào xiǎoxīn.','Khi qua đường cần cẩn thận.'],
 'hsk-vocab-00351':['我没去过北京。','Wǒ méi qùguo Běijīng.','Tôi chưa từng đến Bắc Kinh.'],
 'hsk-vocab-00366':['这里有三间教室。','Zhèlǐ yǒu sān jiān jiàoshì.','Ở đây có ba phòng học.'],
 'hsk-vocab-00367':['老师教我们写汉字。','Lǎoshī jiāo wǒmen xiě Hànzì.','Giáo viên dạy chúng tôi viết chữ Hán.'],
 'hsk-vocab-00374':['我经常去图书馆。','Wǒ jīngcháng qù túshūguǎn.','Tôi thường đến thư viện.'],
 'hsk-vocab-00380':['我们明天考汉语。','Wǒmen míngtiān kǎo Hànyǔ.','Ngày mai chúng tôi thi tiếng Trung.'],
 'hsk-vocab-00381':['考试九点开始。','Kǎoshì jiǔ diǎn kāishǐ.','Bài thi bắt đầu lúc chín giờ.'],
 'hsk-vocab-00400':['门开着。','Mén kāizhe.','Cửa đang để mở.'],
 'hsk-vocab-00401':['老师站在门口。','Lǎoshī zhàn zài ménkǒu.','Giáo viên đứng ở cửa ra vào.'],
 'hsk-vocab-00404':['她在比赛中得了第一名。','Tā zài bǐsài zhōng dé le dì yī míng.','Cô ấy đạt hạng nhất trong cuộc thi.'],
 'hsk-vocab-00414':['他每天早上跑步。','Tā měitiān zǎoshang pǎobù.','Anh ấy chạy bộ mỗi sáng.'],
 'hsk-vocab-00421':['这个球是红色的。','Zhè ge qiú shì hóngsè de.','Quả bóng này màu đỏ.'],
 'hsk-vocab-00431':['上课时别说话。','Shàngkè shí bié shuōhuà.','Trong giờ học đừng nói chuyện.'],
 'hsk-vocab-00439':['因为下雨，所以我们没出去。','Yīnwèi xiàyǔ, suǒyǐ wǒmen méi chūqù.','Vì trời mưa nên chúng tôi không ra ngoài.'],
 'hsk-vocab-00442':['这道题我做错了。','Zhè dào tí wǒ zuòcuò le.','Tôi đã làm sai câu bài tập này.'],
 'hsk-vocab-00461':['门口站着一个小孩儿。','Ménkǒu zhànzhe yí ge xiǎoháir.','Có một đứa trẻ đang đứng ở cửa.'],
 'hsk-vocab-00473':['我们一起去学校。','Wǒmen yìqǐ qù xuéxiào.','Chúng tôi cùng đến trường.'],
 'hsk-vocab-00481':['请往右走。','Qǐng wǎng yòu zǒu.','Xin đi về phía phải.'],
 'hsk-vocab-00486':['老师站在门口。','Lǎoshī zhàn zài ménkǒu.','Giáo viên đứng ở cửa.'],
 'hsk-vocab-00490':['她拿着一本书。','Tā názhe yì běn shū.','Cô ấy đang cầm một quyển sách.'],
 'hsk-vocab-00492':['我们每周上两次课。','Wǒmen měi zhōu shàng liǎng cì kè.','Chúng tôi học hai buổi mỗi tuần.'],
};
