import type { SurvivalManuscript } from './survival-batch-manuscripts';
import type { BatchPractice } from './build-authored-batch';
export const manuscripts:SurvivalManuscript[]=[
 {id:'hsk2-guided-message-lesson-01',focus:'Tin nhắn giúp người nhận biết phải làm gì',scene:'Bạn hẹn đá bóng với Tiểu Lý hôm nay nhưng đang đau đầu. Viết đúng ba câu: báo tình trạng, hủy buổi đá bóng hôm nay và nhờ báo cho Tiểu Vương. Không tự hứa ngày đá bù khi chưa thống nhất.',support:'小李 Xiǎo Lǐ — Tiểu Lý; 小王 Xiǎo Wáng — Tiểu Vương; 头疼 tóu téng — đau đầu; 踢足球 tī zúqiú — đá bóng; 告诉 gàosu — báo cho; 今天 jīntiān — hôm nay.',rule:'Một tin nhắn đủ dùng cần người nhận hiểu việc gì thay đổi và cần làm gì tiếp. 头疼 nêu tình trạng; 今天不能去… nói không thể tham gia hôm nay; 请你告诉… nhờ truyền tin. 因为 + lý do, 所以 + kết quả nối quan hệ nhân quả. 虽然…但是… diễn đạt nhượng bộ, không thay cho mọi quan hệ nguyên nhân.',pitfall:'Chỉ viết 我头疼 không nói rõ buổi hẹn có bị hủy hay không. Không tự thêm 已经告诉… nếu chưa báo. Ba câu là giới hạn luyện tập của bài, không phải mọi tin nhắn đều bắt buộc ba câu.',dialogue:[['小李，我今天头疼。','Xiǎo Lǐ, wǒ jīntiān tóu téng.','Tiểu Lý, hôm nay tôi đau đầu.'],['今天不能去踢足球了。','Jīntiān bù néng qù tī zúqiú le.','Hôm nay tôi không thể đi đá bóng nữa.'],['请你告诉小王，谢谢。','Qǐng nǐ gàosu Xiǎo Wáng, xièxie.','Nhờ bạn báo cho Tiểu Vương, cảm ơn.']],question:'Bạn chưa báo Tiểu Vương và muốn nhờ Tiểu Lý báo. Câu cuối nào đúng việc cần làm?',choices:[['请你告诉小王。','Đúng: nhờ người nhận báo giúp.'],['我已经告诉小王了。','Câu này nói đã báo, trái dữ kiện.'],['小王今天头疼。','Đổi người bị đau đầu, chưa nhờ báo.']],answer:0,transfer:'Đổi vai: nhắn Tiểu Vương rằng hôm nay tay bạn đau, không đi khiêu vũ được và nhờ báo Tiểu Lý. Viết ba câu; không tự thêm chẩn đoán hay ngày hẹn mới.',model:['小王，我今天手疼。今天不能去跳舞了。请你告诉小李，谢谢。','Xiǎo Wáng, wǒ jīntiān shǒu téng. Jīntiān bù néng qù tiàowǔ le. Qǐng nǐ gàosu Xiǎo Lǐ, xièxie.','Tiểu Vương, hôm nay tôi đau tay. Hôm nay tôi không thể đi khiêu vũ nữa. Nhờ bạn báo Tiểu Lý, cảm ơn.'],criteria:['Đúng người nhận Tiểu Vương, người cần báo Tiểu Lý.','Có đau tay, hôm nay và không đi khiêu vũ.','Yêu cầu báo giúp rõ, ba câu, không bịa việc đã hoàn tất.']},
 {id:'hsk2-guided-message-lesson-02',focus:'Yêu cầu rõ đồ vật và sửa thông tin cũ',scene:'Bạn quên túi màu đỏ trong phòng học, trên ghế bên phải cửa. Nhờ Tiểu Lý mang đến cửa ga lúc 5 giờ chiều. Sau đó bạn nhớ ra túi ở ghế bên trái: phải gửi cập nhật rõ để người nhận không tìm theo tin cũ.',support:'包 bāo — túi; 红色 hóngsè — màu đỏ; 椅子 yǐzi — ghế; 门口 ménkǒu — cửa; 拿来 nálái — mang đến; 下午五点 xiàwǔ wǔ diǎn — 5 giờ chiều; 左边 zuǒbian — bên trái.',rule:'Yêu cầu cần nêu vật nào, ở đâu và mang đến đâu/khi nào. 我忘了拿… nói quên lấy; 请帮我… nhờ giúp. Cập nhật bằng 不好意思，我说错了… rồi nêu thông tin mới. 已经…了 chỉ dùng khi việc thật sự hoàn tất. Không bắt người nhận tự suy ra chỗ mới từ một lời xin lỗi.',pitfall:'希望你能帮我 nói mong được giúp nhưng thiếu vật/nơi nên chưa đủ. Khi vị trí đổi, nhắc cả vị trí đúng và phủ định vị trí cũ sẽ giảm nhầm. 不在… không phải 没在… khi sửa vị trí hiện tại trong mẫu này.',dialogue:[['我忘了拿红色的包。包在教室门口右边的椅子上。','Wǒ wàng le ná hóngsè de bāo. Bāo zài jiàoshì ménkǒu yòubian de yǐzi shàng.','Tôi quên lấy túi đỏ. Túi ở trên ghế bên phải cửa phòng học.'],['请你下午五点把包带到车站门口。','Qǐng nǐ xiàwǔ wǔ diǎn bǎ bāo dài dào chēzhàn ménkǒu.','Nhờ bạn mang túi đến cửa ga lúc 5 giờ chiều.'],['不好意思，我说错了：包在左边的椅子上，不在右边。','Bù hǎoyìsi, wǒ shuō cuò le: bāo zài zuǒbian de yǐzi shàng, bú zài yòubian.','Xin lỗi, tôi nói nhầm: túi ở ghế bên trái, không phải bên phải.']],question:'Sau tin sửa, Tiểu Lý phải tìm túi ở đâu?',choices:[['教室门口右边的椅子上。','Đây là thông tin đã được sửa, không dùng nữa.'],['教室门口左边的椅子上。','Đúng: tin cuối sửa phải thành trái.'],['车站门口左边的椅子上。','Cửa ga là nơi giao túi, không phải nơi quên túi.']],answer:1,transfer:'Nhắn ba câu: bạn quên sách màu xanh ở bàn cạnh cửa phòng học; nhờ mang đến cửa trường lúc 4 giờ chiều. Sau đó viết riêng một câu cập nhật giờ thành 4:30, giữ nguyên nơi và đồ vật.',model:['我忘了拿蓝色的书。书在教室门口的桌子上。请你下午四点把书带到学校门口。不好意思，时间改成下午四点半，不是四点。','Wǒ wàng le ná lánsè de shū. Shū zài jiàoshì ménkǒu de zhuōzi shàng. Qǐng nǐ xiàwǔ sì diǎn bǎ shū dài dào xuéxiào ménkǒu. Bù hǎoyìsi, shíjiān gǎi chéng xiàwǔ sì diǎn bàn, bú shì sì diǎn.','Tôi quên lấy sách xanh. Sách ở trên bàn cạnh cửa phòng học. Nhờ bạn mang sách đến cửa trường lúc 4 giờ chiều. Xin lỗi, đổi giờ thành 4:30 chiều, không phải 4 giờ.'],criteria:['Ba câu ban đầu đủ sách xanh, bàn cạnh cửa phòng học, cửa trường, 4 giờ chiều.','Câu cập nhật sửa 4 giờ thành 4:30; không đổi vật hoặc nơi.','Người nhận biết phải mang gì và hẹn theo thời gian mới.']},
 {id:'hsk2-picture-description-lesson-01',focus:'Mô tả điều thấy được, không đoán quan hệ',scene:'Quan sát toàn tranh: một người cao tuổi ngồi bên trái, chiếc ô khép cạnh ghế và hồ cá bên phải. Tranh không cho biết người đó là ông của ai, có bệnh hay không hoặc vừa đi du lịch về.',support:'老人 lǎorén — người cao tuổi; 坐 zuò — ngồi; 旁边 pángbiān — bên cạnh; 伞 sǎn — ô; 池子 chízi — hồ nhỏ; 里面 lǐmiàn — bên trong. Trái/phải tính theo phía người xem tranh.',rule:'Dùng 有 để giới thiệu vật/người có trong tranh; 在 + nơi để định vị; 坐在… mô tả vị trí ngồi. Chọn người → vị trí → vật liên quan để nối ba câu. 眼睛、药、爷爷 là từ học trong bài nhưng không được gán cho tranh nếu không nhìn thấy hay chưa có dữ kiện. 爷爷 là quan hệ với một người cụ thể, không đồng nghĩa mọi người đàn ông cao tuổi.',pitfall:'Không nhìn thấy người bơi trong tranh nên không viết 有人在游泳. Không khẳng định đã uống thuốc, đã đi du lịch hay là ông của tôi chỉ từ ngoại hình. Câu ví dụ từ điển không phải dữ kiện của tranh.',dialogue:[['左边有一位老人。','Zuǒbian yǒu yí wèi lǎorén.','Bên trái có một người cao tuổi.'],['他坐在椅子上，旁边有一把伞。','Tā zuò zài yǐzi shàng, pángbiān yǒu yì bǎ sǎn.','Ông ấy ngồi trên ghế, cạnh đó có một chiếc ô.'],['右边有一个池子，里面有鱼。','Yòubian yǒu yí ge chízi, lǐmiàn yǒu yú.','Bên phải có một hồ nhỏ, bên trong có cá.']],question:'Câu nào có căn cứ từ tranh?',choices:[['我的爷爷已经吃药了。','Tranh không cho biết quan hệ hay việc uống thuốc.'],['右边的池子里有鱼。','Đúng: nhìn thấy hồ bên phải và cá trong hồ.'],['有一个人在游泳。','Không có người bơi trong tranh.']],answer:1,transfer:'Dữ kiện bổ sung bằng chữ, không phải tranh mới: người cao tuổi chuyển sang đứng bên phải hồ, chiếc ô vẫn cạnh ghế. Viết ba câu: người ở đâu, ô ở đâu và cá ở đâu. Giữ ranh giới giữa tranh ban đầu và tình huống đổi này.',model:['老人站在池子的右边。伞还在椅子旁边。池子里有鱼。','Lǎorén zhàn zài chízi de yòubian. Sǎn hái zài yǐzi pángbiān. Chízi lǐ yǒu yú.','Người cao tuổi đứng bên phải hồ. Ô vẫn cạnh ghế. Trong hồ có cá.'],criteria:['Đúng dữ kiện mới: đứng bên phải hồ, không còn ngồi bên trái.','Ô vẫn cạnh ghế; cá trong hồ.','Không bịa quan hệ gia đình, sức khỏe hoặc việc đã xảy ra.']},
 {id:'hsk2-picture-description-lesson-02',focus:'Tách hành động nhìn thấy khỏi nguyên nhân chưa biết',scene:'Quan sát người phụ nữ cầm ô đi về cửa ga bên trái trong mưa. Có thể nói hướng đi, quần áo và thời tiết. Không có đồng hồ hay thông báo chuyến tàu: chưa biết cô ấy có muộn hay vì sao đến ga.',support:'下雨 xià yǔ — mưa; 拿着 ná zhe — đang cầm; 伞 sǎn — ô; 穿着 chuān zhe — đang mặc; 外套 wàitào — áo khoác; 往 wǎng — về phía; 绿 lǜ — xanh lá; 门口 ménkǒu — cửa.',rule:'正/正在 + động từ diễn tả việc đang diễn ra; 动词 + 着 diễn tả trạng thái duy trì: 拿着伞、穿着外套. 往 + hướng/nơi + 走 nêu hướng đi, chưa có nghĩa đã đến. 因为…所以… cần quan hệ nguyên nhân có căn cứ. Mưa và đi đến ga cùng xuất hiện chưa chứng minh cô ấy đến ga vì mưa.',pitfall:'着 trong 拿着 đọc nhẹ zhe, khác zháo trong 着急. Không đổi 走 thành 跑 khi nhân vật đang đi bộ. Không kết luận chồng đang chờ, cô ấy muộn hay chuẩn bị đi du lịch nếu chưa có dữ kiện.',dialogue:[['外面正在下雨。','Wàimian zhèngzài xià yǔ.','Bên ngoài đang mưa.'],['她穿着绿色的外套，拿着一把伞。','Tā chuān zhe lǜsè de wàitào, ná zhe yì bǎ sǎn.','Cô ấy mặc áo khoác xanh lá, cầm một chiếc ô.'],['她正往左边的车站门口走。','Tā zhèng wǎng zuǒbian de chēzhàn ménkǒu zǒu.','Cô ấy đang đi về cửa ga ở bên trái.']],question:'Thông tin nào chưa thể biết chỉ từ tranh?',choices:[['外面在下雨。','Mưa thể hiện trực tiếp trong tranh.'],['她拿着一把伞。','Có thể thấy chiếc ô đang được cầm.'],['她的丈夫在车站等她。','Đúng: tranh không cung cấp chồng hay người đang chờ.']],answer:2,transfer:'Thẻ thông tin mới cho biết chính người phụ nữ nói: “Tôi cầm ô vì đang mưa. Tôi đến ga đón bạn.” Viết ba câu tách thời tiết, lý do cầm ô và mục đích đến ga. Không biến lý do cầm ô thành lý do đến ga.',model:['外面在下雨。因为下雨，所以我拿着伞。我去车站接朋友。','Wàimian zài xià yǔ. Yīnwèi xià yǔ, suǒyǐ wǒ ná zhe sǎn. Wǒ qù chēzhàn jiē péngyou.','Bên ngoài đang mưa. Vì mưa nên tôi cầm ô. Tôi đến ga đón bạn.'],criteria:['Nêu mưa là lý do cầm ô theo lời nhân vật.','Đến ga để đón bạn; không phải vì mưa.','Không tự thêm giờ tàu, đã đến ga hoặc đang chạy.']},
];
export const practices:Record<string,BatchPractice>={
 [manuscripts[0].id]:{pattern:'因为…所以…',example:['因为我头疼，所以今天不能去踢足球。','Yīnwèi wǒ tóu téng, suǒyǐ jīntiān bù néng qù tī zúqiú.','Vì tôi đau đầu nên hôm nay không thể đi đá bóng.'],prompt:'Điền liên từ chỉ kết quả: 因为我头疼，___今天不能去踢足球。',answers:['所以'],explanation:'因为 nêu nguyên nhân, 所以 dẫn kết quả. 但是 sẽ chuyển sang quan hệ đối lập.'},
 [manuscripts[1].id]:{pattern:'请 + người + 把 + vật + 带到 + nơi',example:['请你把包带到车站门口。','Qǐng nǐ bǎ bāo dài dào chēzhàn ménkǒu.','Nhờ bạn mang túi đến cửa ga.'],prompt:'Tin mới sửa phải thành trái. Điền một chữ chỉ hướng: 包在门口___边的椅子上，不在右边。',answers:['左'],explanation:'左边 là bên trái. Câu phủ định cuối loại vị trí cũ bên phải.'},
 [manuscripts[2].id]:{pattern:'Nơi + 有 + người/vật',example:['池子里有鱼。','Chízi lǐ yǒu yú.','Trong hồ có cá.'],prompt:'Giới thiệu thứ hiện diện trong hồ, điền động từ: 池子里___鱼。',answers:['有'],explanation:'有 giới thiệu sự hiện diện. 在 dùng khi đã nêu chủ thể: 鱼在池子里。'},
 [manuscripts[3].id]:{pattern:'Động từ + 着',example:['她拿着一把伞。','Tā ná zhe yì bǎ sǎn.','Cô ấy đang cầm một chiếc ô.'],prompt:'Điền trợ từ chỉ trạng thái cầm ô đang duy trì: 她拿___一把伞。',answers:['着'],explanation:'着 đọc zhe nhẹ, chỉ trạng thái đang cầm. 了 diễn tả thay đổi/hoàn tất trong cách dùng khác, không đáp yêu cầu này.'},
};
export const answerReadings:Record<string,[string,string]>={
 [manuscripts[0].id]:['Qǐng nǐ gàosu Xiǎo Wáng.','Nhờ bạn báo Tiểu Vương.'],
 [manuscripts[1].id]:['Jiàoshì ménkǒu zuǒbian de yǐzi shàng.','Trên ghế bên trái cửa phòng học.'],
 [manuscripts[2].id]:['Yòubian de chízi lǐ yǒu yú.','Trong hồ bên phải có cá.'],
 [manuscripts[3].id]:['Tā de zhàngfu zài chēzhàn děng tā.','Chồng cô ấy đang chờ cô ấy ở ga.'],
};
export const examples:Record<string,[string,string,string]>={
 '踢':['我们明天去踢足球。','Wǒmen míngtiān qù tī zúqiú.','Ngày mai chúng tôi đi đá bóng.'],
 '所以':['今天下雨，所以我不去公园。','Jīntiān xià yǔ, suǒyǐ wǒ bú qù gōngyuán.','Hôm nay mưa nên tôi không đi công viên.'],
 '为什么':['你为什么没来上课？','Nǐ wèishénme méi lái shàngkè?','Vì sao bạn đã không đến lớp?'],
 '洗':['吃饭前要洗手。','Chī fàn qián yào xǐ shǒu.','Trước khi ăn cần rửa tay.'],
 '眼睛':['他的眼睛很大。','Tā de yǎnjing hěn dà.','Mắt của anh ấy rất to.'],
 '药':['这不是我的药。','Zhè bú shì wǒ de yào.','Đây không phải thuốc của tôi.'],
 '爷爷':['我爷爷喜欢看书。','Wǒ yéye xǐhuan kàn shū.','Ông nội tôi thích đọc sách.'],
 '旅游':['我们下个月去旅游。','Wǒmen xià ge yuè qù lǚyóu.','Tháng sau chúng tôi đi du lịch.'],
 '右':['请往右走。','Qǐng wǎng yòu zǒu.','Xin đi về phía phải.'],
 '长':['这件外套太长了。','Zhè jiàn wàitào tài cháng le.','Chiếc áo khoác này dài quá.'],
 '丈夫':['她的丈夫是老师。','Tā de zhàngfu shì lǎoshī.','Chồng cô ấy là giáo viên.'],
 '着':['她拿着一把伞。','Tā ná zhe yì bǎ sǎn.','Cô ấy đang cầm một chiếc ô.'],
 '周':['我们每周见一次面。','Wǒmen měi zhōu jiàn yí cì miàn.','Mỗi tuần chúng tôi gặp nhau một lần.'],
 '自己':['这件事我自己做。','Zhè jiàn shì wǒ zìjǐ zuò.','Việc này tôi tự làm.'],
};
