import type {PersonalNarrative} from './hsk3-personal-narratives';
export const studyWorkNarratives:PersonalNarrative[]=[
 {suffix:'courses-learning',scene:'hsk3-reading-notes',goal:'Phân biệt cách học, kết quả và điều chưa kiểm tra',support:'逐字 zhúzì — từng chữ; 标出 biāo chū — đánh dấu; 猜 cāi — đoán; 复述 fùshù — kể lại; 顺序 shùnxù — thứ tự; 仍然 réngrán — vẫn.',paragraphs:[
 ['小林以前读中文的时候，遇到不认识的字就马上查词典。读完一段以后，他常常忘了前面的内容。','Xiǎo Lín yǐqián dú Zhōngwén de shíhou, yù dào bù rènshi de zì jiù mǎshàng chá cídiǎn. Dú wán yí duàn yǐhòu, tā chángcháng wàng le qiánmian de nèiróng.','Trước đây, khi đọc tiếng Trung, Tiểu Lâm gặp chữ lạ là tra ngay. Đọc xong một đoạn, anh thường quên nội dung phía trước.'],
 ['老师建议他先读一遍，记下谁做了什么，再标出不懂的句子。第二遍才查影响理解的重要词语。','Lǎoshī jiànyì tā xiān dú yí biàn, jì xià shéi zuò le shénme, zài biāo chū bù dǒng de jùzi. Dì èr biàn cái chá yǐngxiǎng lǐjiě de zhòngyào cíyǔ.','Giáo viên khuyên đọc một lượt trước, ghi ai làm gì, rồi đánh dấu câu chưa hiểu. Lượt thứ hai mới tra từ quan trọng ảnh hưởng cách hiểu.'],
 ['小林试了这个方法，把每段的意思写在笔记里。一周后，他能说清楚故事的顺序，但是仍然需要查几个词。','Xiǎo Lín shì le zhège fāngfǎ, bǎ měi duàn de yìsi xiě zài bǐjì lǐ. Yì zhōu hòu, tā néng shuō qīngchu gùshi de shùnxù, dànshì réngrán xūyào chá jǐ ge cí.','Tiểu Lâm thử cách này, ghi ý từng đoạn vào vở. Sau một tuần, anh kể rõ được thứ tự câu chuyện nhưng vẫn cần tra vài từ.'],
 ['他觉得新方法有用，准备下周换一篇文章再试。老师提醒他，记住这篇文章还不等于能读懂所有文章。','Tā juéde xīn fāngfǎ yǒuyòng, zhǔnbèi xià zhōu huàn yì piān wénzhāng zài shì. Lǎoshī tíxǐng tā, jì zhù zhè piān wénzhāng hái bù děngyú néng dú dǒng suǒyǒu wénzhāng.','Anh thấy cách mới hữu ích và định tuần sau thử bài khác. Giáo viên nhắc nhớ bài này chưa có nghĩa đọc hiểu được mọi bài.'],
 ],core:['方法','遍','段','查','记','笔记','重要','有用'],rule:'先…再… nêu thứ tự thao tác. 第二遍才… giới hạn lúc tra từ, không cấm tra từ hoàn toàn. 把每段的意思写在… đưa ý từng đoạn lên trước hành động ghi. 能说清楚 chỉ năng lực đã quan sát trên bài này; 准备…再试 là kế hoạch kiểm tra trên bài mới.',pitfall:'Không tóm tắt rằng anh không còn tra từ hoặc đã đọc hiểu mọi văn bản. “Hữu ích” là đánh giá của nhân vật trên lần thử, không phải bảo đảm một phương pháp phù hợp mọi người.',question:'Kết quả nào đã được kiểm tra trong chuyện?',choices:[['他已经能读懂所有中文文章。','Chưa có kiểm tra trên mọi bài.'],['他能说清楚这篇故事的顺序。','Đúng: đây là kết quả sau một tuần.'],['他再也不需要查词典了。','Sai: anh vẫn cần tra vài từ.']],answer:1,cloze:{prompt:'Điền từ nhấn mạnh đến lượt thứ hai mới tra: 第二遍___查重要的词语。',answer:'才',feedback:'才 nhấn mạnh mốc sau bước đọc lấy ý. Không đồng nghĩa không bao giờ tra.'},transfer:'Mai trước đây chép nguyên đoạn nhưng không kể lại được. Cô đổi sang ghi ba ý, đã kể được chuyện cũ không nhìn sách, chưa thử bài mới. Viết 4 câu về khó khăn, thay đổi, kết quả và bước kiểm tra tiếp theo.',model:['小梅以前抄整段文章，可是不能复述。后来，她只记三个要点。现在她不看书也能讲这个故事了。她还没试过新文章，准备明天再试。','Xiǎo Méi yǐqián chāo zhěng duàn wénzhāng, kěshì bù néng fùshù. Hòulái, tā zhǐ jì sān ge yàodiǎn. Xiànzài tā bú kàn shū yě néng jiǎng zhège gùshi le. Tā hái méi shì guo xīn wénzhāng, zhǔnbèi míngtiān zài shì.','Mai trước đây chép cả đoạn nhưng không kể lại được. Sau đó cô chỉ ghi ba ý. Hiện không nhìn sách cô cũng kể được chuyện này. Cô chưa thử bài mới, định mai thử.'],criteria:['Phân biệt chép nguyên đoạn và ghi ba ý.','Kết quả chỉ trên chuyện cũ.','Bài mới là bước tiếp theo, không phải đã làm.']},
 {suffix:'colleague-workplace',scene:'hsk3-team-handoff',goal:'Theo dõi ai chịu trách nhiệm và việc nào còn chờ',support:'负责 fùzé — phụ trách; 表格 biǎogé — bảng; 地址 dìzhǐ — địa chỉ; 核对 héduì — đối chiếu; 重复 chóngfù — lặp; 避免 bìmiǎn — tránh.',paragraphs:[
 ['陈海刚到公司，和同事小王一起准备客人的名单。陈海以为自己只需要收电话号码。','Chén Hǎi gāng dào gōngsī, hé tóngshì Xiǎo Wáng yìqǐ zhǔnbèi kèrén de míngdān. Chén Hǎi yǐwéi zìjǐ zhǐ xūyào shōu diànhuà hàomǎ.','Trần Hải mới đến công ty, cùng Tiểu Vương chuẩn bị danh sách khách. Anh tưởng mình chỉ cần thu số điện thoại.'],
 ['小王却以为陈海也负责核对地址。两个人发现，还有三位客人的地址没有确认。','Xiǎo Wáng què yǐwéi Chén Hǎi yě fùzé héduì dìzhǐ. Liǎng ge rén fāxiàn, hái yǒu sān wèi kèrén de dìzhǐ méiyǒu quèrèn.','Tiểu Vương lại tưởng Trần Hải cũng phụ trách đối chiếu địa chỉ. Họ phát hiện còn địa chỉ ba khách chưa xác nhận.'],
 ['他们没有马上发出名单，而是先把分工写清楚：陈海打电话，小王修改表格，然后两个人一起检查。','Tāmen méiyǒu mǎshàng fā chū míngdān, ér shì xiān bǎ fēngōng xiě qīngchu: Chén Hǎi dǎ diànhuà, Xiǎo Wáng xiūgǎi biǎogé, ránhòu liǎng ge rén yìqǐ jiǎnchá.','Họ chưa gửi ngay, mà ghi rõ phân công trước: Trần Hải gọi điện, Tiểu Vương sửa bảng, rồi cùng kiểm tra.'],
 ['下午，他们确认了两位客人的地址。第三位还没有接电话，所以名单还不能发。陈海说，下次先说明白分工，可以避免重复和遗漏。','Xiàwǔ, tāmen quèrèn le liǎng wèi kèrén de dìzhǐ. Dì sān wèi hái méiyǒu jiē diànhuà, suǒyǐ míngdān hái bù néng fā. Chén Hǎi shuō, xià cì xiān shuō míngbai fēngōng, kěyǐ bìmiǎn chóngfù hé yílòu.','Chiều họ xác nhận địa chỉ hai khách. Khách thứ ba chưa nghe máy nên danh sách chưa thể gửi. Trần Hải nói lần sau làm rõ phân công trước sẽ tránh lặp và bỏ sót.'],
 ],core:['同事','客人','号码','发现','清楚','然后','接','明白'],rule:'以为 nói điều từng tưởng, cần đối chiếu với sự thật sau đó. 没有…而是… sửa cách xử lý: chưa gửi mà làm rõ phân công. 还没有 chỉ việc chưa xong ở thời điểm kể. Hai địa chỉ xác nhận không bằng toàn bộ ba địa chỉ; ghi người phụ trách bên cạnh từng hành động.',pitfall:'Không đổ toàn bộ lỗi cho một người khi văn bản cho thấy hai bên hiểu khác nhau. Phân công mới không tự chứng minh nhiệm vụ đã hoàn tất.',question:'Vì sao danh sách chưa gửi?',choices:[['第三位客人的地址还没有确认。','Đúng: còn một địa chỉ chờ xác nhận.'],['小王没有修改任何表格。','Không có căn cứ khẳng định chưa sửa gì.'],['三位客人都没接电话。','Sai: hai khách đã xác nhận.']],answer:0,cloze:{prompt:'Điền từ trình tự: 先写清楚分工，___一起检查。',answer:'然后',feedback:'然后 nối bước tiếp theo; không biến kế hoạch thành việc đã hoàn tất.'},transfer:'Đổi dữ kiện: Lan gọi đủ ba khách, Minh đã sửa bảng; hai người chưa kiểm tra chung. Viết ba câu nêu phần đã xong và việc cần làm trước khi gửi.',model:['小兰已经联系了三位客人。小明也修改了表格，但是两个人还没有一起检查。他们要先检查，再发名单。','Xiǎo Lán yǐjīng liánxì le sān wèi kèrén. Xiǎo Míng yě xiūgǎi le biǎogé, dànshì liǎng ge rén hái méiyǒu yìqǐ jiǎnchá. Tāmen yào xiān jiǎnchá, zài fā míngdān.','Lan đã liên hệ đủ ba khách. Minh cũng sửa bảng nhưng họ chưa kiểm tra chung. Họ cần kiểm tra trước rồi gửi danh sách.'],criteria:['Đúng người gọi và người sửa.','Chưa kiểm tra chung, không nói đã gửi.','Bước kiểm tra trước bước gửi.']},
];
