import type {PersonalNarrative} from './hsk3-personal-narratives';

/** Original, bounded cases: a family or two named places, never a rule for all of China. */
export const cultureNarratives:PersonalNarrative[]=[
  {
    suffix:'regional-cuisine',goal:'So sánh hai cách nấu và chọn món theo khẩu vị người ăn',
    support:'口味 kǒuwèi — khẩu vị; 做法 zuòfǎ — cách làm; 辣 là cay. Hai công thức trong bài thuộc hai gia đình giả định, không đại diện cả vùng.',
    paragraphs:[
      ['小周准备请两个朋友吃饭。她先问他们喜欢什么味道，才决定做什么。','Xiǎo Zhōu zhǔnbèi qǐng liǎng ge péngyou chī fàn. Tā xiān wèn tāmen xǐhuan shénme wèidào, cái juédìng zuò shénme.','Tiểu Chu định mời hai người bạn ăn. Cô hỏi họ thích vị gì trước rồi mới chọn món.'],
      ['她家常做甜米饭，米里放一点儿糖和香蕉。朋友小林喜欢甜的，可是不能吃太多糖。','Tā jiā cháng zuò tián mǐfàn, mǐ lǐ fàng yìdiǎnr táng hé xiāngjiāo. Péngyou Xiǎo Lín xǐhuan tián de, kěshì bù néng chī tài duō táng.','Nhà cô thường làm cơm ngọt, cho ít đường và chuối. Bạn Tiểu Lâm thích vị ngọt nhưng không thể ăn nhiều đường.'],
      ['另一个朋友小王喜欢辣菜，不爱甜饭。小周打算做一盘不太辣的菜，还把辣的东西放在旁边。','Lìng yí ge péngyou Xiǎo Wáng xǐhuan là cài, bú ài tián fàn. Xiǎo Zhōu dǎsuàn zuò yì pán bú tài là de cài, hái bǎ là de dōngxi fàng zài pángbiān.','Bạn còn lại, Tiểu Vương, thích món cay và không thích cơm ngọt. Tiểu Chu dự định làm đĩa thức ăn không quá cay, để gia vị cay bên cạnh.'],
      ['吃饭时，小林选择少糖的米饭，小王选择加辣的菜。两个人的选择不同，小周也没有说哪种味道更好。','Chī fàn shí, Xiǎo Lín xuǎnzé shǎo táng de mǐfàn, Xiǎo Wáng xuǎnzé jiā là de cài. Liǎng ge rén de xuǎnzé bùtóng, Xiǎo Zhōu yě méiyǒu shuō nǎ zhǒng wèidào gèng hǎo.','Khi ăn, Tiểu Lâm chọn cơm ít đường; Tiểu Vương chọn món thêm cay. Hai người chọn khác nhau; Tiểu Chu không nói vị nào ngon hơn.'],
    ],core:['米','糖','甜','香蕉','选择','不同'],
    rule:'先问…才决定… nêu quyết định dựa trên thông tin người ăn. 少糖 khác với không có đường; 不太辣 khác với không cay. So sánh khẩu vị của hai người, không xếp hạng cả nền ẩm thực.',
    pitfall:'Không kết luận Tiểu Lâm dị ứng đường hoặc Tiểu Vương đến từ một vùng cụ thể. Văn bản chỉ cho biết sở thích và giới hạn lượng đường.',
    question:'Ai đã chọn món nào khi ăn?',choices:[['小林选少糖米饭，小王选加辣的菜。','Đúng: mỗi người chọn theo khẩu vị đã nêu.'],['小林选很辣的菜，小王选甜米饭。','Sai: đã đảo lựa chọn của hai người.'],['两个人都只吃没有糖的米饭。','Sai: cơm ít đường và Tiểu Vương chọn món cay.']],answer:0,
    cloze:{prompt:'Điền từ chỉ kết quả chỉ đến sau bước hỏi: 她先问朋友的口味，___决定做什么。',answer:'才',feedback:'才 nối quyết định với điều kiện đã hỏi khẩu vị.'},
    transfer:'Bữa ăn khác: An thích món ít cay; Bình thích vị chua nhưng không ăn được nhiều muối. Chủ nhà hỏi trước, chuẩn bị hai lựa chọn và để gia vị riêng. Viết 3–4 câu, không biến sở thích thành quy tắc của cả vùng.',
    model:['主人先问安和小平喜欢什么味道，才决定做菜。安选了不太辣的菜。小平喜欢酸的，但是不能吃太多盐。主人把调味的东西放在旁边，让他们自己选择。','Zhǔrén xiān wèn Ān hé Xiǎo Píng xǐhuan shénme wèidào, cái juédìng zuò cài. Ān xuǎn le bú tài là de cài. Xiǎo Píng xǐhuan suān de, dànshì bù néng chī tài duō yán. Zhǔrén bǎ tiáowèi de dōngxi fàng zài pángbiān, ràng tāmen zìjǐ xuǎnzé.','Chủ nhà hỏi khẩu vị An và Bình trước rồi mới nấu. An chọn món không quá cay. Bình thích chua nhưng không ăn nhiều muối. Chủ nhà để gia vị riêng để họ tự chọn.'],
    criteria:['Giữ riêng khẩu vị và giới hạn của An, Bình.','Có bước hỏi trước khi chọn món.','Không gán một khẩu vị cho tất cả người trong vùng.'],
  },
  {
    suffix:'tableware-etiquette',goal:'Đọc hướng dẫn dùng dụng cụ và lịch sự hỏi trước khi giúp',
    support:'公筷 gōngkuài — đũa gắp chung; 夹 jiā — gắp; 主人 zhǔrén — chủ nhà. Bài mô tả quy ước của một bữa ăn giả định, không phải luật chung.',
    paragraphs:[
      ['小方第一次到陈阿姨家做客。桌上有饭碗、勺子和两双筷子，他不太明白怎样用。','Xiǎo Fāng dì yī cì dào Chén āyí jiā zuò kè. Zhuō shàng yǒu fànwǎn, sháozi hé liǎng shuāng kuàizi, tā bú tài míngbai zěnyàng yòng.','Tiểu Phương lần đầu làm khách nhà dì Trần. Trên bàn có bát, thìa và hai đôi đũa; cậu chưa rõ cách dùng.'],
      ['陈阿姨说，一双筷子用来吃自己碗里的东西，另一双是公筷，大家用它夹中间盘子里的菜。','Chén āyí shuō, yì shuāng kuàizi yòng lái chī zìjǐ wǎn lǐ de dōngxi, lìng yì shuāng shì gōngkuài, dàjiā yòng tā jiā zhōngjiān pánzi lǐ de cài.','Dì Trần giải thích một đôi dùng để ăn đồ trong bát riêng, đôi còn lại là đũa gắp chung dùng lấy món ở đĩa giữa bàn.'],
      ['小方看见老人够不到一盘菜，想帮忙。他先问“我帮您夹一点儿，好吗？”，老人说“好”，他才用公筷夹菜。','Xiǎo Fāng kànjiàn lǎorén gòu bú dào yì pán cài, xiǎng bāngmáng. Tā xiān wèn “Wǒ bāng nín jiā yìdiǎnr, hǎo ma?”, lǎorén shuō “Hǎo”, tā cái yòng gōngkuài jiā cài.','Thấy người lớn tuổi khó với tới một đĩa thức ăn, cậu muốn giúp. Cậu hỏi trước “Cháu gắp giúp bác một ít nhé?”, người ấy đồng ý rồi cậu mới dùng đũa chung gắp.'],
      ['饭后，小方把碗和勺子放在一起，并感谢主人。陈阿姨说，遇到不懂的做法，先问清楚比猜更方便。','Fàn hòu, Xiǎo Fāng bǎ wǎn hé sháozi fàng zài yìqǐ, bìng gǎnxiè zhǔrén. Chén āyí shuō, yùdào bù dǒng de zuòfǎ, xiān wèn qīngchu bǐ cāi gèng fāngbiàn.','Sau bữa ăn cậu đặt bát và thìa cạnh nhau rồi cảm ơn chủ nhà. Dì Trần nói khi chưa hiểu cách làm, hỏi rõ sẽ tiện hơn đoán.'],
    ],core:['筷子','碗','勺子','怎样','方便'],
    rule:'一双…另一双… đối chiếu hai đôi đũa. 先问…才… cho biết chỉ giúp sau khi được đồng ý. 公筷 dùng gắp từ đĩa chung trong bữa ăn này; không suy mọi nhà bày bàn giống vậy.',
    pitfall:'Không viết Tiểu Phương tự gắp cho người khác trước khi hỏi. Không đổi đũa dùng riêng thành đũa gắp chung.',
    question:'Tiểu Phương đã làm gì trước khi gắp giúp?',choices:[['先问，对方同意后才用公筷夹菜。','Đúng: hỏi và nhận đồng ý trước khi gắp.'],['不问就用自己的筷子夹菜。','Sai: cậu có hỏi và dùng đũa gắp chung.'],['先把勺子放进中间的盘子。','Sai: bát và thìa được đặt cùng nhau sau bữa ăn.']],answer:0,
    cloze:{prompt:'Điền từ chỉ hành động chỉ xảy ra sau khi được đồng ý: 老人说“好”，小方___夹菜。',answer:'才',feedback:'才 giữ thứ tự hỏi → đồng ý → giúp.'},
    transfer:'Ở bữa ăn khác, Mai thấy bạn không với tới bình nước. Mai hỏi trước, bạn đồng ý; sau đó Mai rót nước vào cốc của bạn. Bàn có cốc riêng và một bình chung. Viết 3–4 câu đúng thứ tự, không gán quy tắc cho mọi bữa ăn.',
    model:['桌上有大家一起用的水壶，每个人有自己的杯子。小梅看见朋友够不到水壶，先问他要不要水。他说要，她才把水倒进他的杯子。小梅没有替他决定喝多少。','Zhuō shàng yǒu dàjiā yìqǐ yòng de shuǐhú, měi ge rén yǒu zìjǐ de bēizi. Xiǎo Méi kànjiàn péngyou gòu bú dào shuǐhú, xiān wèn tā yào bú yào shuǐ. Tā shuō yào, tā cái bǎ shuǐ dào jìn tā de bēizi. Xiǎo Méi méiyǒu tì tā juédìng hē duōshao.','Trên bàn có bình nước chung và cốc riêng. Mai thấy bạn không với tới bình nên hỏi bạn có muốn nước không. Bạn đồng ý rồi Mai mới rót. Mai không tự quyết bạn uống bao nhiêu.'],
    criteria:['Phân biệt bình chung với cốc riêng.','Hỏi và được đồng ý trước khi rót.','Không tự thêm hành động bạn không yêu cầu.'],
  },
  {
    suffix:'festivals-customs',goal:'Kể đúng trình tự chuẩn bị và thực hiện một dịp lễ của gia đình',
    support:'过节 guòjié — đón lễ; 月饼 yuèbǐng — bánh Trung thu; 中秋节 Zhōngqiū Jié — Tết Trung thu. Đây là lịch của gia đình trong chuyện.',
    paragraphs:[
      ['中秋节快到了，小雨一家打算周六晚上一起吃饭。爸爸先问客人有没有不能吃的东西。','Zhōngqiū Jié kuài dào le, Xiǎo Yǔ yì jiā dǎsuàn Zhōuliù wǎnshang yìqǐ chī fàn. Bàba xiān wèn kèrén yǒu méiyǒu bù néng chī de dōngxi.','Tết Trung thu sắp tới, nhà Tiểu Vũ dự định ăn cùng nhau tối thứ Bảy. Bố hỏi khách trước xem có món gì không thể ăn.'],
      ['星期五，妈妈和小雨买了水果和两种月饼。妈妈说，月饼是这次聚会的一种节日食物，不是每个人都一定要吃。','Xīngqīwǔ, māma hé Xiǎo Yǔ mǎi le shuǐguǒ hé liǎng zhǒng yuèbǐng. Māma shuō, yuèbǐng shì zhè cì jùhuì de yì zhǒng jiérì shíwù, bú shì měi ge rén dōu yídìng yào chī.','Thứ Sáu mẹ và Tiểu Vũ mua trái cây cùng hai loại bánh Trung thu. Mẹ nói bánh là một món dịp lễ trong buổi gặp này; không phải ai cũng buộc phải ăn.'],
      ['周六晚上，客人来了。大家先吃饭，再到外面看月亮。一个客人不吃月饼，小雨就请他吃水果。','Zhōuliù wǎnshang, kèrén lái le. Dàjiā xiān chī fàn, zài dào wàimiàn kàn yuèliang. Yí ge kèrén bù chī yuèbǐng, Xiǎo Yǔ jiù qǐng tā chī shuǐguǒ.','Tối thứ Bảy khách tới. Mọi người ăn trước rồi ra ngoài ngắm trăng. Một người khách không ăn bánh; Tiểu Vũ mời người ấy trái cây.'],
      ['聚会结束以后，小雨写下了家里的安排，想明年再看。她记录的是这一次的做法，没有说每个家庭都一样。','Jùhuì jiéshù yǐhòu, Xiǎo Yǔ xiě xià le jiālǐ de ānpái, xiǎng míngnián zài kàn. Tā jìlù de shì zhè yí cì de zuòfǎ, méiyǒu shuō měi ge jiātíng dōu yíyàng.','Sau buổi gặp, Tiểu Vũ ghi lại lịch nhà mình để năm sau xem. Em ghi cách làm lần này, không nói mọi gia đình đều giống thế.'],
    ],core:['节日','月亮','客人','先','结束'],
    rule:'快到了 và 打算 chỉ việc sắp đến/dự định; thứ Sáu đã mua đồ; tối thứ Bảy đã ăn rồi ngắm trăng. 先…再… xác định thứ tự. 节日食物 không đồng nghĩa mọi khách phải ăn.',
    pitfall:'Không nói tối thứ Sáu đã ngắm trăng. Không biến lịch một gia đình thành phong tục bắt buộc của tất cả người Trung Quốc.',
    question:'Trong tối thứ Bảy, mọi người làm gì theo thứ tự?',choices:[['先吃饭，再到外面看月亮。','Đúng: ăn trước, ngắm trăng sau.'],['先看月亮，星期五才买水果。','Sai: trái cây đã mua thứ Sáu và thứ tự tối thứ Bảy ngược lại.'],['每个客人都先吃月饼。','Sai: một khách không ăn bánh.']],answer:0,
    cloze:{prompt:'Điền từ chỉ bước sau: 大家先吃饭，___到外面看月亮。',answer:'再',feedback:'先…再… ghi trình tự hai việc trong buổi gặp.'},
    transfer:'Gia đình khác mừng sinh nhật Chủ nhật: thứ Bảy mua hoa, Chủ nhật đón khách, ăn trưa rồi chụp ảnh. Một khách không uống trà và được mời nước. Viết 3–4 câu theo mốc, không nói mọi gia đình đều làm vậy.',
    model:['星期六，这家人买了花。星期天，客人来了以后，大家先吃午饭，再一起拍照。一个客人不喝茶，主人就请他喝水。这只是这家人的生日安排。','Xīngqīliù, zhè jiā rén mǎi le huā. Xīngqītiān, kèrén lái le yǐhòu, dàjiā xiān chī wǔfàn, zài yìqǐ pāizhào. Yí ge kèrén bù hē chá, zhǔrén jiù qǐng tā hē shuǐ. Zhè zhǐ shì zhè jiā rén de shēngrì ānpái.','Thứ Bảy nhà này mua hoa. Chủ nhật sau khi khách tới, mọi người ăn trưa rồi chụp ảnh. Một khách không uống trà nên chủ mời nước. Đây chỉ là lịch sinh nhật của gia đình ấy.'],
    criteria:['Thứ Bảy mua hoa, Chủ nhật mới đón khách.','Giữ thứ tự ăn trưa trước, chụp ảnh sau.','Có lựa chọn đồ uống cho khách và giới hạn một gia đình.'],
  },
  {
    suffix:'regional-differences',goal:'So sánh hai địa điểm theo dữ kiện cụ thể mà không khái quát quá mức',
    support:'海边 hǎibiān — ven biển; 山里 shān lǐ — trong núi; 地图 dìtú — bản đồ. Chỉ so sánh hai địa điểm giả định trong cùng một tuần.',
    paragraphs:[
      ['小何要去看两位朋友，一个住在海边的青镇，一个住在山里的松村。他先查地图和这一周的天气。','Xiǎo Hé yào qù kàn liǎng wèi péngyou, yí ge zhù zài hǎibiān de Qīng Zhèn, yí ge zhù zài shān lǐ de Sōng Cūn. Tā xiān chá dìtú hé zhè yì zhōu de tiānqì.','Tiểu Hà định thăm hai bạn: một ở thị trấn Thanh ven biển, một ở làng Tùng trong núi. Anh xem bản đồ và thời tiết tuần này trước.'],
      ['地图上，青镇离车站近，坐车二十分钟就到了。这周那里白天比较热，朋友请他带水。','Dìtú shàng, Qīng Zhèn lí chēzhàn jìn, zuò chē èrshí fēnzhōng jiù dào le. Zhè zhōu nàli báitiān bǐjiào rè, péngyou qǐng tā dài shuǐ.','Theo bản đồ, thị trấn Thanh gần ga, đi xe hai mươi phút. Ban ngày tuần này ở đó khá nóng nên bạn nhắc anh mang nước.'],
      ['松村离车站远一些，坐车要一个小时。这周早晚比较冷，另一个朋友请他带外套。','Sōng Cūn lí chēzhàn yuǎn yìxiē, zuò chē yào yí ge xiǎoshí. Zhè zhōu zǎowǎn bǐjiào lěng, lìng yí ge péngyou qǐng tā dài wàitào.','Làng Tùng xa ga hơn, đi xe một giờ. Sáng tối tuần này khá lạnh nên người bạn kia nhắc anh mang áo khoác.'],
      ['小何把两条消息写在一起：去青镇带水，去松村带外套。他知道这只是这周的情况，不能说明所有海边和山里都这样。','Xiǎo Hé bǎ liǎng tiáo xiāoxi xiě zài yìqǐ: qù Qīng Zhèn dài shuǐ, qù Sōng Cūn dài wàitào. Tā zhīdào zhè zhǐ shì zhè zhōu de qíngkuàng, bù néng shuōmíng suǒyǒu hǎibiān hé shān lǐ dōu zhèyàng.','Tiểu Hà ghép hai thông tin: đi Thanh mang nước, đi Tùng mang áo khoác. Anh biết đây chỉ là tình hình tuần này, không chứng minh mọi nơi ven biển và miền núi đều như vậy.'],
    ],core:['不同','比较','带','海','地图'],
    rule:'So sánh cần nói rõ tiêu chí: thời gian từ ga và thời tiết tuần này. 二十分钟 khác 一小时; 白天 khác 早晚. Dữ liệu của hai nơi trong một tuần không suy ra khí hậu mọi vùng.',
    pitfall:'Không kết luận làng Tùng luôn lạnh hoặc thị trấn Thanh an toàn hơn; văn bản không cho dữ liệu an toàn.',
    question:'Thời gian đi xe từ ga đến hai nơi là bao lâu?',choices:[['青镇二十分钟，松村一个小时。','Đúng: hai thời gian từ ga được nêu rõ.'],['青镇一个小时，松村二十分钟。','Sai: đã đảo thời gian.'],['两个地方都只要二十分钟。','Sai: làng Tùng cần một giờ.']],answer:0,
    cloze:{prompt:'Điền từ chỉ mức độ: 松村离车站___远。',answer:'比较',feedback:'比较远 diễn tả tương đối xa; dữ kiện cụ thể là một giờ từ ga.'},
    transfer:'Hai điểm đọc sách giả định: thư viện A cách trường 10 phút, mở buổi sáng; phòng đọc B cách 25 phút, mở buổi chiều. Lan chỉ có thời gian buổi chiều. Viết 3–4 câu so sánh theo khoảng cách và giờ mở, rồi chọn đúng nơi, không suy chất lượng sách.',
    model:['图书馆A离学校十分钟，上午开放。阅览室B离学校二十五分钟，下午开放。小兰只有下午有时间，所以她选择去阅览室B。这个选择根据时间，不说明哪里的书更好。','Túshūguǎn A lí xuéxiào shí fēnzhōng, shàngwǔ kāifàng. Yuèlǎnshì B lí xuéxiào èrshíwǔ fēnzhōng, xiàwǔ kāifàng. Xiǎo Lán zhǐ yǒu xiàwǔ yǒu shíjiān, suǒyǐ tā xuǎnzé qù yuèlǎnshì B. Zhège xuǎnzé gēnjù shíjiān, bù shuōmíng nǎli de shū gèng hǎo.','Thư viện A cách trường 10 phút, mở sáng. Phòng đọc B cách 25 phút, mở chiều. Lan chỉ rảnh chiều nên chọn B. Lựa chọn này theo thời gian, không chứng minh sách nơi nào tốt hơn.'],
    criteria:['Đúng khoảng cách và giờ mở của từng nơi.','Chọn B vì Lan rảnh buổi chiều.','Không suy chất lượng sách từ khoảng cách.'],
  },
  {
    suffix:'customs-comparison',goal:'Tổng hợp hai cách tiếp khách, chỉ ra điểm chung và phần chưa biết',
    support:'做客 zuòkè — làm khách; 习惯 xíguàn — thói quen; 文化 wénhuà — văn hóa. Hai lịch tiếp khách là ví dụ cá nhân, không đại diện quốc gia.',
    paragraphs:[
      ['小安和小丽做一份关于做客的课文。他们各问一位朋友，想了解不同的做客习惯。','Xiǎo Ān hé Xiǎo Lì zuò yí fèn guānyú zuòkè de kèwén. Tāmen gè wèn yí wèi péngyou, xiǎng liǎojiě bùtóng de zuòkè xíguàn.','An và Lệ làm một bài đọc về đi làm khách. Mỗi người hỏi một bạn để tìm hiểu hai cách đi thăm khác nhau.'],
      ['朋友甲说，他上周到邻居家做客，先打电话约时间，到了以后一起喝茶。主人没有准备晚饭。','Péngyou Jiǎ shuō, tā shàng zhōu dào línjū jiā zuò kè, xiān dǎ diànhuà yuē shíjiān, dào le yǐhòu yìqǐ hē chá. Zhǔrén méiyǒu zhǔnbèi wǎnfàn.','Bạn A kể tuần trước đến nhà hàng xóm: gọi điện hẹn trước, tới nơi cùng uống trà. Chủ nhà không chuẩn bị bữa tối.'],
      ['朋友乙说，她去同学家以前也先约了时间。那天同学请她吃晚饭，还问她有没有不能吃的东西。','Péngyou Yǐ shuō, tā qù tóngxué jiā yǐqián yě xiān yuē le shíjiān. Nà tiān tóngxué qǐng tā chī wǎnfàn, hái wèn tā yǒu méiyǒu bù néng chī de dōngxi.','Bạn B cũng hẹn giờ trước khi tới nhà bạn học. Hôm đó chủ nhà mời ăn tối và hỏi có món gì cô không ăn được.'],
      ['两次做客都先约时间，吃喝的安排却不同。最后，小安说，只问了两个人，不能根据这两次经历说所有家庭都一样。','Liǎng cì zuò kè dōu xiān yuē shíjiān, chī hē de ānpái què bùtóng. Zuìhòu, Xiǎo Ān shuō, zhǐ wèn le liǎng ge rén, bù néng gēnjù zhè liǎng cì jīnglì shuō suǒyǒu jiātíng dōu yíyàng.','Cả hai chuyến thăm đều hẹn trước nhưng cách mời ăn uống khác nhau. Cuối cùng An nói chỉ hỏi hai người, không thể từ hai trải nghiệm suy ra mọi gia đình đều giống nhau.'],
    ],core:['做客','习惯','了解','不同','最后'],
    rule:'都… nhưng 却不同 giúp tách điểm chung khỏi điểm khác. Hai trường hợp đều hẹn trước; chỉ B được mời ăn tối. Mẫu hai người quá nhỏ để kết luận phong tục của mọi gia đình hay quốc gia.',
    pitfall:'Không nói bạn A được mời ăn tối; bài phủ nhận. Không gán hai người cho hai quốc gia vì không có quốc tịch trong nguồn.',
    question:'Điểm chung được cả hai lời kể xác nhận là gì?',choices:[['两个人去做客以前都约了时间。','Đúng: cả hai đều hẹn giờ trước.'],['两个人都在主人家吃了晚饭。','Sai: nhà bạn A không chuẩn bị bữa tối.'],['两个人来自不同的国家。','Sai: bài không cho biết quốc tịch.']],answer:0,
    cloze:{prompt:'Điền từ thể hiện điểm chung: 两次做客___先约时间。',answer:'都',feedback:'都 gom điều đúng ở cả hai trường hợp; ăn tối thì khác.'},
    transfer:'Hai lần ghé nhà khác: C hẹn giờ trước, tới nơi uống nước; D hẹn giờ trước, tới nơi cùng làm bánh. Viết 3–4 câu nêu điểm chung, điểm khác và giới hạn rằng chỉ có hai trường hợp.',
    model:['小陈去朋友家以前先约了时间，到了以后一起喝水。小杜也先约了时间，但是他到朋友家以后一起做蛋糕。两个人都先约时间，后面的活动不同。这只是两次做客的经历，不能说明所有家庭都这样。','Xiǎo Chén qù péngyou jiā yǐqián xiān yuē le shíjiān, dào le yǐhòu yìqǐ hē shuǐ. Xiǎo Dù yě xiān yuē le shíjiān, dànshì tā dào péngyou jiā yǐhòu yìqǐ zuò dàngāo. Liǎng ge rén dōu xiān yuē shíjiān, hòumiàn de huódòng bùtóng. Zhè zhǐ shì liǎng cì zuò kè de jīnglì, bù néng shuōmíng suǒyǒu jiātíng dōu zhèyàng.','C hẹn trước rồi cùng uống nước; D cũng hẹn trước nhưng cùng làm bánh. Cả hai đều hẹn giờ, hoạt động sau đó khác nhau. Chỉ có hai trải nghiệm, không đại diện mọi gia đình.'],
    criteria:['Nêu đúng điểm chung là hẹn giờ trước.','Phân biệt uống nước và làm bánh.','Nêu giới hạn hai trường hợp, không khái quát thành quy tắc.'],
  },
];
