import type {PersonalNarrative} from './hsk3-personal-narratives';

export const natureNarratives:PersonalNarrative[]=[
 {suffix:'climate-seasons',scene:'hsk3-season-preparation',goal:'So sánh bốn mùa và chuẩn bị theo dự báo cụ thể',support:'预报 yùbào — dự báo; 气温 qìwēn — nhiệt độ; 结冰 jiébīng — đóng băng; 薄外套 báo wàitào — áo khoác mỏng. Các đặc điểm sau chỉ thuộc thành phố giả định trong bài.',paragraphs:[
 ['小安住的城市四季不同。春天，公园里的树开始开花，但是早晚还有点儿冷。出门时，他常带一件外套。','Xiǎo Ān zhù de chéngshì sìjì bùtóng. Chūntiān, gōngyuán lǐ de shù kāishǐ kāi huā, dànshì zǎowǎn hái yǒudiǎnr lěng. Chū mén shí, tā cháng dài yí jiàn wàitào.','Thành phố An sống có bốn mùa khác nhau. Mùa xuân, cây trong công viên bắt đầu nở hoa nhưng sáng tối vẫn hơi lạnh. Khi ra ngoài, anh thường mang áo khoác.'],
 ['夏天中午很热，下午有时下雨。小安去学校以前先看天气预报。如果可能下雨，他就带雨衣，不只看出门时有没有太阳。','Xiàtiān zhōngwǔ hěn rè, xiàwǔ yǒushí xià yǔ. Xiǎo Ān qù xuéxiào yǐqián xiān kàn tiānqì yùbào. Rúguǒ kěnéng xià yǔ, tā jiù dài yǔyī, bù zhǐ kàn chū mén shí yǒu méiyǒu tàiyáng.','Trưa mùa hè rất nóng, chiều đôi khi mưa. Trước khi đi học, An xem dự báo. Nếu có thể mưa, anh mang áo mưa, không chỉ nhìn lúc ra cửa có nắng không.'],
 ['秋天比夏天凉快，适合在公园散步。冬天常刮冷风，有时河边的路会结冰，他走路时更注意安全。','Qiūtiān bǐ xiàtiān liángkuai, shìhé zài gōngyuán sànbù. Dōngtiān cháng guā lěng fēng, yǒushí hébiān de lù huì jiébīng, tā zǒu lù shí gèng zhùyì ānquán.','Thu mát hơn hè, hợp đi dạo công viên. Đông thường có gió lạnh, đường ven sông đôi khi đóng băng; anh chú ý an toàn hơn khi đi bộ.'],
 ['明天虽然是春天，预报却说下午有大风和雨。小安准备带外套和雨衣。他说，季节能帮助了解一般情况，出门还要看当天的天气。','Míngtiān suīrán shì chūntiān, yùbào què shuō xiàwǔ yǒu dà fēng hé yǔ. Xiǎo Ān zhǔnbèi dài wàitào hé yǔyī. Tā shuō, jìjié néng bāngzhù liǎojiě yìbān qíngkuàng, chū mén hái yào kàn dàngtiān de tiānqì.','Dù đang mùa xuân, dự báo ngày mai nói chiều có gió lớn và mưa. An định mang áo khoác và áo mưa. Anh nói mùa giúp hiểu tình hình chung, nhưng ra ngoài vẫn cần xem thời tiết ngày đó.'],
 ],core:['四季','春天','开花','夏天','雨衣','秋天','冬天','凉快'],rule:'比 nối hai đối tượng so sánh: 秋天比夏天凉快. 有时/常 phân biệt đôi khi và thường, không phải ngày nào cũng vậy. 虽然…却… nêu dự báo khác điều có thể kỳ vọng từ tên mùa. Nếu…thì… chỉ điều kiện, không khẳng định chắc chắn mưa.',pitfall:'Không biến khí hậu một thành phố giả định thành quy luật cho cả Trung Quốc. Không nói ngày mai chắc có nắng chỉ vì là mùa xuân.',question:'Vì sao An định mang áo mưa ngày mai?',choices:[['因为预报说明天下午有雨。','Đúng: chuẩn bị theo dự báo chiều mai.'],['因为春天每天都下雨。','Không có dữ kiện nói ngày nào cũng mưa.'],['因为冬天已经到了。','Sai: đang mùa xuân.']],answer:0,cloze:{prompt:'Điền từ so sánh: 秋天___夏天凉快。',answer:'比',feedback:'比 đặt giữa hai đối tượng, phía sau là đặc điểm so sánh.'},transfer:'Một thành phố khác: xuân nhiều gió, hè khô nóng, thu hay mưa, đông ít mưa nhưng lạnh. Mai là mùa thu nhưng dự báo khô ráo, sáng lạnh, trưa ấm. Viết 4–5 câu so sánh mùa và chọn mang áo khoác; không chép mưa chiều mai của truyện.',model:['这个城市春天风多，夏天又干又热。秋天常下雨，冬天雨少，可是很冷。明天虽然是秋天，预报却说没有雨。早上冷，中午暖和，所以我准备带外套。','Zhège chéngshì chūntiān fēng duō, xiàtiān yòu gān yòu rè. Qiūtiān cháng xià yǔ, dōngtiān yǔ shǎo, kěshì hěn lěng. Míngtiān suīrán shì qiūtiān, yùbào què shuō méiyǒu yǔ. Zǎoshang lěng, zhōngwǔ nuǎnhuo, suǒyǐ wǒ zhǔnbèi dài wàitào.','Thành phố này xuân nhiều gió, hè khô nóng. Thu hay mưa; đông ít mưa nhưng lạnh. Dù mai đang mùa thu, dự báo không mưa. Sáng lạnh, trưa ấm nên tôi định mang áo khoác.'],criteria:['Đủ bốn mùa của thành phố mới.','Tách đặc điểm thường gặp và dự báo ngày mai.','Mang áo vì sáng lạnh, không tự thêm mưa.']},
 {suffix:'environment-state',scene:'hsk3-stairwell-cleanup',goal:'Tóm tắt hiện trạng, buổi dọn và cách duy trì kết quả',support:'扶手 fúshǒu — tay vịn; 灰尘 huīchén — bụi; 分工 fēngōng — phân công; 轮流 lúnliú — luân phiên; 记录 jìlù — ghi lại.',paragraphs:[
 ['小区的楼梯最近很脏，扶手上也有灰尘。邻居们发现，有人把旧纸箱放在楼梯口，走路不方便。','Xiǎoqū de lóutī zuìjìn hěn zāng, fúshǒu shàng yě yǒu huīchén. Línjūmen fāxiàn, yǒu rén bǎ jiù zhǐxiāng fàng zài lóutīkǒu, zǒu lù bù fāngbiàn.','Cầu thang khu nhà gần đây bẩn, tay vịn có bụi. Hàng xóm phát hiện có người để thùng giấy cũ ở lối cầu thang, gây bất tiện đi lại.'],
 ['周六，大家一起打扫。开始时没有分工，两个人扫同一层，却没有人擦扶手。后来，他们先说清楚每个人做什么。','Zhōuliù, dàjiā yìqǐ dǎsǎo. Kāishǐ shí méiyǒu fēngōng, liǎng ge rén sǎo tóng yì céng, què méiyǒu rén cā fúshǒu. Hòulái, tāmen xiān shuō qīngchu měi ge rén zuò shénme.','Thứ Bảy mọi người cùng dọn. Ban đầu chưa phân công nên hai người quét cùng tầng, không ai lau tay vịn. Sau đó họ làm rõ nhiệm vụ từng người.'],
 ['忙了半天，楼梯干净了，纸箱也搬走了。邻居们觉得环境比以前好，可是知道打扫一次不能解决所有问题。','Máng le bàn tiān, lóutī gānjìng le, zhǐxiāng yě bān zǒu le. Línjūmen juéde huánjìng bǐ yǐqián hǎo, kěshì zhīdào dǎsǎo yí cì bù néng jiějué suǒyǒu wèntí.','Bận nửa ngày, cầu thang sạch, thùng giấy được dời đi. Hàng xóm thấy môi trường tốt hơn trước nhưng biết dọn một lần chưa giải quyết mọi vấn đề.'],
 ['他们决定每周轮流检查，发现东西挡路就联系主人处理。下周才开始记录，现在还不知道一个月后能不能保持干净。','Tāmen juédìng měi zhōu lúnliú jiǎnchá, fāxiàn dōngxi dǎng lù jiù liánxì zhǔrén chǔlǐ. Xià zhōu cái kāishǐ jìlù, xiànzài hái bù zhīdào yí ge yuè hòu néng bù néng bǎochí gānjìng.','Họ quyết định mỗi tuần luân phiên kiểm tra, thấy đồ chắn lối thì liên hệ chủ đồ xử lý. Tuần sau mới bắt đầu ghi nhận; hiện chưa biết một tháng sau có giữ sạch được không.'],
 ],core:['楼梯','脏','邻居','打扫','半天','干净','环境','解决'],rule:'把旧纸箱放在… nói đồ vật được đặt ở đâu. 干净了 nêu trạng thái đã thay đổi. 比以前好 chỉ so với trước buổi dọn. 决定/下周才开始 thuộc kế hoạch, không trộn với việc đã làm xong.',pitfall:'Không viết mọi người đã duy trì sạch một tháng. “半天” là nửa ngày, không suy đúng một số giờ cụ thể.',question:'Kết quả nào đã xảy ra?',choices:[['楼梯已经保持干净一个月。','Chưa có quan sát sau một tháng.'],['楼梯干净了，纸箱搬走了。','Đúng: hai kết quả sau buổi dọn.'],['每个人一开始就知道分工。','Sai: ban đầu chưa phân công.']],answer:1,cloze:{prompt:'Điền từ chỉ thay đổi trạng thái: 打扫以后，楼梯干净___。',answer:'了',feedback:'了 cuối câu đánh dấu trạng thái mới: cầu thang nay sạch.'},transfer:'Khu khác: hành lang có xe đạp chắn lối. Cư dân đã dời xe và lau sàn trong buổi sáng. Họ định ngày mai kẻ chỗ để xe, chưa làm. Viết 4 câu tách hiện trạng, kết quả và kế hoạch.',model:['以前，走廊里有自行车挡路。今天上午，居民搬走了自行车，也擦了地。现在走路方便多了。他们打算明天画出停车的位置，还没有开始。','Yǐqián, zǒuláng lǐ yǒu zìxíngchē dǎng lù. Jīntiān shàngwǔ, jūmín bān zǒu le zìxíngchē, yě cā le dì. Xiànzài zǒu lù fāngbiàn duō le. Tāmen dǎsuàn míngtiān huà chū tíng chē de wèizhi, hái méiyǒu kāishǐ.','Trước đây hành lang có xe chắn. Sáng nay cư dân dời xe và lau sàn. Hiện đi lại tiện hơn nhiều. Họ định mai kẻ chỗ đỗ, chưa bắt đầu.'],criteria:['Đúng xe đạp ở hành lang, không chép thùng giấy.','Dời xe/lau sàn đã xong.','Kẻ chỗ để xe mới là dự định.']},
 {suffix:'environment-protection',scene:'hsk3-green-commute',goal:'Đọc khảo sát và chọn giải pháp đúng trở ngại đi lại',support:'调查 diàochá — khảo sát; 受访者 shòufǎngzhě — người được hỏi; 停车处 tíngchēchù — chỗ đỗ xe; 使用率 shǐyònglǜ — tỷ lệ sử dụng. Số liệu giả định phục vụ bài học.',paragraphs:[
 ['小林调查了二十位同事怎样上班。十二个人住得离公司不远，其中八个人说愿意骑自行车，但是现在很少骑。','Xiǎo Lín diàochá le èrshí wèi tóngshì zěnyàng shàng bān. Shí’èr ge rén zhù de lí gōngsī bù yuǎn, qízhōng bā ge rén shuō yuànyì qí zìxíngchē, dànshì xiànzài hěn shǎo qí.','Lâm khảo sát cách đi làm của 20 đồng nghiệp. 12 người ở gần công ty; trong số đó 8 người nói sẵn lòng đi xe đạp nhưng hiện ít đi.'],
 ['小林问原因。有人怕没有安全的停车处，有人说雨天不方便。住得远的同事更关心公共汽车的时间。','Xiǎo Lín wèn yuányīn. Yǒu rén pà méiyǒu ānquán de tíngchēchù, yǒu rén shuō yǔtiān bù fāngbiàn. Zhù de yuǎn de tóngshì gèng guānxīn gōnggòng qìchē de shíjiān.','Lâm hỏi nguyên nhân. Có người lo thiếu chỗ đỗ an toàn, có người thấy ngày mưa bất tiện. Người ở xa quan tâm giờ xe buýt hơn.'],
 ['大家没有要求所有人每天骑车，而是建议先增加停车处。平时可以骑车，雨天或者路远时可以选择公共汽车。','Dàjiā méiyǒu yāoqiú suǒyǒu rén měi tiān qí chē, ér shì jiànyì xiān zēngjiā tíngchēchù. Píngshí kěyǐ qí chē, yǔtiān huòzhě lù yuǎn shí kěyǐ xuǎnzé gōnggòng qìchē.','Mọi người không yêu cầu tất cả đạp xe mỗi ngày mà đề nghị tăng chỗ đỗ trước. Thường ngày có thể đạp xe; trời mưa hoặc đường xa có thể chọn xe buýt.'],
 ['公司同意先试一个月，再调查实际骑车的人数。现在只有建议，还不能说使用率已经提高了。小林也提醒大家，二十位同事不代表全城的人。','Gōngsī tóngyì xiān shì yí ge yuè, zài diàochá shíjì qí chē de rénshù. Xiànzài zhǐ yǒu jiànyì, hái bù néng shuō shǐyònglǜ yǐjīng tígāo le. Xiǎo Lín yě tíxǐng dàjiā, èrshí wèi tóngshì bù dàibiǎo quán chéng de rén.','Công ty đồng ý thử một tháng rồi khảo sát số người thực tế đạp xe. Hiện mới có đề xuất, chưa thể nói tỷ lệ sử dụng tăng. Lâm nhắc 20 đồng nghiệp không đại diện toàn thành phố.'],
 ],core:['自行车','愿意','骑','安全','方便','或者','选择','提高'],rule:'其中 giới hạn nhóm con: tám người thuộc mười hai người ở gần, không phải tám người ngoài nhóm. 愿意 là sẵn lòng, không bằng đã thực hiện. 没有…而是… nêu phương án thay thế; 先…再… là kế hoạch thử và đo.',pitfall:'Không cộng 12+8 thành 20 người ở gần. Không nói giải pháp đã có hiệu quả hoặc kết quả khảo sát đúng cho toàn thành phố.',question:'Tám người trong bài thuộc nhóm nào?',choices:[['住得不远的十二位同事中。','Đúng: 其中 chỉ nhóm con của 12 người ở gần.'],['住得很远的同事中。','Sai: nhóm được nhắc là người ở gần.'],['全城所有骑车的人中。','Khảo sát chỉ có 20 đồng nghiệp.']],answer:0,cloze:{prompt:'Điền liên từ lựa chọn: 下雨时，可以坐公共汽车___地铁。',answer:'或者',feedback:'或者 nối hai lựa chọn trong câu trần thuật, không khẳng định đi cả hai.'},transfer:'Khảo sát 10 người: 6 người ở gần, trong đó 4 muốn đi bộ nhưng lo vỉa hè tối. Đề xuất thêm đèn, tháng sau mới đếm người đi bộ. Viết 4 câu giữ nhóm con và phân biệt đề xuất/kết quả.',model:['调查中有十个人，六个人住得近。这六个人中，四个人想走路，可是担心路上太暗。大家建议增加路灯。下个月才统计走路的人数，现在还不知道效果。','Diàochá zhōng yǒu shí ge rén, liù ge rén zhù de jìn. Zhè liù ge rén zhōng, sì ge rén xiǎng zǒu lù, kěshì dānxīn lù shàng tài àn. Dàjiā jiànyì zēngjiā lùdēng. Xià ge yuè cái tǒngjì zǒu lù de rénshù, xiànzài hái bù zhīdào xiàoguǒ.','Khảo sát có 10 người, 6 ở gần. Trong 6 người, 4 muốn đi bộ nhưng lo đường tối. Mọi người đề xuất thêm đèn. Tháng sau mới thống kê người đi bộ, hiện chưa biết hiệu quả.'],criteria:['4 là nhóm con của 6 trong tổng 10.','Giải pháp đèn gắn trở ngại đường tối.','Chưa tuyên bố số người đi bộ đã tăng.']},
 {suffix:'landscape-place',scene:'hsk3-mountain-town',goal:'Giới thiệu cảnh quan theo mốc và bốn hướng cố định',support:'观景台 guānjǐngtái — đài ngắm cảnh; 入口 rùkǒu — lối vào; 方位 fāngwèi — phương hướng. Bản đồ giả định quy ước bắc ở trên, không theo hướng người đang đứng.',paragraphs:[
 ['这座山城的游客中心在地图中间。地图上方是北方，下方是南方，左边是西方，右边是东方。先找到中心，再看周围的地点。','Zhè zuò shānchéng de yóukè zhōngxīn zài dìtú zhōngjiān. Dìtú shàngfāng shì běifāng, xiàfāng shì nánfāng, zuǒbian shì xīfāng, yòubian shì dōngfāng. Xiān zhǎodào zhōngxīn, zài kàn zhōuwéi de dìdiǎn.','Trung tâm du khách nằm giữa bản đồ thành phố núi. Trên là bắc, dưới nam, trái tây, phải đông. Tìm trung tâm trước rồi xem địa điểm xung quanh.'],
 ['游客中心北边是一座山，南边是一条老街。东边有花园，西边有湖。天气好时，游客常到花园散步。','Yóukè zhōngxīn běibian shì yí zuò shān, nánbian shì yì tiáo lǎo jiē. Dōngbian yǒu huāyuán, xībian yǒu hú. Tiānqì hǎo shí, yóukè cháng dào huāyuán sànbù.','Phía bắc trung tâm là núi, nam là phố cổ, đông có vườn hoa, tây có hồ. Khi đẹp trời, du khách thường đi dạo trong vườn.'],
 ['小周想先看花，再去湖边。他从游客中心向东走，到花园以后，先回到中心，再向西去湖边。','Xiǎo Zhōu xiǎng xiān kàn huā, zài qù húbiān. Tā cóng yóukè zhōngxīn xiàng dōng zǒu, dào huāyuán yǐhòu, xiān huí dào zhōngxīn, zài xiàng xī qù húbiān.','Tiểu Chu muốn xem hoa rồi ra hồ. Anh từ trung tâm đi đông tới vườn, sau đó trở về trung tâm rồi đi tây tới hồ.'],
 ['工作人员提醒他，地图只说明方向，没有写距离和路况。下雨时能不能上山，还要查看当天的通知，不能只看地图决定。','Gōngzuò rényuán tíxǐng tā, dìtú zhǐ shuōmíng fāngxiàng, méiyǒu xiě jùlí hé lùkuàng. Xià yǔ shí néng bù néng shàng shān, hái yào chákàn dàngtiān de tōngzhī, bù néng zhǐ kàn dìtú juédìng.','Nhân viên nhắc bản đồ chỉ nêu hướng, không ghi khoảng cách hay tình trạng đường. Trời mưa có lên núi được không phải xem thông báo ngày đó, không quyết định chỉ từ bản đồ.'],
 ],core:['地图','中间','北方','南方','东方','西方','花园','方向'],rule:'以游客中心为参照: mọi vị trí được nói so với trung tâm. 在…东边 mô tả vị trí, 向东走 mô tả chuyển động. Khi quay người, đông/tây không đổi theo tay trái/phải của mình. Không suy khoảng cách từ sơ đồ không có tỷ lệ.',pitfall:'Đi tây từ vườn trở về trung tâm trước, không nói vườn ở phía tây. Bản đồ không cho biết đường lên núi đang mở.',question:'Từ trung tâm muốn tới vườn hoa phải đi hướng nào?',choices:[['向西走。','Tây là hướng hồ.'],['向东走。','Đúng: vườn ở phía đông trung tâm.'],['向北走。','Bắc là hướng núi.']],answer:1,cloze:{prompt:'Điền giới từ chỉ hướng di chuyển: 从中心___东走。',answer:'向',feedback:'向 đứng trước hướng di chuyển; 在 chỉ vị trí, không thay 向 trong câu này.'},transfer:'Bản đồ mới, vẫn bắc ở trên: trung tâm giữa; bắc có hồ, nam có vườn, đông có phố cổ, tây có núi. Viết 5 câu giới thiệu đủ bốn hướng và một lộ trình từ trung tâm; chưa có dữ liệu độ dài đường.',model:['游客中心北边有湖，南边有花园。东边是一条老街。西边是一座山。想去花园，可以从中心向南走。地图没有说明距离。','Yóukè zhōngxīn běibian yǒu hú, nánbian yǒu huāyuán. Dōngbian shì yì tiáo lǎo jiē. Xībian shì yí zuò shān. Xiǎng qù huāyuán, kěyǐ cóng zhōngxīn xiàng nán zǒu. Dìtú méiyǒu shuōmíng jùlí.','Bắc trung tâm có hồ, nam có vườn. Đông là phố cổ. Tây là núi. Muốn đến vườn có thể đi nam từ trung tâm. Bản đồ không nêu khoảng cách.'],criteria:['Đúng bốn hướng của bản đồ mới.','Hướng đi dùng cùng mốc trung tâm.','Không thêm số mét hoặc thời gian đi.']},
 {suffix:'plants-animals',scene:'hsk3-community-garden',goal:'Theo dõi cách tạo vườn học tập và giới hạn của quan sát',support:'种植 zhòngzhí — trồng; 浇水 jiāo shuǐ — tưới; 泥土 nítǔ — đất; 昆虫 kūnchóng — côn trùng; 观察 guānchá — quan sát; 移动 yídòng — di chuyển.',paragraphs:[
 ['假期开始时，社区准备把一块空地变成学习花园。大人先搬走旧东西，孩子们画图，标出种树和种花的地方。','Jiàqī kāishǐ shí, shèqū zhǔnbèi bǎ yí kuài kòngdì biànchéng xuéxí huāyuán. Dàrén xiān bān zǒu jiù dōngxi, háizimen huà tú, biāo chū zhòng shù hé zhòng huā de dìfang.','Đầu kỳ nghỉ, cộng đồng định biến đất trống thành vườn học tập. Người lớn dọn đồ cũ, trẻ vẽ sơ đồ đánh dấu nơi trồng cây và hoa.'],
 ['大家查了植物需要的阳光和水，再决定种在哪里。有人以为每天多浇水就好，老师解释，不同植物需要的水不一样。','Dàjiā chá le zhíwù xūyào de yángguāng hé shuǐ, zài juédìng zhòng zài nǎlǐ. Yǒu rén yǐwéi měi tiān duō jiāo shuǐ jiù hǎo, lǎoshī jiěshì, bùtóng zhíwù xūyào de shuǐ bù yíyàng.','Mọi người tra nhu cầu nắng và nước của cây rồi chọn chỗ trồng. Có người tưởng cứ tưới nhiều mỗi ngày là tốt; giáo viên giải thích mỗi loại cần lượng nước khác nhau.'],
 ['种好以后，孩子们每周记下植物的变化，也观察树边的小动物。他们只在旁边看，不随便移动动物，让它们留在原来的地方。','Zhòng hǎo yǐhòu, háizimen měi zhōu jì xià zhíwù de biànhuà, yě guānchá shù biān de xiǎo dòngwù. Tāmen zhǐ zài pángbiān kàn, bù suíbiàn yídòng dòngwù, ràng tāmen liú zài yuánlái de dìfang.','Trồng xong, trẻ ghi thay đổi mỗi tuần và quan sát động vật nhỏ cạnh cây. Các em chỉ xem bên cạnh, không tùy tiện di chuyển, để chúng ở nơi ban đầu.'],
 ['两周后，有些花开了，有些还没有开。孩子们发现，花园不是种完就不用管。他们还要继续记录，不能只看一天就说哪种办法最好。','Liǎng zhōu hòu, yǒuxiē huā kāi le, yǒuxiē hái méiyǒu kāi. Háizimen fāxiàn, huāyuán bú shì zhòng wán jiù bú yòng guǎn. Tāmen hái yào jìxù jìlù, bù néng zhǐ kàn yì tiān jiù shuō nǎ zhǒng bànfǎ zuì hǎo.','Sau hai tuần, một số hoa nở, một số chưa. Trẻ nhận ra trồng xong vẫn cần chăm. Các em phải tiếp tục ghi nhận, không chỉ xem một ngày rồi kết luận cách nào tốt nhất.'],
 ],core:['假期','大人','搬','树','以为','不同','动物','发现'],rule:'先…再… tổ chức chuẩn bị trước quyết định. 以为 nói nhận định cần sửa, không phải sự thật được xác nhận. 有些…有些… giữ khác biệt trong nhóm. 种好/种完 biểu thị hoàn thành trồng, không hoàn thành mọi chăm sóc.',pitfall:'Không nói tất cả hoa đều nở hoặc tưới càng nhiều càng tốt. Hai tuần quan sát không chứng minh một cách chăm phù hợp mọi loài.',question:'Điều gì đã được quan sát sau hai tuần?',choices:[['所有的花都开了。','Sai: một số chưa nở.'],['有些花开了，有些还没有开。','Đúng: kết quả khác nhau giữa các cây.'],['以后完全不用照顾花园了。','Sai: cần tiếp tục chăm và ghi nhận.']],answer:1,cloze:{prompt:'Điền từ thể hiện nhận định trước đây chưa đúng: 他___每天多浇水就好，后来才知道要看植物的需要。',answer:'以为',feedback:'以为 đặt niềm tin ban đầu trước thông tin sửa lại về nhu cầu từng cây.'},transfer:'Nhóm mới trồng 6 cây. Sau một tuần, 4 cây có lá mới, 2 cây chưa; nhóm chưa biết lý do. Họ định ghi ánh sáng và nước thêm một tuần, không tự tăng nước cho mọi cây. Viết 4 câu.',model:['小组种了六棵植物。一周后，四棵长出了新叶，两棵还没有。大家还不知道原因。他们准备再记录一周的阳光和水量，不给所有植物都增加水。','Xiǎozǔ zhòng le liù kē zhíwù. Yì zhōu hòu, sì kē zhǎng chū le xīn yè, liǎng kē hái méiyǒu. Dàjiā hái bù zhīdào yuányīn. Tāmen zhǔnbèi zài jìlù yì zhōu de yángguāng hé shuǐliàng, bù gěi suǒyǒu zhíwù dōu zēngjiā shuǐ.','Nhóm trồng sáu cây. Sau một tuần, bốn có lá mới, hai chưa. Mọi người chưa biết lý do. Họ định ghi nắng và lượng nước thêm một tuần, không tăng nước đồng loạt.'],criteria:['4+2=6, thời gian một tuần.','Chưa biết nguyên nhân, không tự chẩn đoán.','Kế hoạch ghi thêm chưa được thực hiện.']},
];

