import {readFileSync} from 'node:fs';
import type {PersonalNarrative} from './hsk3-personal-narratives';

type Sentence=[string,string,string];
const source=JSON.parse(readFileSync('content/drafts/hsk3-modality-time-narration-grammar-2026.07.json','utf8')) as {lessons:Array<{lessonId:string;modelNarration:{lines:Array<{hanzi:string;pinyin:string;vietnamese:string}>}}>} ;
const corrections:Record<string,Record<number,Sentence>>={
 'lesson-01':{5:['离开诊室以后，我们向南门慢慢走去，准备坐车回家。','Líkāi zhěnshì yǐhòu, wǒmen xiàng nánmén mànmàn zǒu qù, zhǔnbèi zuò chē huí jiā.','Rời phòng khám, chúng tôi đi chậm về phía cổng nam, chuẩn bị đi xe về nhà.']},
 'lesson-02':{
  3:['在老师看来，错误是学习过程的一部分；对我来说，坚持最难。','Zài lǎoshī kànlái, cuòwù shì xuéxí guòchéng de yí bùfen; duì wǒ láishuō, jiānchí zuì nán.','Theo thầy, lỗi là một phần của quá trình học; với tôi, kiên trì là khó nhất.'],
  4:['一般来说，短时间多次复习比一次学很久更容易坚持。','Yìbān láishuō, duǎn shíjiān duō cì fùxí bǐ yí cì xué hěn jiǔ gèng róngyì jiānchí.','Nói chung, ôn nhiều lần ngắn dễ duy trì hơn học một lần quá lâu.'],
 },
 'lesson-03':{
  1:['这次回来前的几天，他一个电话也没打，妈妈却一点儿也不生气。','Zhè cì huílai qián de jǐ tiān, tā yí ge diànhuà yě méi dǎ, māma què yìdiǎnr yě bù shēngqì.','Trong mấy ngày trước lần về này, anh không gọi cuộc nào, nhưng mẹ không hề giận.'],
  5:['我是支持哥哥去外地工作的，家人也愿意听完他的计划。','Wǒ shì zhīchí gēge qù wàidì gōngzuò de, jiārén yě yuànyì tīngwán tā de jìhuà.','Tôi ủng hộ việc anh đi làm xa; gia đình cũng sẵn lòng nghe hết kế hoạch của anh.'],
 },
};
const paragraphs=(suffix:string):Sentence[]=>source.lessons.find(lesson=>lesson.lessonId.endsWith(suffix))!.modelNarration.lines.map((line,index)=>corrections[suffix]?.[index]??[line.hanzi,line.pinyin,line.vietnamese]);

export const modalityNarratives:PersonalNarrative[]=[
  {suffix:'lesson-01',goal:'Đọc lời kể đi khám và phân biệt triệu chứng, lời khuyên, điều bắt buộc và việc không còn cần làm',support:'需要 xūyào — cần; 愿意 yuànyì — sẵn lòng; 必须 bìxū — bắt buộc; 应该 yīnggāi — nên; 不必 búbì — không cần. Đây là truyện giả định để học ngôn ngữ, không phải lời khuyên y tế.',paragraphs:paragraphs('lesson-01'),core:['总是','担心','检查','愿意','必须','不用'],rule:'好像有些累 là nhận xét có vẻ mệt, không phải chẩn đoán. 医生说…必须… là chỉ dẫn được người kể thuật lại; 应该 là lời khuyên. 不用/不必 bỏ yêu cầu, không phải cấm làm. 向家人说明 là nói với gia đình; 向南门走去 chỉ hướng đi, chưa tự chứng minh đã qua cổng.',pitfall:'Đừng biến “kết quả tương đối tốt” thành khỏi bệnh hoàn toàn; cũng đừng biến “đi về phía cổng nam” thành đã về tới nhà. Câu chuyện không cho biết bệnh gì hoặc tên thuốc.',question:'Kết luận nào giữ đúng điều bác sĩ nói?',choices:[['奶奶必须按时吃药，也应该多休息。','Đúng: uống thuốc đúng giờ là yêu cầu, nghỉ nhiều là lời khuyên.'],['奶奶不能再吃药。','Sai: không có lệnh cấm uống thuốc.'],['奶奶已经完全好了。','Sai: kết quả tương đối tốt không chứng minh khỏi hoàn toàn.']],answer:0,cloze:{prompt:'Bác sĩ nói gia đình không cần chuẩn bị đồ quá ngọt. Điền: 家人___准备特别甜的东西。',answer:'不用',feedback:'不用 gỡ bỏ việc cần chuẩn bị; 不能 sẽ thành cấm đoán.'},transfer:'Cảnh khác: Tiểu Minh gần đây ngủ không ngon; chị sẵn lòng đi khám cùng. Bác sĩ khuyên cậu nghỉ ngơi, dặn phải uống thuốc đúng giờ. Sau khám, chị nói cả hai không cần xếp hàng nữa. Viết 4 câu; giữ khác biệt giữa khuyên, bắt buộc và không cần.',model:['小明最近睡不好，姐姐愿意陪他去医院。医生说他应该多休息，必须按时吃药。检查以后，姐姐告诉他不用再排队了。','Xiǎo Míng zuìjìn shuì bu hǎo, jiějie yuànyì péi tā qù yīyuàn. Yīshēng shuō tā yīnggāi duō xiūxi, bìxū ànshí chī yào. Jiǎnchá yǐhòu, jiějie gàosu tā búyòng zài páiduì le.','Gần đây Tiểu Minh ngủ không ngon, chị sẵn lòng đi bệnh viện cùng. Bác sĩ nói cậu nên nghỉ nhiều và phải uống thuốc đúng giờ. Khám xong, chị bảo cậu không cần xếp hàng nữa.'],criteria:['Chị sẵn lòng đi cùng, không biến thành yêu cầu.','应该 là lời khuyên; 必须 là việc bắt buộc trong câu chuyện.','不用 là không cần xếp hàng, không phải bị cấm.']},
  {suffix:'lesson-02',goal:'Tách mục đích, căn cứ, điều kiện và góc nhìn trong một kế hoạch học nghe',support:'为了 wèile — để; 根据 gēnjù — dựa theo; …的话 dehuà — nếu; 看来 kànlái — xem ra; 在…看来 — theo góc nhìn của; 对…来说 — đối với. Một tháng kết quả tăng là dữ kiện của nhân vật, không là cam kết học tập.',paragraphs:paragraphs('lesson-02'),core:['根据','新闻','声音','坚持','复习','看来'],rule:'为了提高听力 nêu mục đích; 根据老师的建议 nêu căn cứ lập kế hoạch. 有时间的话 là điều kiện để kể lại, không phải ngày nào cũng đã kể. 在老师看来 là ý thầy; 对我来说 là trải nghiệm người kể. 一般来说 là khái quát có ngoại lệ; 看来 ở cuối là kết luận từ kết quả cá nhân.',pitfall:'Đừng biến lời thầy thành sự thật tuyệt đối hay nói người kể đã kể lại tin mỗi ngày. “Kết quả tăng” không chứng minh phương pháp phù hợp mọi người; văn bản chỉ đánh giá cho nhân vật này.',question:'Điều nào là bước chắc chắn trong kế hoạch từ hôm nay?',choices:[['每天听一段新闻。','Đúng: người kể dự định nghe một đoạn tin mỗi ngày.'],['每天一定复述新闻。','Sai: chỉ kể lại nếu có thời gian.'],['老师每天帮他听新闻。','Sai: thầy đưa lời khuyên, không có bước nghe cùng mỗi ngày.']],answer:0,cloze:{prompt:'Điền dấu điều kiện: 有时间___，我再说一遍内容。',answer:'的话',feedback:'的话 gắn sau 有时间; việc kể lại tùy có thời gian.'},transfer:'Lan muốn luyện đọc: để đọc tốt hơn, cô dựa theo góp ý của thầy chia bài thành hai phần. Từ thứ Hai, cô đọc một đoạn ngắn mỗi ngày; nếu có thời gian thì viết tóm tắt. Sau một tuần cô đọc nhanh hơn và chỉ kết luận kế hoạch này hợp với mình. Viết 4–5 câu, phân biệt mục đích, điều kiện và nhận định cá nhân.',model:['为了提高阅读能力，小兰根据老师的建议把文章分成两部分。从星期一起，她每天读一小段，有时间的话就写一个小总结。一周后，她读得快了一些。看来这个计划适合她。','Wèile tígāo yuèdú nénglì, Xiǎo Lán gēnjù lǎoshī de jiànyì bǎ wénzhāng fēn chéng liǎng bùfen. Cóng Xīngqīyī qǐ, tā měitiān dú yì xiǎo duàn, yǒu shíjiān dehuà jiù xiě yí ge xiǎo zǒngjié. Yì zhōu hòu, tā dú de kuài le yìxiē. Kànlái zhège jìhuà shìhé tā.','Để nâng khả năng đọc, Lan dựa theo góp ý của thầy chia bài thành hai phần. Từ thứ Hai cô đọc một đoạn ngắn mỗi ngày, có thời gian thì viết tóm tắt. Một tuần sau cô đọc nhanh hơn một chút. Xem ra kế hoạch hợp với cô.'],criteria:['Nêu rõ mục đích và căn cứ khác nhau.','Viết tóm tắt là bước có điều kiện.','Kết luận chỉ áp cho Lan, không khái quát mọi người.']},
  {suffix:'lesson-03',goal:'Kể lại mốc trở về và phân biệt phủ định hoàn toàn, lời trấn an và thái độ ủng hộ',support:'一个…也没 — dù một… cũng không; 一点儿也不 — không hề; …以前/以后 — trước/sau; 该…了 — đã đến lúc; 不是…吗 — câu hỏi nhắc lại điều đã biết. Lời thoại trong gia đình là tình huống giả định.',paragraphs:paragraphs('lesson-03'),core:['离开','担心','生气','欢迎','怎样','选择'],rule:'一个电话也没打 nói về mấy ngày trước lần về này; không suy rằng ba năm hoàn toàn không liên lạc. 一点儿也不生气 phủ định mức giận. 担心什么啊 là lời trấn an thân mật, không phải hỏi nguyên nhân. 不是…吗 nhắc lại tin đã biết. 是支持…的 nhấn thái độ của người kể, không khẳng định mọi người cùng ý.',pitfall:'Không gán lời trấn an của bố cho mẹ hoặc biến mẹ không giận thành chưa từng lo lắng. 哥哥离开家三年了 là mốc ba năm đến hiện tại trong truyện, không phải ba năm chuyến đi lần này.',question:'Trong mấy ngày trước lần về này, người anh đã làm gì theo văn bản?',choices:[['一个电话也没打。','Đúng: trong mấy ngày đó anh không gọi cuộc nào.'],['每天都给家里打电话。','Sai: trái với câu phủ định trong khoảng đã nêu.'],['妈妈一点儿也不担心。','Sai: văn bản chỉ nói mẹ không giận, không nêu mẹ có lo hay không.']],answer:0,cloze:{prompt:'Điền dấu phủ định toàn bộ: 这次回来前的几天，他一个电话___没打。',answer:'也',feedback:'一个…也没… nhấn mạnh không có dù một cuộc gọi trong mấy ngày đó.'},transfer:'Một chuyện mới: chị gái đi học xa hai năm rồi về vào chiều thứ Bảy. Trong mấy ngày trước lần về này chị không gửi một tin nhắn nào; bố không hề giận. Trời tối, cả nhà đến lúc ra ga đón; em nói mình ủng hộ quyết định học xa của chị. Viết 4–5 câu, giữ đúng phạm vi thời gian và thái độ từng người.',model:['姐姐离开家两年了，星期六下午回来。这次回来前的几天，她一条消息也没发。爸爸一点儿也不生气。天黑了，我们该去车站接她了。我是支持姐姐去外地学习的。','Jiějie líkāi jiā liǎng nián le, Xīngqīliù xiàwǔ huílai. Zhè cì huílai qián de jǐ tiān, tā yì tiáo xiāoxi yě méi fā. Bàba yìdiǎnr yě bù shēngqì. Tiān hēi le, wǒmen gāi qù chēzhàn jiē tā le. Wǒ shì zhīchí jiějie qù wàidì xuéxí de.','Chị gái rời nhà đã hai năm và về chiều thứ Bảy. Trong mấy ngày trước lần về này chị không gửi tin nào. Bố không hề giận. Trời tối, cả nhà đã đến lúc ra ga đón. Em thực sự ủng hộ chị học xa.'],criteria:['Hai năm là khoảng rời nhà, không phải thời gian đi ga.','一条消息也没发 chỉ mấy ngày trước lần về này.','Không gán thái độ của bố cho mọi người; nêu rõ thái độ của em.']},
];
