import type {PersonalNarrative} from './hsk3-personal-narratives';

export const eventNarratives:PersonalNarrative[]=[
 {suffix:'lesson-01',goal:'Kể đúng thứ tự làm dự án và phân biệt khả năng hoàn thành với phần đã làm xong',support:'组长 zǔzhǎng — trưởng nhóm; 报告 bàogào — báo cáo; 重点 zhòngdiǎn — điểm chính; 听懂 tīngdǒng — nghe hiểu; 完得成 wán de chéng — hoàn thành được. Dự án và nhân vật là giả định.',paragraphs:[
  ['放假前，我们见了两次面，讨论班级项目。','Fàngjià qián, wǒmen jiàn le liǎng cì miàn, tǎolùn bānjí xiàngmù.','Trước kỳ nghỉ, chúng tôi gặp nhau hai lần để bàn dự án của lớp.'],
  ['第一次，大家没听懂要求，老师又说明了一遍。','Dì yī cì, dàjiā méi tīngdǒng yāoqiú, lǎoshī yòu shuōmíng le yí biàn.','Lần đầu mọi người chưa nghe hiểu yêu cầu, thầy giải thích thêm một lượt.'],
  ['组长看出了问题，想起上次的办法，把重点记了下来。','Zǔzhǎng kànchū le wèntí, xiǎngqǐ shàng cì de bànfǎ, bǎ zhòngdiǎn jì le xiàlai.','Trưởng nhóm nhận ra vấn đề, nhớ ra cách làm lần trước và ghi lại điểm chính.'],
  ['第二次见面时，我们把第一部分写完了。组长说：“剩下的不多，明天完得成。”','Dì èr cì jiànmiàn shí, wǒmen bǎ dì yī bùfen xiěwán le. Zǔzhǎng shuō: “Shèngxià de bù duō, míngtiān wán de chéng.”','Ở buổi gặp thứ hai, chúng tôi viết xong phần đầu. Trưởng nhóm nói: “Phần còn lại không nhiều, ngày mai làm xong được.”'],
  ['旧文件被老师拿走了，新报告被放在桌子上。大家终于听懂了全部要求。','Jiù wénjiàn bèi lǎoshī názǒu le, xīn bàogào bèi fàng zài zhuōzi shàng. Dàjiā zhōngyú tīngdǒng le quánbù yāoqiú.','Tài liệu cũ được thầy mang đi, báo cáo mới được đặt trên bàn. Cuối cùng mọi người đã nghe hiểu toàn bộ yêu cầu.'],
  ['离开教室以前，我们关上了窗户，也记住了交作业的时间。','Líkāi jiàoshì yǐqián, wǒmen guānshàng le chuānghu, yě jìzhù le jiāo zuòyè de shíjiān.','Trước khi rời lớp, chúng tôi đóng cửa sổ và ghi nhớ thời gian nộp bài.'],
 ],core:['放假','要求','办法','终于','旧','以前'],rule:'见了两次面 đặt số lần giữa động từ 见 và tân tố 面. 听懂/写完 nêu kết quả; 完得成 là khả năng đạt kết quả trong điều kiện được nói, chưa xác nhận đã làm xong. 把第一部分写完了 nêu phần chịu xử lý; 旧文件被老师拿走了 đổi góc nhìn sang vật chịu tác động. 看出/想起/记下来 là nhận ra/nhớ ra/ghi lại, không phải chuyển động vật lý.',pitfall:'Đã viết xong phần đầu không phải xong toàn dự án. 明天完得成 là nhận định của trưởng nhóm về ngày mai. Câu bị động lược người đặt báo cáo, không được đoán người đặt là thầy.',question:'Sau buổi gặp thứ hai, điều gì đã được văn bản xác nhận?',choices:[['第一部分写完了。','Đúng: phần đầu đã viết xong.'],['整个项目已经完成了。','Sai: phần còn lại mới được dự đoán làm xong ngày mai.'],['老师把新报告放在桌上了。','Sai: câu chỉ nói báo cáo được đặt lên bàn, không nêu ai đặt.']],answer:0,cloze:{prompt:'Điền kết quả nghe hiểu: 老师说明以后，我们终于听___了要求。',answer:'懂',feedback:'听懂 là đạt kết quả hiểu; chỉ 听了 không đảm bảo đã hiểu.'},transfer:'Nhóm Mai gặp nhau ba lần để làm bài. Ban đầu chưa hiểu yêu cầu; sau khi thầy giải thích, nhóm ghi lại điểm chính. Hôm nay viết xong phần thứ hai; trưởng nhóm cho rằng ngày mai làm xong phần còn lại được. Viết 4–5 câu, giữ rõ kết quả đã đạt và khả năng tương lai.',model:['小梅和同学见了三次面。刚开始，他们没听懂要求。老师说明以后，他们把重点记了下来。今天，他们把第二部分写完了。组长觉得剩下的明天完得成。','Xiǎo Méi hé tóngxué jiàn le sān cì miàn. Gāng kāishǐ, tāmen méi tīngdǒng yāoqiú. Lǎoshī shuōmíng yǐhòu, tāmen bǎ zhòngdiǎn jì le xiàlai. Jīntiān, tāmen bǎ dì èr bùfen xiěwán le. Zǔzhǎng juéde shèngxià de míngtiān wán de chéng.','Mai và các bạn gặp nhau ba lần. Lúc đầu họ chưa nghe hiểu yêu cầu. Sau khi thầy giải thích, họ ghi lại điểm chính. Hôm nay họ viết xong phần thứ hai. Trưởng nhóm nghĩ phần còn lại ngày mai hoàn thành được.'],criteria:['Số lần đúng vị trí trong 见了三次面.','Phần hai đã xong; phần còn lại mới là khả năng.','Dùng bổ ngữ để nói rõ nghe hiểu và ghi lại.']},
 {suffix:'lesson-02',goal:'Theo dõi ai chuyển vật gì cho ai, ở đâu và kết quả tìm lại báo cáo',support:'钥匙 yàoshi — chìa khóa; 柜子 guìzi — tủ; 工作人员 gōngzuò rényuán — nhân viên; 找回来 zhǎo huílai — tìm lại được; 分工 fēngōng — phân công. Không đoán thủ phạm từ việc báo cáo bị thất lạc.',paragraphs:[
  ['发现报告不见了以后，大家马上讨论起来。','Fāxiàn bàogào bú jiàn le yǐhòu, dàjiā mǎshàng tǎolùn qǐlai.','Sau khi phát hiện không thấy báo cáo, mọi người lập tức bắt đầu thảo luận.'],
  ['组长的声音太小，后面的同学听不清。大家请他大声一点儿，再讨论下去。','Zǔzhǎng de shēngyīn tài xiǎo, hòumian de tóngxué tīng bu qīng. Dàjiā qǐng tā dàshēng yìdiǎnr, zài tǎolùn xiàqu.','Giọng trưởng nhóm quá nhỏ, các bạn phía sau nghe không rõ. Mọi người nhờ cậu nói to hơn rồi tiếp tục thảo luận.'],
  ['小林把旧文件放在老师的桌子上，又把柜子的钥匙交给了工作人员。','Xiǎo Lín bǎ jiù wénjiàn fàng zài lǎoshī de zhuōzi shàng, yòu bǎ guìzi de yàoshi jiāo gěi le gōngzuò rényuán.','Tiểu Lâm đặt tài liệu cũ lên bàn thầy, rồi giao chìa khóa tủ cho nhân viên.'],
  ['工作人员打开柜子，大家在里面找到了报告，终于把它拿回来了。','Gōngzuò rényuán dǎkāi guìzi, dàjiā zài lǐmian zhǎodào le bàogào, zhōngyú bǎ tā ná huílai le.','Nhân viên mở tủ. Mọi người tìm thấy báo cáo bên trong và cuối cùng mang nó trở lại.'],
  ['组长把经过写清楚了，也重新安排了检查工作。','Zǔzhǎng bǎ jīngguò xiě qīngchu le, yě chóngxīn ānpái le jiǎnchá gōngzuò.','Trưởng nhóm viết rõ diễn biến và sắp xếp lại việc kiểm tra.'],
  ['从那以后，大家每次离开教室前都检查文件。这个习惯一直坚持了下来。','Cóng nà yǐhòu, dàjiā měi cì líkāi jiàoshì qián dōu jiǎnchá wénjiàn. Zhège xíguàn yìzhí jiānchí le xiàlai.','Từ đó, mỗi lần rời lớp mọi người đều kiểm tra tài liệu. Thói quen ấy được duy trì đến nay.'],
 ],core:['发现','不见','声音','清楚','经过','坚持'],rule:'讨论起来 đánh dấu bắt đầu; 讨论下去 là tiếp tục từ thời điểm đó; 坚持下来 nhìn lại việc đã duy trì. 听不清 mô tả không đạt kết quả nghe rõ trong điều kiện âm lượng nhỏ. 把旧文件放在桌子上 nêu vật và vị trí; 把钥匙交给工作人员 nêu vật và người nhận; 把它拿回来 nêu kết quả hướng trở về.',pitfall:'Tiểu Lâm giao chìa khóa, không giao báo cáo cho nhân viên. Báo cáo được tìm trong tủ, không trên bàn thầy. Văn bản không nói ai cất báo cáo vào tủ hoặc có hành vi trộm cắp.',question:'Tiểu Lâm đã giao vật gì cho nhân viên?',choices:[['柜子的钥匙。','Đúng: chìa khóa tủ được giao cho nhân viên.'],['老师桌上的旧文件。','Sai: tài liệu cũ được đặt trên bàn thầy.'],['已经找到的报告。','Sai: báo cáo chỉ được tìm thấy sau khi nhân viên mở tủ.']],answer:0,cloze:{prompt:'Điền người nhận theo đúng văn bản: 小林把钥匙交给了___。',answer:'工作人员',feedback:'Người nhận chìa khóa là nhân viên; 把 đặt vật trước động từ, 给 dẫn người nhận.'},transfer:'Một nhóm khác không thấy bản đồ. Lan đặt sách lên bàn rồi giao chìa khóa phòng cho cô giáo. Cô mở phòng, nhóm tìm thấy và mang bản đồ trở lại. Từ đó họ luôn kiểm tra bản đồ trước khi đi. Viết 4–5 câu, không tự thêm người làm thất lạc.',model:['大家发现地图不见了，就讨论起来。小兰把书放在桌子上，再把钥匙交给老师。老师打开房间以后，大家找到了地图，把它拿回来了。从那以后，大家每次出发前都检查地图。','Dàjiā fāxiàn dìtú bú jiàn le, jiù tǎolùn qǐlai. Xiǎo Lán bǎ shū fàng zài zhuōzi shàng, zài bǎ yàoshi jiāo gěi lǎoshī. Lǎoshī dǎkāi fángjiān yǐhòu, dàjiā zhǎodào le dìtú, bǎ tā ná huílai le. Cóng nà yǐhòu, dàjiā měi cì chūfā qián dōu jiǎnchá dìtú.','Nhóm không thấy bản đồ nên bắt đầu thảo luận. Lan đặt sách lên bàn rồi giao chìa khóa cho cô giáo. Cô mở phòng, cả nhóm tìm được bản đồ và mang trở lại. Từ đó họ kiểm tra bản đồ trước mỗi lần đi.'],criteria:['Sách lên bàn; chìa khóa tới cô giáo, không đảo hai vật.','Mở phòng rồi mới tìm được bản đồ.','Không tự kết luận ai làm mất hoặc giấu bản đồ.']},
 {suffix:'lesson-03',goal:'Kể một tuần thực tập, giữ đúng tác nhân, số lần và hành động diễn ra đồng thời',support:'实习 shíxí — thực tập; 实习生 shíxíshēng — thực tập sinh; 客户 kèhù — khách hàng; 拿着 názhe — đang cầm; 被 bèi — đánh dấu bị động. Không suy lý do nghỉ việc hay đánh giá năng lực từ số lần sửa.',paragraphs:[
  ['实习第一天，我的报告被经理改了三次。','Shíxí dì yī tiān, wǒ de bàogào bèi jīnglǐ gǎi le sān cì.','Ngày thực tập đầu tiên, báo cáo của tôi được quản lý sửa ba lần.'],
  ['下午，办公室的门被关上了。经理拿着文件走进会议室。','Xiàwǔ, bàngōngshì de mén bèi guānshàng le. Jīnglǐ názhe wénjiàn zǒujìn huìyìshì.','Buổi chiều, cửa văn phòng được đóng lại. Quản lý cầm tài liệu bước vào phòng họp.'],
  ['会议室里走进来了一位新客户，大家都站起来欢迎他。','Huìyìshì lǐ zǒu jìnlai le yí wèi xīn kèhù, dàjiā dōu zhàn qǐlai huānyíng tā.','Một khách hàng mới bước vào phòng họp, mọi người đều đứng lên chào.'],
  ['这一周，我写报告写得很认真，也写得越来越快。','Zhè yì zhōu, wǒ xiě bàogào xiě de hěn rènzhēn, yě xiě de yuèláiyuè kuài.','Trong tuần này, tôi viết báo cáo rất cẩn thận và ngày càng nhanh hơn.'],
  ['一周后，项目结束了，公司里走了两名实习生。','Yì zhōu hòu, xiàngmù jiéshù le, gōngsī lǐ zǒu le liǎng míng shíxíshēng.','Một tuần sau, dự án kết thúc, hai thực tập sinh rời công ty.'],
  ['我被安排负责新任务，也更明白自己的责任了。','Wǒ bèi ānpái fùzé xīn rènwu, yě gèng míngbai zìjǐ de zérèn le.','Tôi được giao phụ trách nhiệm vụ mới và hiểu rõ trách nhiệm của mình hơn.'],
 ],core:['经理','办公室','会议','欢迎','认真','结束'],rule:'报告被经理改了三次 nêu rõ người sửa là quản lý và số lần là ba. 门被关上了 lược tác nhân: không biết ai đóng. 拿着文件走进… diễn tả vừa cầm tài liệu vừa đi vào, không phải đặt tài liệu rồi mới đi. 会议室里走进来了一位… giới thiệu người mới xuất hiện; 公司里走了两名… nói người rời nơi đó. 写报告写得很认真 lặp động từ để gắn bổ ngữ sau tân ngữ.',pitfall:'Ba lần sửa không phải ba báo cáo khác nhau. Hai người rời công ty không tự có nghĩa bị sa thải; văn bản không nêu lý do. Không gán việc đóng cửa hoặc giao nhiệm vụ mới cho quản lý khi câu không nêu tác nhân.',question:'Ai đã sửa báo cáo và sửa mấy lần?',choices:[['经理改了三次。','Đúng: quản lý là tác nhân, ba là số lần sửa.'],['三位经理各改了一次。','Sai: ba là số lần, không phải số quản lý.'],['新客户改了两次。','Sai: khách chỉ xuất hiện trong phòng họp; hai là số thực tập sinh rời công ty.']],answer:0,cloze:{prompt:'Điền dấu hành động kèm: 经理拿___文件走进会议室。',answer:'着',feedback:'拿着文件 là trạng thái đi kèm khi bước vào; không phải hai việc trước–sau.'},transfer:'Ngày đầu làm việc, bản kế hoạch của Mai được cô Lý sửa hai lần. Cô Lý cầm bản đồ đi vào lớp; có hai học viên mới bước vào. Sau ba ngày, một học viên rời lớp, không rõ lý do. Mai viết ghi chú cẩn thận. Viết 4–5 câu, nêu đúng tác nhân, số lần và hành động đồng thời.',model:['第一天，小梅的计划被李老师改了两次。李老师拿着地图走进教室。教室里走进来了两名新同学。三天后，班里走了一名同学，原因还不清楚。小梅写笔记写得很认真。','Dì yī tiān, Xiǎo Méi de jìhuà bèi Lǐ lǎoshī gǎi le liǎng cì. Lǐ lǎoshī názhe dìtú zǒujìn jiàoshì. Jiàoshì lǐ zǒu jìnlai le liǎng míng xīn tóngxué. Sān tiān hòu, bān lǐ zǒu le yì míng tóngxué, yuányīn hái bù qīngchu. Xiǎo Méi xiě bǐjì xiě de hěn rènzhēn.','Ngày đầu, kế hoạch của Mai được cô Lý sửa hai lần. Cô Lý cầm bản đồ vào lớp. Hai học viên mới bước vào. Ba ngày sau một học viên rời lớp, lý do còn chưa rõ. Mai viết ghi chú cẩn thận.'],criteria:['Cô Lý sửa hai lần, không phải hai người sửa.','拿着 diễn tả cầm bản đồ trong khi đi vào.','Hai người vào, một người rời lớp; không bịa lý do rời.']},
];
