import {readFileSync} from 'node:fs';
import type {PersonalNarrative} from './hsk3-personal-narratives';
type Sentence=[string,string,string];
const source=JSON.parse(readFileSync('content/drafts/hsk3-discourse-linking-narration-grammar-2026.07.json','utf8')) as {lessons:Array<{lessonId:string;modelNarration:{lines:Array<{hanzi:string;pinyin:string;vietnamese:string}>}}>} ;
const changes:Record<string,Record<number,Sentence>>={
 'lesson-01':{0:['出发前，我们想：或者坐地铁，或者坐公共汽车去艺术节。','Chūfā qián, wǒmen xiǎng: huòzhě zuò dìtiě, huòzhě zuò gōnggòng qìchē qù yìshùjié.','Trước khi đi, chúng tôi tính: hoặc đi tàu điện, hoặc đi xe buýt tới liên hoan nghệ thuật.']},
 'lesson-02':{
  0:['社区篮球赛开始后，主队一会儿领先，一会儿又被追平。','Shèqū lánqiúsài kāishǐ hòu, zhǔduì yíhuìr lǐngxiān, yíhuìr yòu bèi zhuīpíng.','Sau khi trận bóng rổ khu phố bắt đầu, đội chủ nhà lúc dẫn trước, lúc lại bị gỡ hòa.'],
  3:['比赛以后，社区还安排了做菜活动。厨师一边准备菜，一边介绍家乡的做法。','Bǐsài yǐhòu, shèqū hái ānpái le zuò cài huódòng. Chúshī yìbiān zhǔnbèi cài, yìbiān jièshào jiāxiāng de zuòfǎ.','Sau trận, khu phố còn tổ chức hoạt động nấu ăn. Đầu bếp vừa chuẩn bị món vừa giới thiệu cách làm ở quê mình.'],
  4:['这道菜不但很香，而且还有一个节日故事。','Zhè dào cài bùdàn hěn xiāng, érqiě hái yǒu yí ge jiérì gùshi.','Món ăn không chỉ thơm mà còn có một câu chuyện lễ hội.'],
 },
 'lesson-03':{
  0:['第一次去这位朋友家做客的话，我们就先问清楚他家的习惯。','Dì yī cì qù zhè wèi péngyou jiā zuòkè dehuà, wǒmen jiù xiān wèn qīngchu tā jiā de xíguàn.','Nếu lần đầu đến nhà người bạn này, chúng tôi hỏi rõ nếp nhà của bạn trước.'],
  1:['为了表示尊重，我们提前问了合适的称呼和到达时间。','Wèile biǎoshì zūnzhòng, wǒmen tíqián wèn le héshì de chēnghu hé dàodá shíjiān.','Để thể hiện sự tôn trọng, chúng tôi hỏi trước cách xưng hô và giờ đến.'],
  2:['主人说：“只有收到邀请，才能参加这次家庭聚会。”','Zhǔrén shuō: “Zhǐyǒu shōudào yāoqǐng, cái néng cānjiā zhè cì jiātíng jùhuì.”','Chủ nhà nói: “Chỉ khi nhận được lời mời mới được tham gia buổi họp mặt gia đình này.”'],
  3:['他还说：“只要给我发消息，我就把菜单发给你。但收到菜单不等于收到邀请。”','Tā hái shuō: “Zhǐyào gěi wǒ fā xiāoxi, wǒ jiù bǎ càidān fā gěi nǐ. Dàn shōudào càidān bù děngyú shōudào yāoqǐng.”','Chủ nhà còn nói: “Chỉ cần nhắn cho tôi, tôi sẽ gửi thực đơn. Nhưng nhận thực đơn không đồng nghĩa nhận lời mời.”'],
  4:['我们收到邀请以后才去了朋友家。主人介绍了座位，我们就坐下了。','Wǒmen shōudào yāoqǐng yǐhòu cái qù le péngyou jiā. Zhǔrén jièshào le zuòwèi, wǒmen jiù zuòxia le.','Sau khi nhận lời mời chúng tôi mới đến nhà bạn. Chủ nhà giới thiệu chỗ ngồi rồi chúng tôi ngồi xuống.'],
 },
};
const p=(suffix:string):Sentence[]=>source.lessons.find(l=>l.lessonId.endsWith(suffix))!.modelNarration.lines.map((s,i)=>changes[suffix]?.[i]??[s.hanzi,s.pinyin,s.vietnamese]);
export const discourseNarratives:PersonalNarrative[]=[
 {suffix:'lesson-01',goal:'Giữ đúng lựa chọn, trình tự và phạm vi hoạt động trong một chuyến đi liên hoan',support:'艺术节 yìshùjié — liên hoan nghệ thuật; 取票 qǔpiào — lấy vé; 戏剧 xìjù — kịch; 交流 jiāoliú — giao lưu. Không có dữ kiện phương tiện cuối cùng đã chọn.',paragraphs:p('lesson-01'),core:['或者','先','然后','除了','表演','参加'],rule:'或者…或者… đưa các khả năng; không xác nhận đã dùng cả hai phương tiện. 先…然后… là hai bước trước–sau. 一边…一边… mô tả hai việc đồng thời. 除了音乐会以外…还有… bổ sung múa và kịch ngoài hòa nhạc. 如果…就… cho khả năng theo điều kiện, chưa nói người kể đã tham gia giao lưu.',pitfall:'Danh mục có nhiều hoạt động nhưng nhóm chỉ dự hai; văn bản không cho biết chính xác hai hoạt động nào. Không suy đã đi tàu điện từ việc nó được nêu đầu tiên.',question:'Từ câu dùng 或者…或者…, có thể kết luận gì về phương tiện nhóm đã chọn?',choices:[['还不知道他们最后选择了哪种交通工具。','Đúng: hai phương án vẫn được nêu là khả năng, chưa có lựa chọn cuối.'],['他们先坐地铁，然后坐公共汽车。','Sai: 或者 đưa lựa chọn, không phải thứ tự đi cả hai phương tiện.'],['他们坐了地铁，没有坐公共汽车。','Sai: phương án được nêu trước không có nghĩa đã được chọn.']],answer:0,cloze:{prompt:'Hai bước trước–sau: 我们先在网上买票，___到剧院取票。（用“然后”）',answer:'然后',feedback:'先…然后… giữ thứ tự mua trước, lấy vé sau; 一边 dùng cho đồng thời.'},transfer:'Chuyến bảo tàng khác: ban đầu cân nhắc đi tàu hoặc xe buýt; đặt vé trước rồi nhận vé ở cửa. Ngoài tranh còn có ảnh. Nhóm cuối cùng chỉ xem khu tranh, chưa có dữ kiện phương tiện đã chọn. Viết 4 câu không tự thêm điều chưa biết.',model:['出发前，我们想或者坐地铁，或者坐公共汽车。我们先订票，然后在门口取票。除了画以外，博物馆里还有照片。最后，我们只看了画，没有看完所有展品。','Chūfā qián, wǒmen xiǎng huòzhě zuò dìtiě, huòzhě zuò gōnggòng qìchē. Wǒmen xiān dìngpiào, ránhòu zài ménkǒu qǔpiào. Chúle huà yǐwài, bówùguǎn lǐ hái yǒu zhàopiàn. Zuìhòu, wǒmen zhǐ kàn le huà, méiyǒu kàn wán suǒyǒu zhǎnpǐn.','Trước khi đi chúng tôi tính tàu hoặc xe buýt. Chúng tôi đặt vé trước rồi lấy vé ở cửa. Ngoài tranh bảo tàng còn có ảnh. Cuối cùng chúng tôi chỉ xem tranh, chưa xem hết mọi vật trưng bày.'],criteria:['Phương tiện là lựa chọn chưa xác nhận.','Đặt vé trước, nhận vé sau.','Phân biệt danh mục có gì với nhóm đã xem gì.']},
 {suffix:'lesson-02',goal:'Nối diễn biến thể thao và hoạt động nấu ăn bằng đúng quan hệ ý',support:'主队 zhǔduì — đội chủ nhà; 客队 kèduì — đội khách; 领先 lǐngxiān — dẫn trước; 追平 zhuīpíng — gỡ hòa; 清淡 qīngdàn — thanh đạm. Đây là lịch hoạt động khu phố giả định.',paragraphs:p('lesson-02'),core:['比赛','得分','最后','一边','不但','而且'],rule:'一会儿…一会儿… chỉ luân phiên trạng thái trong trận. 又认真又冷静 nêu hai đặc điểm cùng có. 虽然…可是… giữ sự trái kỳ vọng: ghi điểm trước nhưng không thắng. 一边…一边… là nấu và giới thiệu cùng lúc; 不但…而且… thêm thông tin, không biểu thị đối lập. 如果…就… nêu phương án khi không ăn cay được.',pitfall:'Dẫn trước không phải thắng cuối trận. Câu chuyện lễ hội gắn với món do đầu bếp giới thiệu; không suy mọi món quê ấy đều cay hoặc ai cũng ăn được.',question:'Đội nào thắng cuối trận?',choices:[['客队最后赢了。','Đúng: đội khách thắng dù chủ nhà ghi điểm trước.'],['主队先得分，所以一定赢了。','Sai: điểm đầu tiên không quyết định kết quả cuối.'],['两队最后打平了。','Sai: luân phiên bị gỡ hòa là diễn biến, không phải kết quả cuối.']],answer:0,cloze:{prompt:'Giữ ý nhượng bộ: 虽然主队先得分，___客队最后赢了。（用“可是”）',answer:'可是',feedback:'虽然…可是… đối chiếu việc ghi điểm trước với kết quả trái kỳ vọng.'},transfer:'Một buổi cộng đồng khác: đội xanh ghi điểm trước nhưng đội đỏ thắng. Sau trận, người hướng dẫn vừa pha trà vừa giải thích cách làm. Trà không chỉ thơm mà còn có một câu chuyện. Nếu khách không uống trà, có thể chọn nước. Viết 4 câu đúng bốn quan hệ ý.',model:['虽然蓝队先得分，可是红队最后赢了。比赛以后，老师一边泡茶，一边介绍做法。这种茶不但很香，而且还有一个故事。如果客人不喝茶，就可以选水。','Suīrán lán duì xiān défēn, kěshì hóng duì zuìhòu yíng le. Bǐsài yǐhòu, lǎoshī yìbiān pào chá, yìbiān jièshào zuòfǎ. Zhè zhǒng chá bùdàn hěn xiāng, érqiě hái yǒu yí ge gùshi. Rúguǒ kèrén bù hē chá, jiù kěyǐ xuǎn shuǐ.','Dù đội xanh ghi điểm trước, đội đỏ thắng cuối trận. Sau trận người hướng dẫn vừa pha trà vừa giới thiệu. Trà không chỉ thơm mà còn có câu chuyện. Nếu khách không uống trà có thể chọn nước.'],criteria:['Đội đỏ thắng, không đảo người thắng.','一边 cho hai hành động đồng thời; 不但…而且… cho bổ sung.','如果 giữ phương án có điều kiện, không nói tất cả khách chọn nước.']},
 {suffix:'lesson-03',goal:'Phân biệt điều kiện cần để dự buổi họp mặt với điều kiện đủ để nhận thực đơn',support:'邀请 yāoqǐng — lời mời; 菜单 càidān — thực đơn; 聚会 jùhuì — họp mặt; 不等于 bù děngyú — không đồng nghĩa. Quy định chỉ thuộc buổi họp mặt trong truyện, không đại diện phong tục toàn Trung Quốc.',paragraphs:p('lesson-03'),core:['只有','才','只要','为了','习惯','做客'],rule:'只有收到邀请，才能参加… nêu lời mời là điều kiện cần của buổi này. 只要发消息，就发菜单 là lời chủ nhà cam kết gửi thực đơn khi có tin nhắn. Hai kết quả khác nhau: có thực đơn chưa đủ chứng minh được mời. 为了表示尊重 nêu mục đích hỏi trước; …了，就… sắp xếp trình tự đã xảy ra.',pitfall:'Không đổi 只有…才… và 只要…就… cho nhau. Không coi hỏi thực đơn là nhận lời mời. Mục đích lịch sự không tự chứng minh mọi hành vi đều lịch sự; đây là nếp của một gia đình.',question:'Người chỉ nhận được thực đơn đã chắc được mời chưa?',choices:[['还不能确定，收到菜单不等于收到邀请。','Đúng: hai loại tin khác nhau; lời mời mới là điều kiện cần để dự.'],['已经确定，因为只要发消息就能参加。','Sai: nhắn tin đủ để nhận thực đơn, không phải để dự.'],['不能参加，因为收到菜单的人都没有邀请。','Sai: có thực đơn không chứng minh có hay không có lời mời.']],answer:0,cloze:{prompt:'Điều kiện cần của buổi này: ___收到邀请，才能参加。（用“只有”）',answer:'只有',feedback:'只有…才… nêu điều kiện cần; không thay bằng 只要 trong câu này.'},transfer:'Buổi đọc sách giả định chỉ cho người có vé tham gia. Ban tổ chức hứa ai nhắn tin sẽ nhận lịch chương trình. Mai nhắn tin và nhận lịch, nhưng chưa biết đã có vé hay chưa. Viết 3–4 câu, không kết luận Mai được tham gia từ việc có lịch.',model:['只有有票，才能参加这次读书活动。只要给工作人员发消息，就能收到活动安排。小梅收到了安排，但我们还不知道她有没有票。所以还不能确定她能不能参加。','Zhǐyǒu yǒu piào, cái néng cānjiā zhè cì dúshū huódòng. Zhǐyào gěi gōngzuò rényuán fā xiāoxi, jiù néng shōudào huódòng ānpái. Xiǎo Méi shōudào le ānpái, dàn wǒmen hái bù zhīdào tā yǒu méiyǒu piào. Suǒyǐ hái bù néng quèdìng tā néng bu néng cānjiā.','Chỉ có vé mới được dự buổi đọc sách này. Chỉ cần nhắn nhân viên sẽ nhận lịch. Mai nhận lịch, nhưng chưa biết có vé hay không. Vì vậy chưa xác định Mai có được dự không.'],criteria:['Vé là điều kiện cần, không phải lịch.','Nhắn tin dẫn đến nhận lịch, không tự dẫn đến được dự.','Giữ trạng thái chưa biết Mai có vé hay chưa.']},
];
