import {emptyLessonBlock,type LessonPageDocument} from '../../src/learning/lessonPages';
import {emptyLessonActivity} from '../../src/learning/lessonActivities';
export function foodExtension(id:string,taskId:string):LessonPageDocument['pages']{
 const target={skill:'reading' as const,objective:'Theo dõi ngân sách và khẩu vị khi chọn món',sources:[{kind:'task' as const,id:taskId}]};
 return [
 {id:`${id}:v2:meal`,title:'Sau mua sắm: chọn bữa trưa',layout:'focus',stage:'understand',blocks:[{...emptyLessonBlock(`${id}:v2:block:meal`),kind:'reading',title:'Giá và khẩu vị cùng ảnh hưởng lựa chọn',reading:{instruction:'Đọc tình huống tiếp nối. 王丽 còn 30 tệ sau khi mua quần; giá dưới đây đã gồm toàn bộ bữa.',notePrompt:'Cô còn bao nhiêu tiền, không ăn được gì và đã chọn món nào?',paragraphs:[
 {id:`${id}:meal-0`,hanzi:'买完短裤，王丽还剩三十块钱。她走进一家小饭馆，看了看菜单。',pinyin:'Mǎi wán duǎnkù, Wáng Lì hái shèng sānshí kuài qián. Tā zǒu jìn yì jiā xiǎo fànguǎn, kàn le kan càidān.',meaningVi:'Mua quần xong, Vương Lệ còn 30 tệ. Cô vào một quán ăn nhỏ và xem thực đơn.'},
 {id:`${id}:meal-1`,hanzi:'面条二十块，辣的鸡肉饭二十五块。她不能吃辣，就点了面条和一杯五块钱的饮料。',pinyin:'Miàntiáo èrshí kuài, là de jīròu fàn èrshíwǔ kuài. Tā bù néng chī là, jiù diǎn le miàntiáo hé yì bēi wǔ kuài qián de yǐnliào.',meaningVi:'Mì 20 tệ, cơm gà cay 25 tệ. Cô không ăn cay được nên gọi mì và một cốc đồ uống 5 tệ.'},
 {id:`${id}:meal-2`,hanzi:'这顿饭一共二十五块。她吃饱了，也没有花完剩下的钱。',pinyin:'Zhè dùn fàn yígòng èrshíwǔ kuài. Tā chī bǎo le, yě méiyǒu huā wán shèng xià de qián.',meaningVi:'Bữa này tổng cộng 25 tệ. Cô ăn no và chưa tiêu hết số tiền còn lại.'},
 ]}}]},
 {id:`${id}:v2:meal-choice`,title:'Giữ đúng lý do chọn món',layout:'focus',stage:'practice',blocks:[{...emptyLessonBlock(`${id}:v2:block:meal-choice`),kind:'activity',title:'Không suy sở thích chỉ từ giá',body:'Vì sao cô không chọn cơm gà cay?',activity:{...emptyLessonActivity(),learningTarget:target,options:[{id:'budget',text:'因为她只有二十块钱。',feedback:'Không đúng: cô còn 30 tệ, không phải 20.'},{id:'taste',text:'因为她不能吃辣。',feedback:'Đúng: khẩu vị là lý do được nêu rõ; cơm 25 tệ vẫn trong 30 tệ.'},{id:'sold',text:'因为鸡肉饭已经卖完了。',feedback:'Không có thông tin món đã bán hết.'}],answerIds:['taste'],explanation:'Không gán mọi quyết định cho giá. Cô chọn mì theo khả năng ăn cay, đồng thời vẫn đủ tiền cho đồ uống.'}}]},
 {id:`${id}:v2:meal-transfer`,title:'Tự chọn bữa theo dữ kiện mới',layout:'workshop',stage:'transfer',blocks:[{...emptyLessonBlock(`${id}:v2:block:meal-transfer`),kind:'activity',title:'Giải thích lựa chọn bằng hai tiêu chí',body:'Nhân vật Lan có 30 tệ, ăn cay được và muốn cơm. Cơm gà cay 25 tệ, mì 20 tệ, đồ uống 5 tệ. Viết hai câu: chọn món/đồ uống và tổng tiền. Không giữ lý do “không ăn cay được” của Vương Lệ.',activity:{...emptyLessonActivity(),type:'rubric',learningTarget:{...target,skill:'writing'},rubric:[{id:'food',label:'Chọn cơm gà cay và đồ uống phù hợp dữ kiện',guidance:'Lan ăn cay được, muốn cơm; không tự gán dị ứng hoặc sở thích mì.'},{id:'cost',label:'Tổng 30 tệ, vừa ngân sách',guidance:'25 + 5 = 30; không nói còn 5 tệ.'}],explanation:'Một phương án: 小兰能吃辣，也想吃米饭，所以她点了辣的鸡肉饭和一杯饮料。一共三十块钱，正好是她带的钱。\nXiǎo Lán néng chī là, yě xiǎng chī mǐfàn, suǒyǐ tā diǎn le là de jīròu fàn hé yì bēi yǐnliào. Yígòng sānshí kuài qián, zhènghǎo shì tā dài de qián.\nLan ăn cay được và muốn cơm, nên gọi cơm gà cay cùng đồ uống. Tổng 30 tệ, vừa số tiền mang theo. Tự đối chiếu không phải điểm viết độc lập.'}}]},
 ];
}
