/** Original narratives; keep factual evidence separate from contextual illustrations. */
type Sentence=[string,string,string];
export type PersonalNarrative={suffix:string;scene?:string;goal:string;support:string;paragraphs:Sentence[];core:string[];rule:string;pitfall:string;question:string;choices:[string,string][];answer:number;cloze:{prompt:string;answer:string;feedback:string};transfer:string;model:Sentence;criteria:string[]};
export const personalNarratives:PersonalNarrative[]=[
 {suffix:'identity-transactions',scene:'hsk3-office-request',goal:'Phân biệt nộp đơn, nhận đơn và được đồng ý',support:'申请 shēnqǐng — đơn/đề nghị; 手续 shǒuxù — thủ tục; 填 tián — điền; 确认 quèrèn — xác nhận. Hồ sơ là giả định, không nhập số điện thoại thật.',paragraphs:[
 ['小林想周五请假一天，去参加家里的活动。他先问同事需要办什么手续。','Xiǎo Lín xiǎng Zhōuwǔ qǐng jià yì tiān, qù cānjiā jiālǐ de huódòng. Tā xiān wèn tóngshì xūyào bàn shénme shǒuxù.','Tiểu Lâm muốn xin nghỉ thứ Sáu một ngày để tham gia việc gia đình. Anh hỏi đồng nghiệp cần làm thủ tục gì trước.'],
 ['同事告诉他，申请上要写清楚请假的日期和联系方式。小林填完以后，又检查了一遍。','Tóngshì gàosu tā, shēnqǐng shàng yào xiě qīngchu qǐngjià de rìqī hé liánxì fāngshì. Xiǎo Lín tián wán yǐhòu, yòu jiǎnchá le yí biàn.','Đồng nghiệp nói đơn cần ghi rõ ngày nghỉ và cách liên hệ. Điền xong, Tiểu Lâm kiểm tra thêm một lượt.'],
 ['经理收到申请时，没有马上同意。她发现小林写的是周四，就请他先确认日期。','Jīnglǐ shōudào shēnqǐng shí, méiyǒu mǎshàng tóngyì. Tā fāxiàn Xiǎo Lín xiě de shì Zhōusì, jiù qǐng tā xiān quèrèn rìqī.','Khi nhận đơn, quản lý không đồng ý ngay. Cô phát hiện Tiểu Lâm ghi thứ Năm nên yêu cầu xác nhận ngày trước.'],
 ['小林把日期改成了周五，再交给经理。经理确认工作安排没有问题以后，才同意了他的申请。','Xiǎo Lín bǎ rìqī gǎi chéng le Zhōuwǔ, zài jiāo gěi jīnglǐ. Jīnglǐ quèrèn gōngzuò ānpái méiyǒu wèntí yǐhòu, cái tóngyì le tā de shēnqǐng.','Tiểu Lâm sửa ngày thành thứ Sáu rồi nộp lại. Sau khi xác nhận lịch công việc không có vấn đề, quản lý mới đồng ý.'],
 ],core:['请假','办','需要','检查','收到','经理','清楚','同意'],rule:'收到 chỉ nhận được, không đồng nghĩa 同意. …以后才… nhấn mạnh chỉ sau điều kiện đó mới xảy ra kết quả. 把日期改成… nêu dữ kiện đã sửa. 先…再… nêu trình tự; 再交给经理 là bước nộp tiếp sau sửa, còn 又检查了一遍 là kể một lần kiểm tra thêm đã xảy ra.',pitfall:'Đừng tóm tắt “quản lý nhận đơn nên đã duyệt ngay”. Ngày thứ Năm là dữ kiện sai trên bản đầu; yêu cầu cuối là thứ Sáu. Không thêm lý do nghỉ ốm vì truyện chỉ nói việc gia đình.',question:'Đơn được đồng ý vào lúc nào?',choices:[['经理刚收到第一份申请的时候。','Sai: khi nhận bản đầu quản lý chưa đồng ý.'],['日期改好，经理确认工作安排没有问题以后。','Đúng: cần sửa ngày và xác nhận lịch trước.'],['小林问同事的时候。','Sai: hỏi thủ tục chưa phải nộp hay được đồng ý.']],answer:1,cloze:{prompt:'Điền từ nhấn mạnh chỉ sau xác nhận mới đồng ý: 经理确认以后，___同意了申请。',answer:'才',feedback:'才 nhấn mạnh điều kiện/thời điểm cần đạt trước kết quả. 马上 sẽ làm mất việc phải chờ xác nhận.'},transfer:'Viết 4 câu: Lan xin nghỉ thứ Hai nhưng ghi nhầm thứ Ba. Quản lý yêu cầu sửa; cô đã sửa và nộp lại. Đến cuối câu chuyện quản lý chưa trả lời. Không viết rằng đơn đã được đồng ý.',model:['小兰想周一请假，可是在申请上写了周二。经理请她修改日期。她把日期改成周一，又交给了经理。经理还没有回答，所以现在还不能说申请已经得到了同意。','Xiǎo Lán xiǎng Zhōuyī qǐng jià, kěshì zài shēnqǐng shàng xiě le Zhōuèr. Jīnglǐ qǐng tā xiūgǎi rìqī. Tā bǎ rìqī gǎi chéng Zhōuyī, yòu jiāo gěi le jīnglǐ. Jīnglǐ hái méiyǒu huídá, suǒyǐ xiànzài hái bù néng shuō shēnqǐng yǐjīng dédào le tóngyì.','Lan muốn nghỉ thứ Hai nhưng ghi thứ Ba. Quản lý yêu cầu sửa ngày. Cô sửa thành thứ Hai và nộp lại. Quản lý chưa trả lời nên hiện chưa thể nói đơn đã được đồng ý.'],criteria:['Ngày muốn nghỉ thứ Hai, ngày sai thứ Ba.','Sửa và nộp lại là việc đã xong.','Chưa có trả lời, không biến nhận đơn thành phê duyệt.']},
 {suffix:'travel-transport',scene:'hsk3-travel-detour',goal:'Theo dõi lịch trình dự kiến và kết quả thực tế',support:'出租车 chūzūchē — taxi; 堵车 dǔchē — tắc đường; 绕路 ràolù — đi vòng; 入口 rùkǒu — lối vào. Giờ giấc trong văn bản là dữ kiện bài, ảnh không có đồng hồ để đọc.',paragraphs:[
 ['小安打算坐九点的火车去看朋友。他根据地图，决定八点坐出租车出发。','Xiǎo Ān dǎsuàn zuò jiǔ diǎn de huǒchē qù kàn péngyou. Tā gēnjù dìtú, juédìng bā diǎn zuò chūzūchē chūfā.','Tiểu An định đi tàu 9 giờ thăm bạn. Dựa trên bản đồ, anh quyết định xuất phát bằng taxi lúc 8 giờ.'],
 ['到了一个路口，前面堵车了。司机说，换一条路可能快一点儿，小安同意了。','Dào le yí ge lùkǒu, qiánmian dǔchē le. Sījī shuō, huàn yì tiáo lù kěnéng kuài yìdiǎnr, Xiǎo Ān tóngyì le.','Đến một giao lộ, phía trước tắc đường. Tài xế nói đổi đường có thể nhanh hơn một chút, Tiểu An đồng ý.'],
 ['他们绕路以后，八点四十分到了火车站。小安先找到了入口，再拿出车票。','Tāmen ràolù yǐhòu, bā diǎn sìshí fēn dào le huǒchēzhàn. Xiǎo Ān xiān zhǎo dào le rùkǒu, zài ná chū chēpiào.','Sau khi đi vòng, họ đến ga lúc 8:40. Tiểu An tìm được lối vào trước rồi lấy vé ra.'],
 ['八点五十分开始检票。虽然路上耽误了一些时间，小安最后还是坐上了九点的火车。','Bā diǎn wǔshí fēn kāishǐ jiǎnpiào. Suīrán lùshang dānwu le yìxiē shíjiān, Xiǎo Ān zuìhòu háishi zuò shàng le jiǔ diǎn de huǒchē.','8:50 bắt đầu kiểm vé. Dù trên đường mất thêm thời gian, cuối cùng Tiểu An vẫn lên được tàu 9 giờ.'],
 ],core:['根据','地图','决定','出发','路口','司机','换','检票'],rule:'Tách giờ xuất phát 8:00, đến ga 8:40, kiểm vé 8:50 và tàu 9:00. 根据 nêu căn cứ ra quyết định. 可能 chỉ khả năng của đường vòng, không đảm bảo nhanh hơn. 虽然…还是… nối trở ngại với kết quả đạt được. 坐上了 cho biết đã lên được, không chỉ dự định 坐.',pitfall:'Tắc đường không đồng nghĩa lỡ tàu. Không suy đường vòng mất đúng 40 phút: 40 phút là toàn hành trình từ lúc xuất phát. Không biến lời dự đoán tài xế thành kết quả đo được.',question:'Thông tin nào được văn bản xác nhận?',choices:[['小安没赶上九点的火车。','Sai: kết thúc nói đã lên tàu 9 giờ.'],['绕路一定比原来的路快四十分钟。','Sai: không có thời gian tuyến cũ để so sánh.'],['小安八点四十分到站，后来坐上了九点的火车。','Đúng: giữ đúng giờ đến và kết quả.']],answer:2,cloze:{prompt:'Điền từ giữ kết quả trái trở ngại: 虽然路上堵车，小安最后___坐上了火车。',answer:'还是',feedback:'还是 trong 虽然…还是… nghĩa là vẫn. Không dùng 或者 (hoặc) để nối kết quả này.'},transfer:'Dữ kiện mới: Mai định đi tàu 10 giờ, xuất phát 9 giờ nhưng đến ga 10:05 vì tắc đường. Sau đó đổi vé sang 11 giờ. Viết 4 câu phân biệt kế hoạch, nguyên nhân, lỡ chuyến và giải pháp; không giữ kết quả lên tàu đúng chuyến của An.',model:['小梅打算坐十点的火车，九点就出发了。因为路上堵车，她十点零五分才到火车站。她没赶上十点的火车。后来，她换了十一点的车票。','Xiǎo Méi dǎsuàn zuò shí diǎn de huǒchē, jiǔ diǎn jiù chūfā le. Yīnwèi lùshang dǔchē, tā shí diǎn líng wǔ fēn cái dào huǒchēzhàn. Tā méi gǎn shàng shí diǎn de huǒchē. Hòulái, tā huàn le shíyī diǎn de chēpiào.','Mai định đi tàu 10 giờ, đã xuất phát lúc 9 giờ. Vì tắc đường, 10:05 cô mới đến ga. Cô lỡ tàu 10 giờ. Sau đó cô đổi vé sang 11 giờ.'],criteria:['Giữ 9 giờ xuất phát, 10:05 đến và chuyến cũ 10 giờ.','Nêu tắc đường dẫn đến lỡ tàu, khác truyện An.','Đổi vé 11 giờ; không tự khẳng định đã lên chuyến mới.']},
 {suffix:'food-shopping',scene:'hsk3-shopping-choice',goal:'Tóm tắt lựa chọn mua hàng bằng tiêu chí và bằng chứng',support:'店员 diànyuán — nhân viên cửa hàng; 蓝色 lánsè — xanh lam; 米色 mǐsè — màu be; 预算 yùsuàn — ngân sách; 超出 chāochū — vượt quá. Các màu và giá là dữ kiện của văn bản, không đọc từ ảnh.',paragraphs:[
 ['周末，王丽去商店买短裤。她带了一百五十块钱，不想超出预算。','Zhōumò, Wáng Lì qù shāngdiàn mǎi duǎnkù. Tā dài le yì bǎi wǔshí kuài qián, bù xiǎng chāochū yùsuàn.','Cuối tuần, Vương Lệ đến cửa hàng mua quần đùi. Cô mang 150 tệ và không muốn vượt ngân sách.'],
 ['店员拿来了两条短裤。蓝色的一百二十块，米色的一百八十块。','Diànyuán ná lái le liǎng tiáo duǎnkù. Lánsè de yì bǎi èrshí kuài, mǐsè de yì bǎi bāshí kuài.','Nhân viên mang đến hai chiếc quần. Chiếc xanh 120 tệ, chiếc be 180 tệ.'],
 ['王丽先试了蓝色的，觉得大小正合适。她又试了米色的，可是穿着有点儿瘦。','Wáng Lì xiān shì le lánsè de, juéde dàxiǎo zhèng héshì. Tā yòu shì le mǐsè de, kěshì chuān zhe yǒudiǎnr shòu.','Vương Lệ thử chiếc xanh trước và thấy vừa đúng. Cô thử thêm chiếc be, nhưng mặc hơi chật.'],
 ['虽然她更喜欢米色，但是蓝色的既合适，也没有超出预算。她最后决定买蓝色的。','Suīrán tā gèng xǐhuan mǐsè, dànshì lánsè de jì héshì, yě méiyǒu chāochū yùsuàn. Tā zuìhòu juédìng mǎi lánsè de.','Dù thích màu be hơn, chiếc xanh vừa người và không vượt ngân sách. Cuối cùng cô quyết định mua chiếc xanh.'],
 ],core:['短裤','试','大小','合适','比较','决定','先','又'],rule:'Tách sở thích khỏi quyết định cuối. 先…又… nối hai lần thử đã diễn ra; 又 là thêm một lần đã xảy ra, không phải 再 trong lời hẹn thử lần sau. 虽然…但是… giữ sự trái kỳ vọng: thích màu be nhưng chọn xanh. 既…也… nêu hai ưu điểm cùng đúng: vừa và trong ngân sách. 蓝色的 lược 短裤 vì đã xác định vật đang nói.',pitfall:'Không viết mua chiếc be chỉ vì cô thích màu đó. Cũng không nói xanh rẻ nhất cửa hàng: văn bản chỉ so sánh hai chiếc. “Vừa” không đồng nghĩa “rộng”.',question:'Vì sao Vương Lệ chọn chiếc xanh?',choices:[['因为蓝色的合适，而且没有超出预算。','Đúng: cả kích cỡ và ngân sách đều phù hợp.'],['因为她最喜欢蓝色。','Sai: văn bản nói thích màu be hơn.'],['因为米色的比蓝色的便宜。','Sai: 180 cao hơn 120.']],answer:0,cloze:{prompt:'Giữ quan hệ trái kỳ vọng, điền liên từ: 虽然她更喜欢米色，___她买了蓝色的。',answer:'但是',feedback:'但是 nối lựa chọn thực tế khác sở thích. 所以 sẽ biến sở thích màu be thành lý do mua xanh mà thiếu cầu nối.'},transfer:'Dữ kiện mới: Lan có 200 tệ; áo trắng 190 tệ vừa người, áo xanh 160 tệ quá nhỏ; Lan thích xanh hơn nhưng mua trắng. Viết 4 câu: ngân sách, hai lựa chọn, sở thích trái quyết định, lý do cuối. Không đổi thành quần trong văn bản cũ.',model:['小兰带了两百块钱。白色的衣服一百九十块，大小合适；蓝色的一百六十块，可是太小。虽然她更喜欢蓝色，但是她买了白色的。因为白色的合适，也没有超出预算。','Xiǎo Lán dài le liǎng bǎi kuài qián. Báisè de yīfu yì bǎi jiǔshí kuài, dàxiǎo héshì; lánsè de yì bǎi liùshí kuài, kěshì tài xiǎo. Suīrán tā gèng xǐhuan lánsè, dànshì tā mǎi le báisè de. Yīnwèi báisè de héshì, yě méiyǒu chāochū yùsuàn.','Lan mang 200 tệ. Áo trắng 190 tệ vừa người; áo xanh 160 tệ nhưng quá nhỏ. Dù thích xanh hơn, cô mua trắng. Vì áo trắng vừa và không vượt ngân sách.'],criteria:['Đúng vật áo, giá 190/160 và ngân sách 200.','Không nhầm sở thích xanh với quyết định mua trắng.','Nêu kích cỡ và ngân sách; không suy rẻ nhất cửa hàng.']},
 {suffix:'health-care',scene:'hsk3-clinic-conversation',goal:'Theo dõi triệu chứng, lời dặn và kết quả theo thời gian',support:'摔倒 shuāidǎo — ngã; 检查 jiǎnchá — kiểm tra; 复查 fùchá — tái khám; 按照 ànzhào — theo. Đây là câu chuyện giả định để học tiếng, lời bác sĩ chỉ áp dụng cho nhân vật trong chuyện.',paragraphs:[
 ['周一，一位画家在公园摔倒了，右腿很疼。他的朋友陪他去医院。','Zhōuyī, yí wèi huàjiā zài gōngyuán shuāidǎo le, yòu tuǐ hěn téng. Tā de péngyou péi tā qù yīyuàn.','Thứ Hai, một họa sĩ ngã ở công viên, chân phải rất đau. Bạn ông đi cùng ông tới bệnh viện.'],
 ['医生检查以后说，他需要住院观察两天。画家本来想回家，只好先住院。','Yīshēng jiǎnchá yǐhòu shuō, tā xūyào zhùyuàn guānchá liǎng tiān. Huàjiā běnlái xiǎng huí jiā, zhǐhǎo xiān zhùyuàn.','Sau khi kiểm tra, bác sĩ nói ông cần nằm viện theo dõi hai ngày. Ban đầu ông muốn về nhà, nhưng đành nhập viện trước.'],
 ['周三，医生同意他出院，并请他下周一回来复查。医生还说，现在不要跑步，要按照复查结果再安排锻炼。','Zhōusān, yīshēng tóngyì tā chūyuàn, bìng qǐng tā xià zhōuyī huílai fùchá. Yīshēng hái shuō, xiànzài bú yào pǎobù, yào ànzhào fùchá jiéguǒ zài ānpái duànliàn.','Thứ Tư, bác sĩ đồng ý cho ông xuất viện và hẹn thứ Hai tuần sau tái khám. Bác sĩ còn dặn hiện chưa chạy bộ, cần dựa kết quả tái khám rồi sắp xếp luyện tập.'],
 ['回家以后，朋友帮他买菜。画家觉得腿比周一舒服了，但是他知道出院不等于已经完全好了。','Huí jiā yǐhòu, péngyou bāng tā mǎi cài. Huàjiā juéde tuǐ bǐ Zhōuyī shūfu le, dànshì tā zhīdào chūyuàn bù děngyú yǐjīng wánquán hǎo le.','Sau khi về nhà, bạn giúp ông mua đồ ăn. Ông thấy chân dễ chịu hơn thứ Hai nhưng biết xuất viện không có nghĩa đã hoàn toàn khỏi.'],
 ],core:['画家','腿','需要','住院','出院','照顾','以后','锻炼'],rule:'Dựng trục 周一→周三→下周一. 以后 đặt sau sự kiện làm mốc. 只好 biểu thị đành chọn phương án trong hoàn cảnh, không có nghĩa rất muốn. 先…再… trong lời dặn nêu thứ tự cần thực hiện, không chứng minh các bước đều đã xong. 比…舒服了 chỉ thay đổi so với trước, không phải hoàn toàn khỏi.',pitfall:'Hẹn tái khám chưa phải đã tái khám. Đừng biến lời dặn cho một nhân vật thành quy tắc y tế cho mọi người; nhiệm vụ ở đây là hiểu đúng người, thời gian và lời nói.',question:'Đến cuối văn bản, việc nào vẫn là kế hoạch?',choices:[['周一去医院。','Việc này đã xảy ra lúc mở câu chuyện.'],['周三出院。','Ông đã về nhà sau khi xuất viện.'],['下周一回来复查。','Đúng: mới là lời hẹn tái khám, chưa có kết quả.']],answer:2,cloze:{prompt:'Điền liên từ thời gian: 回家___，朋友帮他买菜。',answer:'以后',feedback:'以后 nối việc về nhà với việc xảy ra sau đó. Đây là mốc đã xảy ra, khác lời hẹn tuần tới.'},transfer:'Đổi dữ kiện: Mai khám tay đau vào thứ Ba, về nhà cùng ngày; hẹn thứ Sáu tái khám, chưa có kết quả. Chị gái giúp nấu cơm. Viết 4 câu tách việc đã xảy ra, hỗ trợ nhận được và việc còn chờ; không tự thêm thuốc hoặc chẩn đoán.',model:['小梅周二因为手疼去医院。她当天就回家了。回家以后，姐姐帮她做饭。医生请她周五回来复查，现在还没有复查结果。','Xiǎo Méi Zhōuèr yīnwèi shǒu téng qù yīyuàn. Tā dàngtiān jiù huí jiā le. Huí jiā yǐhòu, jiějie bāng tā zuò fàn. Yīshēng qǐng tā Zhōuwǔ huílai fùchá, xiànzài hái méiyǒu fùchá jiéguǒ.','Mai đến bệnh viện thứ Ba vì đau tay. Cô về nhà cùng ngày. Sau khi về, chị giúp nấu cơm. Bác sĩ hẹn thứ Sáu tái khám, hiện chưa có kết quả tái khám.'],criteria:['Đúng thứ Ba khám và về nhà, thứ Sáu mới là hẹn.','Nêu chị giúp nấu cơm, không nhầm với bạn mua đồ ăn.','Không tự thêm chẩn đoán, thuốc hoặc khẳng định khỏi hẳn.']},
 {suffix:'home-family-leisure',scene:'hsk3-moving-neighbors',goal:'Kể thay đổi nơi ở mà không đánh đồng mọi mặt đều tốt hơn',support:'楼下 lóuxià — dưới tầng; 整理 zhěnglǐ — sắp xếp; 熟悉 shúxī — quen thuộc; 环境 huánjìng — môi trường; 搬进 bān jìn — chuyển vào.',paragraphs:[
 ['上个月，小周和妻子搬进了一个新小区。新屋子比以前小，但是离公司更近。','Shàng ge yuè, Xiǎo Zhōu hé qīzi bān jìn le yí ge xīn xiǎoqū. Xīn wūzi bǐ yǐqián xiǎo, dànshì lí gōngsī gèng jìn.','Tháng trước, Tiểu Chu và vợ chuyển vào khu nhà mới. Nhà mới nhỏ hơn trước nhưng gần công ty hơn.'],
 ['刚搬来的时候，他们忙着整理箱子，几乎没有时间做饭。住在楼下的邻居告诉他们，附近有一家小饭馆。','Gāng bān lái de shíhou, tāmen máng zhe zhěnglǐ xiāngzi, jīhū méiyǒu shíjiān zuò fàn. Zhù zài lóuxià de línjū gàosu tāmen, fùjìn yǒu yì jiā xiǎo fànguǎn.','Lúc vừa chuyển đến, họ bận sắp xếp thùng đồ, gần như không có thời gian nấu ăn. Người hàng xóm tầng dưới cho biết gần đó có quán ăn nhỏ.'],
 ['周末，他们去附近的公园散步，又和邻居聊了一会儿。邻居喜欢养花，小周也对养花有兴趣。','Zhōumò, tāmen qù fùjìn de gōngyuán sànbù, yòu hé línjū liáo le yíhuìr. Línjū xǐhuan yǎng huā, Xiǎo Zhōu yě duì yǎng huā yǒu xìngqù.','Cuối tuần họ đi dạo công viên gần nhà rồi trò chuyện với hàng xóm. Hàng xóm thích trồng hoa; Tiểu Chu cũng có hứng thú.'],
 ['现在，他们已经熟悉了附近的环境。小周觉得生活方便多了，不过晚上有时能听到马路上的声音。','Xiànzài, tāmen yǐjīng shúxī le fùjìn de huánjìng. Xiǎo Zhōu juéde shēnghuó fāngbiàn duō le, búguò wǎnshang yǒushí néng tīng dào mǎlù shàng de shēngyīn.','Hiện họ đã quen khu vực xung quanh. Tiểu Chu thấy sinh hoạt tiện hơn nhiều, nhưng đôi lúc buổi tối nghe tiếng ngoài đường.'],
 ],core:['搬家','小区','屋子','邻居','附近','箱子','兴趣','方便'],rule:'刚…的时候 nêu giai đoạn mới bắt đầu, 现在 nêu tình trạng hiện nay. 几乎没有 là gần như không có, không phải phủ định tuyệt đối. 对…有兴趣 nói hứng thú với hoạt động. 不过 giữ giới hạn của đánh giá: tiện hơn nhưng vẫn có tiếng ồn. So sánh phải nói rõ mặt nào thay đổi.',pitfall:'Không suy nhà mới rộng hơn vì “tiện hơn”. Hàng xóm giúp bằng thông tin, văn bản không nói họ giúp chuyển thùng. 现在 đã quen không có nghĩa mọi khó khăn đều biến mất.',question:'Nhận xét nào giữ đúng cả lợi ích và hạn chế?',choices:[['新屋子更大，也更安静。','Sai: nhà nhỏ hơn và đôi khi có tiếng đường.'],['生活方便多了，不过晚上有时有声音。','Đúng: giữ cả tiện lợi và hạn chế.'],['他们一直没有时间做饭。','Sai: gần như không có thời gian chỉ giai đoạn vừa chuyển tới.']],answer:1,cloze:{prompt:'Điền giới từ: 小周___养花有兴趣。',answer:'对',feedback:'对 + hoạt động + 有兴趣. Không dùng 在 để diễn đạt đối tượng hứng thú trong khung này.'},transfer:'Nhân vật mới Lan chuyển đến nhà rộng hơn nhưng xa trường hơn. Ban đầu chưa biết chợ ở đâu; hàng xóm chỉ đường. Hiện đã quen khu vực nhưng phải dậy sớm đi học. Viết 4–5 câu, giữ lợi ích và hạn chế.',model:['小兰搬家了，新屋子比以前大，但是离学校更远。刚搬来的时候，她不知道市场在哪儿。邻居告诉了她。现在她已经熟悉了附近的环境，不过每天上学得早起。','Xiǎo Lán bān jiā le, xīn wūzi bǐ yǐqián dà, dànshì lí xuéxiào gèng yuǎn. Gāng bān lái de shíhou, tā bù zhīdào shìchǎng zài nǎr. Línjū gàosu le tā. Xiànzài tā yǐjīng shúxī le fùjìn de huánjìng, búguò měitiān shàngxué děi zǎoqǐ.','Lan chuyển nhà, nhà mới rộng hơn nhưng xa trường hơn. Lúc mới đến cô không biết chợ ở đâu. Hàng xóm chỉ cho cô. Hiện cô đã quen khu vực, nhưng mỗi ngày phải dậy sớm đi học.'],criteria:['Rộng hơn nhưng xa trường, không đảo hai mặt.','Phân biệt lúc đầu và hiện nay.','Hàng xóm cung cấp thông tin; không bịa giúp chuyển đồ.']},
];
