import type {PersonalNarrative} from './hsk3-personal-narratives';

export const studyWorkExtensions:PersonalNarrative[]=[
 {suffix:'campus-education',scene:'hsk3-campus-visit',goal:'Tóm tắt buổi tham quan và phân biệt vai trò nhà trường, gia đình',support:'家长 jiāzhǎng — phụ huynh; 参观 cānguān — tham quan; 鼓励 gǔlì — khuyến khích; 代替 dàitì — thay thế; 提问 tíwèn — đặt câu hỏi.',paragraphs:[
 ['周六，小雨和妈妈在图书馆前见面，一起参观新校园。小雨下个月才上初中，现在还不熟悉这里。','Zhōuliù, Xiǎo Yǔ hé māma zài túshūguǎn qián jiànmiàn, yìqǐ cānguān xīn xiàoyuán. Xiǎo Yǔ xià ge yuè cái shàng chūzhōng, xiànzài hái bù shúxī zhèlǐ.','Thứ Bảy, Tiểu Vũ và mẹ gặp trước thư viện rồi tham quan trường mới. Tháng sau em mới lên cấp hai, hiện chưa quen nơi này.'],
 ['校长站在黑板旁边，介绍学校的安排。学生上午上课，下午可以参加体育活动，也可以去图书馆看书。','Xiàozhǎng zhàn zài hēibǎn pángbiān, jièshào xuéxiào de ānpái. Xuéshēng shàngwǔ shàng kè, xiàwǔ kěyǐ cānjiā tǐyù huódòng, yě kěyǐ qù túshūguǎn kàn shū.','Hiệu trưởng đứng cạnh bảng giới thiệu lịch của trường. Học sinh học buổi sáng; chiều có thể tham gia thể thao hoặc đọc ở thư viện.'],
 ['小雨想问图书馆几点关门，却不好意思开口。妈妈没有代替她问，而是鼓励她自己向老师提问。老师回答说，下午五点关门。','Xiǎo Yǔ xiǎng wèn túshūguǎn jǐ diǎn guān mén, què bù hǎoyìsi kāikǒu. Māma méiyǒu dàitì tā wèn, ér shì gǔlì tā zìjǐ xiàng lǎoshī tíwèn. Lǎoshī huídá shuō, xiàwǔ wǔ diǎn guān mén.','Tiểu Vũ muốn hỏi giờ đóng cửa nhưng ngại mở lời. Mẹ không hỏi hộ mà khuyến khích em tự hỏi giáo viên. Giáo viên trả lời đóng cửa lúc 5 giờ chiều.'],
 ['参观结束后，小雨清楚了图书馆的开放时间，妈妈也放心了。她们决定开学后再了解其他活动，今天没有报名。','Cānguān jiéshù hòu, Xiǎo Yǔ qīngchu le túshūguǎn de kāifàng shíjiān, māma yě fàngxīn le. Tāmen juédìng kāixué hòu zài liǎojiě qítā huódòng, jīntiān méiyǒu bàomíng.','Sau tham quan, Tiểu Vũ hiểu rõ giờ mở cửa thư viện, mẹ cũng yên tâm. Họ định sau khai giảng tìm hiểu hoạt động khác; hôm nay chưa đăng ký.'],
 ],core:['图书馆','见面','校园','初中','校长','黑板','体育','清楚'],rule:'Theo dõi người làm từng việc: hiệu trưởng giới thiệu; mẹ khuyến khích; Tiểu Vũ hỏi; giáo viên trả lời. 没有…而是… phân biệt hỏi hộ với hỗ trợ con tự hỏi. 才 ở 下个月才… đánh dấu việc chưa xảy ra; 开学后再… là bước tương lai.',pitfall:'Được phép tham gia hoạt động không có nghĩa đã đăng ký. Biết giờ thư viện không có nghĩa đã biết mọi hoạt động của trường.',question:'Mẹ hỗ trợ Tiểu Vũ bằng cách nào?',choices:[['她鼓励小雨自己向老师提问。','Đúng: mẹ giúp con tự mở lời.'],['她代替小雨问了所有问题。','Sai: mẹ không hỏi thay.'],['她已经给小雨报名了。','Sai: hôm nay chưa đăng ký.']],answer:0,cloze:{prompt:'Điền theo quan hệ thay thế: 妈妈没有代替她问，___鼓励她自己问。',answer:'而是',feedback:'没有…而是… phủ định cách thứ nhất rồi nêu cách thực tế.'},transfer:'Nam tham quan trường với bố. Nam tự hỏi giờ sân thể thao đóng cửa; giáo viên nói 6 giờ chiều. Bố giúp ghi giờ, chưa đăng ký hoạt động. Viết 4 câu đúng vai trò từng người.',model:['小南和爸爸参观学校。小南自己问老师体育场几点关门。老师说下午六点关门，爸爸帮他记下时间。他们还没有报名参加活动。','Xiǎo Nán hé bàba cānguān xuéxiào. Xiǎo Nán zìjǐ wèn lǎoshī tǐyùchǎng jǐ diǎn guān mén. Lǎoshī shuō xiàwǔ liù diǎn guān mén, bàba bāng tā jì xià shíjiān. Tāmen hái méiyǒu bàomíng cānjiā huódòng.','Nam cùng bố tham quan trường. Nam tự hỏi giờ sân thể thao đóng cửa. Giáo viên nói 6 giờ chiều, bố giúp ghi giờ. Họ chưa đăng ký hoạt động.'],criteria:['Đúng sân thể thao và 6 giờ, không chép giờ thư viện.','Nam hỏi, giáo viên trả lời, bố ghi.','Không thêm kết quả đăng ký.']},
 {suffix:'office-tasks',scene:'hsk3-office-library',goal:'Tách manh mối, kết quả tìm đồ và quy trình mới',support:'录音室 lùyīnshì — phòng thu; 资料 zīliào — tài liệu; 登记 dēngjì — ghi vào sổ; 归还 guīhuán — trả lại; 栏 lán — cột trong bảng.',paragraphs:[
 ['工作日早上，王经理开机看邮件，准备九点的会议。他发现要用的词典不见了。','Gōngzuòrì zǎoshang, Wáng jīnglǐ kāijī kàn yóujiàn, zhǔnbèi jiǔ diǎn de huìyì. Tā fāxiàn yào yòng de cídiǎn bújiàn le.','Sáng ngày làm việc, quản lý Vương bật máy xem thư, chuẩn bị họp lúc 9 giờ. Anh phát hiện cuốn từ điển cần dùng không thấy đâu.'],
 ['他先找桌子下面和灯旁边，可是没有找到。同事提醒他，昨天录节目时可能用过这本词典。','Tā xiān zhǎo zhuōzi xiàmian hé dēng pángbiān, kěshì méiyǒu zhǎodào. Tóngshì tíxǐng tā, zuótiān lù jiémù shí kěnéng yòng guo zhè běn cídiǎn.','Anh tìm dưới bàn và cạnh đèn trước nhưng chưa thấy. Đồng nghiệp nhắc có thể đã dùng cuốn này lúc thu chương trình hôm qua.'],
 ['王经理到录音室，在椅子上找到了词典。他在会议开始前把词典拿回来，还给负责资料的同事。','Wáng jīnglǐ dào lùyīnshì, zài yǐzi shàng zhǎodào le cídiǎn. Tā zài huìyì kāishǐ qián bǎ cídiǎn ná huílai, huán gěi fùzé zīliào de tóngshì.','Quản lý đến phòng thu và tìm thấy từ điển trên ghế. Anh mang về trước khi họp, trả cho người phụ trách tài liệu.'],
 ['从那天起，办公室开始登记借用的资料。借的时候写姓名和日期，归还后再填最后一栏。新表已经做好，但还没有人用过。','Cóng nà tiān qǐ, bàngōngshì kāishǐ dēngjì jièyòng de zīliào. Jiè de shíhou xiě xìngmíng hé rìqī, guīhuán hòu zài tián zuìhòu yì lán. Xīn biǎo yǐjīng zuò hǎo, dàn hái méiyǒu rén yòng guo.','Từ hôm đó, văn phòng bắt đầu ghi sổ mượn tài liệu. Lúc mượn ghi tên, ngày; trả xong mới điền cột cuối. Bảng mới đã làm xong nhưng chưa ai dùng thử.'],
 ],core:['工作日','经理','开机','邮件','会议','词典','不见','灯'],rule:'找 là tìm, 找到 là tìm thấy. 可能 chỉ manh mối chưa xác nhận, 找到了 mới xác nhận vị trí. 在…前 xác định trả đồ trước cuộc họp. 从那天起 nêu mốc quy trình mới, không chứng minh quy trình đã có hiệu quả.',pitfall:'Không kể tìm thấy dưới bàn: đó là nơi đã tìm không thành. Bảng hoàn thành chưa có nghĩa đã được dùng hoặc sẽ loại bỏ mọi thất lạc.',question:'Thông tin nào đã được xác nhận?',choices:[['词典在录音室的椅子上。','Đúng: quản lý đến và tìm thấy tại đó.'],['新表已经用了一个月。','Sai: chưa ai dùng bảng mới.'],['词典在桌子下面。','Sai: đã tìm dưới bàn nhưng không thấy.']],answer:0,cloze:{prompt:'Điền bổ ngữ kết quả trong “đã tìm thấy”: 他在椅子上找___了词典。',answer:'到',feedback:'找到 xác nhận kết quả, khác chỉ thực hiện hành động 找.'},transfer:'Đổi sự cố: máy ghi âm không ở tủ; Lan tìm thấy trong phòng họp và trả trước 4 giờ. Bảng mượn mới đã thử một lần, chưa biết hiệu quả lâu dài. Viết 4 câu từ tìm kiếm đến giới hạn của kết quả.',model:['小兰先在柜子里找录音机，可是没有找到。后来，她在会议室找到了录音机。她四点以前把它还了。新的借用表只用过一次，现在还不知道长期效果。','Xiǎo Lán xiān zài guìzi lǐ zhǎo lùyīnjī, kěshì méiyǒu zhǎodào. Hòulái, tā zài huìyìshì zhǎodào le lùyīnjī. Tā sì diǎn yǐqián bǎ tā huán le. Xīn de jièyòng biǎo zhǐ yòng guo yí cì, xiànzài hái bù zhīdào chángqī xiàoguǒ.','Lan tìm máy ghi âm trong tủ nhưng chưa thấy. Sau đó cô tìm thấy ở phòng họp, trả trước 4 giờ. Bảng mượn mới chỉ dùng một lần, chưa biết hiệu quả lâu dài.'],criteria:['Đúng máy ghi âm và phòng họp.','Trả trước 4 giờ, không biến thành đúng 4 giờ.','Một lần dùng chưa chứng minh hiệu quả lâu dài.']},
 {suffix:'career-experience',scene:'hsk3-fashion-career',goal:'Tóm tắt kinh nghiệm, lý do chọn nghề và kế hoạch chưa thực hiện',support:'设计 shèjì — thiết kế; 草图 cǎotú — phác thảo; 需求 xūqiú — nhu cầu; 专业 zhuānyè — chuyên môn; 职业 zhíyè — nghề nghiệp.',paragraphs:[
 ['林美在服装店工作，常常帮助客人选裙子。她喜欢画画，可是还没有学过专业设计。','Lín Měi zài fúzhuāngdiàn gōngzuò, chángcháng bāngzhù kèrén xuǎn qúnzi. Tā xǐhuan huà huà, kěshì hái méiyǒu xué guo zhuānyè shèjì.','Lâm Mỹ làm ở cửa hàng quần áo, thường giúp khách chọn váy. Cô thích vẽ nhưng chưa học thiết kế chuyên nghiệp.'],
 ['一天，她遇见老周来给女儿买生日礼物。林美不但问了颜色，还问她平时喜欢穿什么。','Yì tiān, tā yùjiàn Lǎo Zhōu lái gěi nǚ’ér mǎi shēngrì lǐwù. Lín Měi bùdàn wèn le yánsè, hái wèn tā píngshí xǐhuan chuān shénme.','Một hôm cô gặp chú Chu đến mua quà sinh nhật cho con gái. Lâm Mỹ không chỉ hỏi màu mà còn hỏi con gái chú thường thích mặc gì.'],
 ['她一边听一边画，半小时才完成一张草图。老周说，这张图符合女儿的习惯，但还需要让女儿自己看看。','Tā yìbiān tīng yìbiān huà, bàn xiǎoshí cái wánchéng yì zhāng cǎotú. Lǎo Zhōu shuō, zhè zhāng tú fúhé nǚ’ér de xíguàn, dàn hái xūyào ràng nǚ’ér zìjǐ kànkan.','Cô vừa nghe vừa vẽ, nửa giờ mới xong một phác thảo. Chú Chu nói bản này phù hợp thói quen của con gái nhưng vẫn cần cho con tự xem.'],
 ['这次经验让林美更相信自己的方向。她决定明年学习设计，先了解课程和费用。她还没有报名，也没有辞去现在的工作。','Zhè cì jīngyàn ràng Lín Měi gèng xiāngxìn zìjǐ de fāngxiàng. Tā juédìng míngnián xuéxí shèjì, xiān liǎojiě kèchéng hé fèiyòng. Tā hái méiyǒu bàomíng, yě méiyǒu cí qù xiànzài de gōngzuò.','Trải nghiệm khiến Lâm Mỹ tin hơn vào hướng đi. Cô quyết định năm sau học thiết kế, trước mắt tìm hiểu khóa học và chi phí. Cô chưa đăng ký, cũng chưa nghỉ việc hiện tại.'],
 ],core:['客人','裙子','遇见','不但','一边','完成','习惯','决定'],rule:'不但…还… bổ sung hai nội dung đã hỏi. 一边…一边… nói hai hành động đồng thời. 才 trong 半小时才完成 nhấn mạnh mất đến nửa giờ. 决定 học không đồng nghĩa 已经 học; đánh giá của người bố chưa thay được phản hồi của con gái.',pitfall:'Không suy rằng Lâm Mỹ đã trở thành nhà thiết kế hoặc con gái chú Chu đã thích mẫu. Trải nghiệm cung cấp lý do khám phá nghề, chưa chứng minh đủ năng lực hành nghề.',question:'Đến cuối bài, Lâm Mỹ đã làm việc nào?',choices:[['已经辞去工作。','Sai: chưa nghỉ việc.'],['完成了一张草图。','Đúng: đã hoàn thành phác thảo trong nửa giờ.'],['已经学完专业设计。','Sai: việc học là kế hoạch năm sau.']],answer:1,cloze:{prompt:'Điền cấu trúc vừa nghe vừa vẽ: 她一边听，___画。',answer:'一边',feedback:'一边…一边… biểu thị hai hoạt động đồng thời.'},transfer:'Minh làm quán ăn, thích chụp ảnh. Anh đã chụp thực đơn cho quán; chủ quán thấy rõ nhưng chưa hỏi khách. Anh định tháng sau tìm khóa ảnh, chưa đăng ký. Viết 4 câu tách sản phẩm, đánh giá và kế hoạch.',model:['小明在饭馆工作，喜欢拍照。他已经给饭馆的菜单拍了照片。老板觉得照片很清楚，但是还没有问客人的意见。小明打算下个月找摄影课，现在还没有报名。','Xiǎo Míng zài fànguǎn gōngzuò, xǐhuan pāi zhào. Tā yǐjīng gěi fànguǎn de càidān pāi le zhàopiàn. Lǎobǎn juéde zhàopiàn hěn qīngchu, dànshì hái méiyǒu wèn kèrén de yìjiàn. Xiǎo Míng dǎsuàn xià ge yuè zhǎo shèyǐng kè, xiànzài hái méiyǒu bàomíng.','Minh làm ở quán ăn và thích chụp ảnh. Anh đã chụp ảnh thực đơn cho quán. Chủ quán thấy ảnh rõ nhưng chưa hỏi ý khách. Minh định tháng sau tìm khóa nhiếp ảnh, hiện chưa đăng ký.'],criteria:['Ảnh thực đơn đã làm, khóa học chưa đăng ký.','Nhận xét của chủ quán không thay ý khách.','Không biến dự định tìm khóa thành hoàn thành khóa.']},
];
