import {readFileSync} from 'node:fs';
import type {PersonalNarrative} from './hsk3-personal-narratives';
type Sentence=[string,string,string];
const source=JSON.parse(readFileSync('content/drafts/hsk3-comparison-description-evaluation-narration-grammar-2026.07.json','utf8')) as {lessons:Array<{lessonId:string;modelNarration:{lines:Array<{hanzi:string;pinyin:string;vietnamese:string}>}}>} ;
const changes:Record<string,Record<number,Sentence>>={
 'lesson-01':{2:['山顶看上去还很远，我们决定先休息。','Shāndǐng kànshangqu hái hěn yuǎn, wǒmen juédìng xiān xiūxi.','Đỉnh núi trông còn xa, chúng tôi quyết định nghỉ trước.'],4:['第二天比第一天更暖，雨停以后，我们看山也看得更清楚了。','Dì èr tiān bǐ dì yī tiān gèng nuǎn, yǔ tíng yǐhòu, wǒmen kàn shān yě kàn de gèng qīngchu le.','Ngày thứ hai ấm hơn ngày đầu; sau khi mưa tạnh, chúng tôi nhìn núi rõ hơn.']},
 'lesson-02':{3:['一年以后，河边比以前更干净。居民说：“今天的空气清新得很。”','Yì nián yǐhòu, hébiān bǐ yǐqián gèng gānjìng. Jūmín shuō: “Jīntiān de kōngqì qīngxīn de hěn.”','Một năm sau, ven sông sạch hơn trước. Người dân nói: “Không khí hôm nay trong lành lắm.”']},
 'lesson-03':{
  1:['两种服务要求的材料一样，不过得到帮助的方式不同。','Liǎng zhǒng fúwù yāoqiú de cáiliào yíyàng, búguò dédào bāngzhù de fāngshì bù tóng.','Hai dịch vụ yêu cầu cùng loại giấy tờ, nhưng cách nhận hỗ trợ khác nhau.'],
  2:['对小林来说，网上服务跟现场服务一样方便。','Duì Xiǎo Lín láishuō, wǎngshàng fúwù gēn xiànchǎng fúwù yíyàng fāngbiàn.','Đối với Tiểu Lâm, dịch vụ trực tuyến tiện như dịch vụ tại chỗ.'],
  3:['他这周比较了两次办事的时间：现场服务不比网上服务慢，两次都用了十分钟。','Tā zhè zhōu bǐjiào le liǎng cì bànshì de shíjiān: xiànchǎng fúwù bù bǐ wǎngshàng fúwù màn, liǎng cì dōu yòng le shí fēnzhōng.','Tuần này cậu so thời gian hai lần làm thủ tục: tại chỗ không chậm hơn trực tuyến, cả hai lần đều mất mười phút.'],
  4:['今年九月，服务点比去年九月早开门半个小时，多接待了两百人。','Jīnnián jiǔ yuè, fúwùdiǎn bǐ qùnián jiǔ yuè zǎo kāimén bàn ge xiǎoshí, duō jiēdài le liǎngbǎi rén.','Tháng Chín năm nay, điểm dịch vụ mở sớm hơn tháng Chín năm trước nửa giờ và tiếp thêm hai trăm người.'],
 },
};
const p=(suffix:string):Sentence[]=>source.lessons.find(l=>l.lessonId.endsWith(suffix))!.modelNarration.lines.map((s,i)=>changes[suffix]?.[i]??[s.hanzi,s.pinyin,s.vietnamese]);
export const comparisonNarratives:PersonalNarrative[]=[
 {suffix:'lesson-01',goal:'So sánh hai ngày trên núi và phân biệt quan sát, dự đoán với dữ kiện đã xảy ra',support:'看起来 kànqǐlai / 看上去 kànshangqu — trông có vẻ; 山顶 shāndǐng — đỉnh núi; 越来越 — ngày càng. Đây là nhật ký giả định của hai ngày, không phải dữ liệu khí hậu cả vùng.',paragraphs:p('lesson-01'),core:['决定','清楚','山','更','先','比较'],rule:'越来越冷 mô tả một đặc điểm thay đổi theo thời gian. 越下越大 nối tiến trình mưa với mức mưa lớn dần. 看起来快要下雨了 là dự đoán từ mây; 下午雨越下越大 xác nhận mưa thật sự đã xảy ra. 第二天比第一天更暖 chỉ so hai ngày theo nhiệt độ.',pitfall:'Không so đỉnh núi với chân núi rồi kết luận khoảng cách khi chưa nêu người quan sát ở đâu. “Trông có vẻ” chưa phải kết quả đo. Hai ngày không chứng minh thời tiết nơi này luôn như vậy.',question:'Chi tiết nào xác nhận trời đã mưa, thay vì chỉ dự đoán?',choices:[['下午雨越下越大。','Đúng: mô tả mưa buổi chiều đang lớn dần.'],['看起来快要下雨了。','Sai: đây mới là dự đoán từ dấu hiệu.'],['山顶看上去还很远。','Sai: nhận xét khoảng cách nhìn thấy, không nói mưa.']],answer:0,cloze:{prompt:'Mưa càng lúc càng lớn: 雨越下___大。',answer:'越',feedback:'越下越大 nối tiến trình mưa với mức mưa lớn dần.'},transfer:'Viết nhật ký hai buổi: sáng mây đen hơn và trông có vẻ sắp mưa; chiều mưa thật và ngày càng lớn. Sáng hôm sau ấm hơn sáng trước. Chỉ kết luận trong hai ngày này, không nói khí hậu luôn vậy. Viết 4 câu.',model:['早上，云越来越黑，看起来快要下雨了。下午真的下雨了，雨越下越大。第二天早上比前一天早上更暖。这只是两天的情况，不代表这里的天气总是这样。','Zǎoshang, yún yuèláiyuè hēi, kànqǐlai kuàiyào xiàyǔ le. Xiàwǔ zhēn de xiàyǔ le, yǔ yuè xià yuè dà. Dì èr tiān zǎoshang bǐ qián yì tiān zǎoshang gèng nuǎn. Zhè zhǐ shì liǎng tiān de qíngkuàng, bù dàibiǎo zhèli de tiānqì zǒngshì zhèyàng.','Sáng mây ngày càng đen, có vẻ sắp mưa. Chiều mưa thật, càng lúc càng lớn. Sáng ngày hai ấm hơn sáng hôm trước. Đây chỉ là tình hình hai ngày, không đại diện thời tiết nơi này luôn vậy.'],criteria:['Tách dự đoán lúc sáng với mưa đã xảy ra chiều.','So cùng phương diện nhiệt độ ở hai buổi sáng.','Không khái quát hai ngày thành khí hậu.']},
 {suffix:'lesson-02',goal:'Mô tả cải thiện môi trường và giữ lại điều kiện mà vấn đề vẫn xuất hiện',support:'治理 zhìlǐ — cải thiện/xử lý; 居民 jūmín — người dân; 垃圾箱 lājīxiāng — thùng rác; 清新 qīngxīn — trong lành. Cảnh giả định; lời người dân không phải chỉ số đo chất lượng không khí.',paragraphs:p('lesson-02'),core:['环境','以前','变化','干净','树','以后'],rule:'在保护环境上 giới hạn phương diện; 在治理过程中 chỉ quá trình; 在…情况下 nêu điều kiện. 干净 hơn trước không có nghĩa hết mọi vấn đề. 得很 và 极了 đều nhấn mức độ nhưng đặt sau tính từ; giữ rõ đó là đánh giá của người nói.',pitfall:'Nhiều cây và thùng rác hơn chưa tự chứng minh nguyên nhân duy nhất làm môi trường tốt lên. Mưa lớn vẫn có rác. Cảm giác “không khí trong lành” không thay cho đo đạc.',question:'Nhận xét nào giữ đủ cả tiến bộ và hạn chế?',choices:[['河边比以前干净，但下大雨时还会有垃圾。','Đúng: giữ cải thiện và điều kiện còn vấn đề.'],['现在无论什么时候都没有垃圾。','Sai: mưa lớn vẫn xuất hiện rác.'],['增加垃圾箱证明所有空气问题都解决了。','Sai: không có bằng chứng giải quyết toàn bộ vấn đề không khí.']],answer:0,cloze:{prompt:'Giữ đúng mẫu tính từ + 得很: 空气清新___很。',answer:'得',feedback:'清新得很 nhấn mức độ; đây là lời nhận xét, không phải số đo.'},transfer:'Một công viên giả định trước đây ít thùng rác. Sau sáu tháng đặt thêm thùng và tổ chức dọn vệ sinh, lối đi sạch hơn; cuối tuần đông người vẫn còn rác. Viết 4 câu giữ tiến bộ, thời gian và giới hạn; không nói đã sạch tuyệt đối.',model:['这个公园以前垃圾箱很少。在改善环境的过程中，公园增加了垃圾箱，也组织大家打扫。六个月以后，路比以前更干净了。不过，周末人多的时候，路上还会有垃圾。','Zhège gōngyuán yǐqián lājīxiāng hěn shǎo. Zài gǎishàn huánjìng de guòchéng zhōng, gōngyuán zēngjiā le lājīxiāng, yě zǔzhī dàjiā dǎsǎo. Liù ge yuè yǐhòu, lù bǐ yǐqián gèng gānjìng le. Búguò, zhōumò rén duō de shíhou, lù shàng hái huì yǒu lājī.','Công viên trước ít thùng rác. Trong quá trình cải thiện môi trường, công viên thêm thùng và tổ chức dọn vệ sinh. Sáu tháng sau đường sạch hơn. Nhưng cuối tuần đông người vẫn có rác.'],criteria:['Sáu tháng là mốc so trước–sau.','Sạch hơn không chuyển thành sạch tuyệt đối.','Nêu rõ hạn chế khi cuối tuần đông người.']},
 {suffix:'lesson-03',goal:'Đọc so sánh dịch vụ mà không nhầm độ chênh với tổng số hay suy tốt hơn về mọi mặt',support:'材料 cáiliào — giấy tờ/tài liệu; 现场 xiànchǎng — tại chỗ; 接待 jiēdài — tiếp đón; 半个小时 — nửa giờ. Số liệu là tình huống giả định với cùng tháng để so.',paragraphs:p('lesson-03'),core:['服务','办法','帮助','一样','方便','只'],rule:'一样 cần xác định mặt giống: giấy tờ yêu cầu hay mức tiện. A不比B慢 chỉ phủ định A chậm hơn B; riêng văn bản cho thêm cả hai đều mười phút nên mới biết bằng nhau. 早开门半个小时 là mở sớm hơn nửa giờ; 多接待两百人 là tăng thêm 200, chưa cho tổng năm nay.',pitfall:'Không biến tăng thêm 200 người thành chỉ có 200 người. Tiểu Lâm thấy tiện như nhau không đại diện mọi người. Không kết luận mở sớm là nguyên nhân duy nhất của lượng khách tăng.',question:'Con số hai trăm trong văn bản có nghĩa gì?',choices:[['比去年九月多接待的人数。','Đúng: số người tăng thêm so cùng tháng năm trước.'],['今年九月接待的总人数。','Sai: chưa có tổng của tháng Chín năm nay.'],['网上服务比现场服务多接待的人数。','Sai: số liệu so hai năm, không so hai kênh dịch vụ.']],answer:0,cloze:{prompt:'Giữ nghĩa không chậm hơn: 现场服务___比网上服务慢。',answer:'不',feedback:'不比…慢 chưa tự có nghĩa bằng nhau; dữ kiện hai lần mười phút mới xác định bằng nhau ở đây.'},transfer:'Thư viện A tháng Tám năm nay mở sớm hơn cùng tháng năm ngoái một giờ, đón thêm 100 người. Lan thấy phòng mới yên tĩnh như phòng cũ. Viết 3–4 câu, phân biệt chênh lệch với tổng, và nhận xét cá nhân với kết luận chung.',model:['今年八月，图书馆比去年八月早开门一个小时，也多接待了一百人。我们还不知道今年八月的总人数。小兰觉得新阅览室跟旧阅览室一样安静。这些信息不能说明所有方面都更好。','Jīnnián bā yuè, túshūguǎn bǐ qùnián bā yuè zǎo kāimén yí ge xiǎoshí, yě duō jiēdài le yìbǎi rén. Wǒmen hái bù zhīdào jīnnián bā yuè de zǒng rénshù. Xiǎo Lán juéde xīn yuèlǎnshì gēn jiù yuèlǎnshì yíyàng ānjìng. Zhèxiē xìnxī bù néng shuōmíng suǒyǒu fāngmiàn dōu gèng hǎo.','Tháng Tám năm nay thư viện mở sớm một giờ và đón thêm 100 người so cùng tháng năm ngoái. Ta chưa biết tổng năm nay. Lan thấy phòng đọc mới yên tĩnh như phòng cũ. Thông tin đó không nói mọi mặt đều tốt hơn.'],criteria:['Một giờ và 100 người là chênh lệch.','So cùng tháng, không trộn hai kênh dịch vụ.','Yên tĩnh như nhau là nhận xét của Lan ở một phương diện.']},
];
