import type {PersonalNarrative} from './hsk3-personal-narratives';

/** Original local-study manuscripts. Diagrams, not stock scenes, carry the facts. */
export const societyNarratives:PersonalNarrative[]=[
  {
    suffix:'modern-life',goal:'Theo dõi một thói quen đổi cách thực hiện mà không biến mất',
    support:'每周 měi zhōu — mỗi tuần; 平日 píngrì — ngày thường; 周末 zhōumò — cuối tuần. Câu chuyện chỉ nói về gia đình này.',
    paragraphs:[
      ['以前，爷爷每天早上看报纸，了解当天的新闻。他不喜欢用手机看字。','Yǐqián, yéye měitiān zǎoshang kàn bàozhǐ, liǎojiě dàngtiān de xīnwén. Tā bù xǐhuan yòng shǒujī kàn zì.','Trước đây, sáng nào ông cũng đọc báo để biết tin trong ngày. Ông không thích đọc chữ trên điện thoại.'],
      ['后来，那份报纸改成每周出一次。爷爷想每天看新闻，孙女就教他把手机上的字放大。','Hòulái, nà fèn bàozhǐ gǎi chéng měi zhōu chū yí cì. Yéye xiǎng měitiān kàn xīnwén, sūnnǚ jiù jiāo tā bǎ shǒujī shàng de zì fàng dà.','Sau đó, tờ báo ấy chuyển sang ra mỗi tuần một lần. Ông muốn xem tin mỗi ngày nên cháu gái dạy ông phóng to chữ trên điện thoại.'],
      ['刚开始，他看得很慢。练了几天以后，他能自己找到想看的新闻了。','Gāng kāishǐ, tā kàn de hěn màn. Liàn le jǐ tiān yǐhòu, tā néng zìjǐ zhǎodào xiǎng kàn de xīnwén le.','Lúc đầu ông đọc rất chậm. Sau vài ngày tập, ông đã tự tìm được tin mình muốn xem.'],
      ['现在，爷爷平日用手机，周末还是看报纸。家里的习惯有了变化，可是他没有放弃自己喜欢的报纸。','Xiànzài, yéye píngrì yòng shǒujī, zhōumò háishi kàn bàozhǐ. Jiālǐ de xíguàn yǒu le biànhuà, kěshì tā méiyǒu fàngqì zìjǐ xǐhuan de bàozhǐ.','Bây giờ ngày thường ông dùng điện thoại, cuối tuần vẫn đọc báo. Thói quen gia đình có thay đổi, nhưng ông không bỏ tờ báo mình thích.'],
    ],core:['以前','报纸','了解','新闻','变化','习惯'],
    rule:'以前 → 后来 → 刚开始 → 现在 đánh dấu bốn giai đoạn. 改成每周出一次 là tần suất xuất bản thay đổi; không có nghĩa báo ngừng hẳn. 还是 cho biết thói quen đọc báo tiếp tục ở cuối tuần.',
    pitfall:'Đừng viết “ông đã bỏ báo giấy” hoặc “mọi người lớn tuổi đều không thích điện thoại”. Chỉ có hành vi của ông trong câu chuyện.',
    question:'Kết luận nào được đoạn cuối xác nhận?',choices:[
      ['爷爷平日用手机，周末还看报纸。','Đúng: cách mới và thói quen cũ cùng tồn tại.'],
      ['爷爷再也不看报纸了。','Sai: cuối tuần ông vẫn đọc báo.'],
      ['报纸现在每天出一次。','Sai: tờ báo chuyển sang ra mỗi tuần một lần.'],
    ],answer:0,
    cloze:{prompt:'Điền từ diễn tả thói quen còn tiếp tục: 周末爷爷___看报纸。',answer:'还是',feedback:'还是 nghĩa là vẫn; chi tiết cuối tuần đọc báo không mất đi.'},
    transfer:'Một khu dân cư trước đây dán lịch hoạt động trên giấy mỗi ngày. Nay giấy chỉ cập nhật mỗi tuần, bảng điện tử cập nhật hằng ngày. Tiểu Trần xem bảng điện tử ngày thường và vẫn xem giấy vào Chủ nhật. Viết 3–4 câu nêu thay đổi và điều vẫn giữ, không kể lại chuyện đọc báo của ông.',
    model:['以前，小区每天贴一张纸，告诉大家有什么活动。现在，纸每周换一次，电子屏每天更新。小陈平日看电子屏，星期天还是看纸上的安排。方法变了，他还是看纸。','Yǐqián, xiǎoqū měitiān tiē yì zhāng zhǐ, gàosu dàjiā yǒu shénme huódòng. Xiànzài, zhǐ měi zhōu huàn yí cì, diànzǐ píng měitiān gēngxīn. Xiǎo Chén píngrì kàn diànzǐ píng, Xīngqītiān háishi kàn zhǐ shàng de ānpái. Fāngfǎ biàn le, tā háishi kàn zhǐ.','Trước đây khu dân cư dán tờ giấy mới hằng ngày để báo hoạt động. Nay giấy thay mỗi tuần, bảng điện tử cập nhật hằng ngày. Tiểu Trần xem bảng điện tử ngày thường, Chủ nhật vẫn xem lịch trên giấy. Cách làm đổi nhưng anh vẫn xem giấy.'],
    criteria:['Tách tần suất cập nhật giấy và bảng điện tử.','Nêu đúng ngày thường và Chủ nhật.','Không viết Tiểu Trần bỏ hẳn giấy.'],
  },
  {
    suffix:'city-development',goal:'Đọc thay đổi công năng một tòa nhà và phân biệt hiện tại với kế hoạch',
    support:'社区 shèqū — khu dân cư; 一层 yì céng — tầng một; 开放 kāifàng — mở cửa; 意见 yìjiàn — ý kiến. Sơ đồ tầng trong bài chỉ mô tả tòa nhà giả định.',
    paragraphs:[
      ['城市里有一座三层旧房子，空了两年。附近的人希望它能为社区服务。','Chéngshì lǐ yǒu yí zuò sān céng jiù fángzi, kōng le liǎng nián. Fùjìn de rén xīwàng tā néng wèi shèqū fúwù.','Trong thành phố có căn nhà cũ ba tầng bỏ trống hai năm. Người ở gần mong nó phục vụ khu dân cư.'],
      ['工作人员先问居民的意见，再决定每层做什么。年轻人建议留一个能一起读书的地方。','Gōngzuò rényuán xiān wèn jūmín de yìjiàn, zài juédìng měi céng zuò shénme. Niánqīng rén jiànyì liú yí ge néng yìqǐ dú shū de dìfang.','Nhân viên hỏi ý kiến cư dân trước rồi mới quyết định công năng từng tầng. Người trẻ đề nghị có nơi đọc sách cùng nhau.'],
      ['改好以后，一层能办卡，二层可以读书，三层有小教室。房子上周已经开放，居民现在可以进去。','Gǎi hǎo yǐhòu, yì céng néng bàn kǎ, èr céng kěyǐ dú shū, sān céng yǒu xiǎo jiàoshì. Fángzi shàng zhōu yǐjīng kāifàng, jūmín xiànzài kěyǐ jìnqù.','Sau khi sửa xong, tầng một làm thẻ, tầng hai đọc sách, tầng ba có phòng học nhỏ. Nhà đã mở cửa tuần trước; hiện cư dân có thể vào.'],
      ['下个月，工作人员还要问大家用得方不方便，再解决新的问题。服务已经开始，检查效果却还没有做。','Xià ge yuè, gōngzuò rényuán hái yào wèn dàjiā yòng de fāng bù fāngbiàn, zài jiějué xīn de wèntí. Fúwù yǐjīng kāishǐ, jiǎnchá xiàoguǒ què hái méiyǒu zuò.','Tháng sau nhân viên sẽ hỏi mọi người dùng có tiện không, rồi giải quyết vấn đề mới. Dịch vụ đã bắt đầu nhưng việc kiểm hiệu quả vẫn chưa thực hiện.'],
    ],core:['城市','旧','服务','年轻','办','解决'],
    rule:'先…再… chỉ thứ tự hỏi ý kiến rồi quyết định. 已经开放 là đã mở; 下个月还要 hỏi ý kiến là kế hoạch. Ba tầng có ba công năng khác nhau, không gộp mọi việc vào tầng một.',
    pitfall:'Không nói cư dân đã đánh giá hiệu quả sau một tháng. Cũng không đổi tầng đọc sách thành tầng làm thẻ.',
    question:'Việc nào chưa xảy ra?',choices:[
      ['工作人员下个月问大家用得方不方便。','Đúng: việc hỏi sau khi sử dụng được dự kiến vào tháng sau.'],
      ['房子上周开放了。','Sai: nhà đã mở tuần trước.'],
      ['二层可以读书。','Sai: tầng hai hiện đã dùng để đọc sách.'],
    ],answer:0,
    cloze:{prompt:'Điền từ cho hành động đã xảy ra: 房子上周___开放了。',answer:'已经',feedback:'已经 đánh dấu việc mở cửa đã xảy ra, khác kế hoạch hỏi ý kiến tháng sau.'},
    transfer:'Thị trấn khác đang sửa nhà kho cũ thành một điểm phục vụ: tầng một dự định có phòng đọc, tầng hai dự định có lớp học. Công trình chưa xong và tháng sau mới mở. Viết 3–4 câu đúng trạng thái kế hoạch, không viết đã mở như tòa nhà trong bài.',
    model:['镇上有一座旧房子，大家想把它改成服务中心。一层计划有阅览室，二层计划有教室。现在还没有改好，下个月才开放。居民现在不能进去使用。','Zhèn shàng yǒu yí zuò jiù fángzi, dàjiā xiǎng bǎ tā gǎi chéng fúwù zhōngxīn. Yì céng jìhuà yǒu yuèlǎnshì, èr céng jìhuà yǒu jiàoshì. Xiànzài hái méiyǒu gǎi hǎo, xià ge yuè cái kāifàng. Jūmín xiànzài bù néng jìnqù shǐyòng.','Thị trấn có căn nhà cũ; mọi người muốn sửa thành trung tâm phục vụ. Tầng một dự định có phòng đọc, tầng hai có lớp học. Hiện chưa sửa xong, tháng sau mới mở; cư dân chưa thể vào dùng.'],
    criteria:['Tầng một đọc, tầng hai học của địa điểm mới.','Giữ trạng thái chưa sửa xong, tháng sau mới mở.','Không nói dịch vụ mới đã bắt đầu.'],
  },
  {
    suffix:'arts-activities',goal:'Kể quá trình chuẩn bị buổi diễn mà không bỏ qua việc nghỉ ngơi',
    support:'彩排 cǎipái — tổng duyệt; 嗓子 sǎngzi — cổ họng; 休息 xiūxi — nghỉ ngơi; 展览 zhǎnlǎn — triển lãm; 评选 píngxuǎn — bình chọn. Buổi diễn là tình huống giả định, sơ đồ không cung cấp điểm số.',
    paragraphs:[
      ['学校周五有晚会，小兰和朋友准备一个音乐表演。小兰每天认真练习，很想把歌唱好。','Xuéxiào Zhōuwǔ yǒu wǎnhuì, Xiǎo Lán hé péngyou zhǔnbèi yí ge yīnyuè biǎoyǎn. Xiǎo Lán měitiān rènzhēn liànxí, hěn xiǎng bǎ gē chàng hǎo.','Trường có liên hoan vào thứ Sáu; Tiểu Lan và bạn chuẩn bị một tiết mục nhạc. Cô luyện nghiêm túc mỗi ngày và muốn hát tốt.'],
      ['周三彩排以后，她的嗓子有点不舒服，还想再练很久。老师请她先休息，明天再练。','Zhōusān cǎipái yǐhòu, tā de sǎngzi yǒudiǎn bù shūfu, hái xiǎng zài liàn hěn jiǔ. Lǎoshī qǐng tā xiān xiūxi, míngtiān zài liàn.','Sau buổi tổng duyệt thứ Tư, cổ họng cô hơi khó chịu nhưng vẫn muốn tập lâu thêm. Giáo viên đề nghị nghỉ trước, mai luyện tiếp.'],
      ['小兰听了老师的话。周四，她和朋友练了两遍，还留时间休息。','Xiǎo Lán tīng le lǎoshī de huà. Zhōusì, tā hé péngyou liàn le liǎng biàn, hái liú shíjiān xiūxi.','Tiểu Lan nghe lời giáo viên. Thứ Năm cô tập cùng bạn hai lượt và vẫn dành thời gian nghỉ.'],
      ['周五的表演顺利完成，朋友们拍了照片。老师说，认真准备重要，照顾自己和同伴也重要。','Zhōuwǔ de biǎoyǎn shùnlì wánchéng, péngyoumen pāi le zhàopiàn. Lǎoshī shuō, rènzhēn zhǔnbèi zhòngyào, zhàogù zìjǐ hé tóngbàn yě zhòngyào.','Tiết mục thứ Sáu hoàn thành thuận lợi, bạn bè chụp ảnh. Giáo viên nói chuẩn bị nghiêm túc quan trọng, chăm sóc bản thân và bạn diễn cũng quan trọng.'],
    ],core:['晚会','音乐','表演','认真','照片','重要'],
    rule:'周三、周四、周五 giữ thứ tự tổng duyệt → điều chỉnh cách tập → biểu diễn. 再练很久 là ý định lúc thứ Tư, không phải việc đã làm. 顺利完成 chỉ hoàn thành thuận lợi; văn bản không đưa điểm hay giải thưởng.',
    pitfall:'Không nói Tiểu Lan bị bệnh nặng hoặc đạt giải nhất. Đừng biến lời muốn tập thêm thành việc đã tập thêm.',
    question:'Sau lời khuyên của giáo viên, Tiểu Lan đã làm gì?',choices:[
      ['周四练了两遍，也留时间休息。','Đúng: thứ Năm cô tập hai lượt và có thời gian nghỉ.'],
      ['周三一直练到半夜。','Sai: văn bản chỉ nói cô muốn tập lâu thêm.'],
      ['马上退出了周五的表演。','Sai: cô vẫn biểu diễn vào thứ Sáu.'],
    ],answer:0,
    cloze:{prompt:'Điền từ giữ thứ tự lời khuyên: 老师请她先休息，明天___练。',answer:'再',feedback:'再练 là luyện tiếp sau khi nghỉ; không phải đã luyện thêm ngay tối thứ Tư.'},
    transfer:'Nhóm mỹ thuật chuẩn bị triển lãm thứ Bảy. Thứ Năm Tiểu Minh muốn vẽ cả tối nhưng mỏi mắt; cô giáo bảo nghỉ. Thứ Sáu em hoàn thiện tranh sau hai giờ làm việc. Thứ Bảy tranh được trưng bày, chưa có kết quả bình chọn. Viết 4 câu tách ý định, việc đã làm và kết quả.',
    model:['星期四，小明想画一晚上，可是眼睛有点累。老师请他先休息。星期五，他画了两个小时，完成了画。星期六，大家在展览上看到了他的画，还没有人告诉他评选结果。','Xīngqīsì, Xiǎo Míng xiǎng huà yì wǎnshang, kěshì yǎnjing yǒudiǎn lèi. Lǎoshī qǐng tā xiān xiūxi. Xīngqīwǔ, tā huà le liǎng ge xiǎoshí, wánchéng le huà. Xīngqīliù, dàjiā zài zhǎnlǎn shàng kàn dào le tā de huà, hái méiyǒu rén gàosu tā píngxuǎn jiéguǒ.','Thứ Năm Tiểu Minh muốn vẽ cả tối nhưng hơi mỏi mắt; giáo viên bảo nghỉ. Thứ Sáu em vẽ hai giờ và hoàn thành tranh. Thứ Bảy mọi người thấy tranh ở triển lãm; chưa ai báo kết quả bình chọn.'],
    criteria:['Không biến muốn vẽ cả tối thành việc đã làm.','Giữ đúng hai giờ hoàn thiện vào thứ Sáu.','Trưng bày không đồng nghĩa đạt giải.'],
  },
  {
    suffix:'sports-introduction',goal:'Hiểu quy trình một buổi thử môn thể thao, không nhầm với thi đấu',
    support:'球拍 qiúpāi — vợt; 教练 jiàoliàn — huấn luyện viên; 初学者 chūxuézhě — người mới học. Buổi thử không thu thập thông tin cá nhân thật.',
    paragraphs:[
      ['社区周六办网球体验活动，欢迎第一次参加的人。报名时只要写名字，不用写比赛成绩。','Shèqū Zhōuliù bàn wǎngqiú tǐyàn huódòng, huānyíng dì yī cì cānjiā de rén. Bàomíng shí zhǐ yào xiě míngzi, bú yòng xiě bǐsài chéngjì.','Khu dân cư tổ chức buổi thử quần vợt thứ Bảy, đón người tham gia lần đầu. Đăng ký chỉ cần ghi tên, không cần thành tích thi đấu.'],
      ['大家先选择合适的球拍。教练告诉初学者怎样拿球拍，再请他们两个人一组练习。','Dàjiā xiān xuǎnzé héshì de qiúpāi. Jiàoliàn gàosu chūxuézhě zěnyàng ná qiúpāi, zài qǐng tāmen liǎng ge rén yì zǔ liànxí.','Mọi người chọn vợt phù hợp trước. Huấn luyện viên chỉ người mới cách cầm vợt, rồi mời họ tập theo cặp.'],
      ['小丁开始接不到球，就放慢动作，多练了几次。教练说，先学会把球打过去，比打得快更重要。','Xiǎo Dīng kāishǐ jiē bú dào qiú, jiù fàng màn dòngzuò, duō liàn le jǐ cì. Jiàoliàn shuō, xiān xuéhuì bǎ qiú dǎ guòqù, bǐ dǎ de kuài gèng zhòngyào.','Ban đầu Tiểu Đinh không đỡ được bóng nên làm chậm động tác và tập thêm vài lần. Huấn luyện viên nói học đánh bóng qua trước quan trọng hơn đánh nhanh.'],
      ['活动结束时，小丁已经能和同伴打几个来回。他没有参加比赛，只是决定下周再来练习。','Huódòng jiéshù shí, Xiǎo Dīng yǐjīng néng hé tóngbàn dǎ jǐ ge láihuí. Tā méiyǒu cānjiā bǐsài, zhǐshì juédìng xià zhōu zài lái liànxí.','Cuối buổi Tiểu Đinh đã đánh qua lại với bạn được vài lượt. Cậu không thi đấu; chỉ quyết định tuần sau tập tiếp.'],
    ],core:['网球','参加','选择','练习','重要'],
    rule:'先…再… nêu trình tự chọn vợt → học cầm → luyện cặp. 已经能 nói kỹ năng tại cuối buổi; 下周再来 là dự định. 体验活动 là buổi thử, không phải 比赛.',
    pitfall:'Không tự thêm hộ chiếu/số điện thoại vào đăng ký. Đánh qua lại vài lượt không chứng minh cậu thắng trận hay thành vận động viên chuyên nghiệp.',
    question:'Câu nào phân biệt đúng buổi thử và cuộc thi?',choices:[
      ['小丁练了几个来回，没有参加比赛。','Đúng: bài nêu rõ chỉ thử và luyện, không thi đấu.'],
      ['小丁赢了正式的网球比赛。','Sai: không có trận thi đấu.'],
      ['报名以前每个人要写自己的比赛成绩。','Sai: đăng ký không cần thành tích.'],
    ],answer:0,
    cloze:{prompt:'Điền từ nối bước sau: 大家先选球拍，___两个人一组练习。',answer:'再',feedback:'先…再… chỉ thứ tự: chọn vợt trước, luyện theo cặp sau.'},
    transfer:'Buổi thử cầu lông mới: người tham gia chọn vợt, nghe hướng dẫn cầm vợt, tập theo cặp. Tiểu Vân chưa đánh tốt nhưng dự định tuần sau quay lại. Không có thi đấu hoặc giải thưởng. Viết 3–4 câu đúng trình tự và giới hạn.',
    model:['社区办了羽毛球体验活动。大家先选球拍，再听教练讲怎样拿，最后两个人一组练习。小云还打得不太好，打算下周再来。今天没有比赛，也没有人得奖。','Shèqū bàn le yǔmáoqiú tǐyàn huódòng. Dàjiā xiān xuǎn qiúpāi, zài tīng jiàoliàn jiǎng zěnyàng ná, zuìhòu liǎng ge rén yì zǔ liànxí. Xiǎo Yún hái dǎ de bú tài hǎo, dǎsuàn xià zhōu zài lái. Jīntiān méiyǒu bǐsài, yě méiyǒu rén dé jiǎng.','Khu dân cư tổ chức buổi thử cầu lông. Mọi người chọn vợt, nghe cách cầm, rồi tập theo cặp. Tiểu Vân chưa đánh tốt và dự định tuần sau quay lại. Hôm nay không thi đấu hay có giải thưởng.'],
    criteria:['Giữ thứ tự chọn vợt, nghe hướng dẫn, luyện theo cặp.','Tuần sau mới là dự định.','Không bịa trận đấu hoặc giải thưởng.'],
  },
  {
    suffix:'competition-report',goal:'Đọc tỉ số và diễn biến để phân biệt kết quả với lời bình',
    support:'篮球 lánqiú — bóng rổ; 甲队 jiǎ duì — đội A; 乙队 yǐ duì — đội B; 上半场 shàng bàn chǎng — hiệp đầu; 进攻 jìngōng — tấn công. Tỉ số giả định chỉ phục vụ bài đọc.',
    paragraphs:[
      ['昨天学校有一场篮球比赛，甲队和乙队九点开始打球。上半场结束时，甲队六分，乙队八分。','Zuótiān xuéxiào yǒu yì chǎng lánqiú bǐsài, Jiǎ duì hé Yǐ duì jiǔ diǎn kāishǐ dǎ qiú. Shàng bàn chǎng jiéshù shí, Jiǎ duì liù fēn, Yǐ duì bā fēn.','Hôm qua trường có trận bóng rổ; hai đội A và B bắt đầu lúc 9 giờ. Hết hiệp đầu, A được 6 điểm, B được 8 điểm.'],
      ['甲队队长请大家先看清楚位置，再一起进攻。他们没有马上得分，但是一直坚持这个办法。','Jiǎ duì duìzhǎng qǐng dàjiā xiān kàn qīngchu wèizhi, zài yìqǐ jìngōng. Tāmen méiyǒu mǎshàng dé fēn, dànshì yìzhí jiānchí zhège bànfǎ.','Đội trưởng A đề nghị xem rõ vị trí trước rồi cùng tấn công. Họ chưa ghi điểm ngay nhưng tiếp tục theo cách đó.'],
      ['后来，甲队得了六分，乙队又得了两分。比赛结束时，比分是十二比十，甲队赢了。','Hòulái, Jiǎ duì dé le liù fēn, Yǐ duì yòu dé le liǎng fēn. Bǐsài jiéshù shí, bǐfēn shì shí’èr bǐ shí, Jiǎ duì yíng le.','Sau đó A ghi thêm 6 điểm, B thêm 2. Kết thúc trận, tỉ số là 12–10 và A thắng.'],
      ['这份报告写了开始、改变办法和最后的结果。队长说，坚持很重要；这句话是他的看法，不是另一个比赛结果。','Zhè fèn bàogào xiě le kāishǐ, gǎibiàn bànfǎ hé zuìhòu de jiéguǒ. Duìzhǎng shuō, jiānchí hěn zhòngyào; zhè jù huà shì tā de kànfǎ, bú shì lìng yí ge bǐsài jiéguǒ.','Bản tin ghi điểm đầu, việc đổi cách chơi và kết quả cuối. Đội trưởng nói kiên trì rất quan trọng; đây là lời nhận xét, không phải một kết quả trận đấu khác.'],
    ],core:['比赛','得分','坚持','结束','最后'],
    rule:'6–8 là tỉ số hết hiệp đầu, 12–10 là cuối trận. “甲队得了六分，乙队又得了两分” là điểm ghi thêm: 6+6=12, 8+2=10. Đội trưởng nhận xét về sự kiên trì; câu đó là ý kiến, không thay thế dữ kiện tỉ số.',
    pitfall:'Không đọc 6–8 là kết quả chung cuộc. Không nói đổi cách chơi lập tức ghi điểm; văn bản phủ nhận điều đó. Một trận không chứng minh đội A luôn thắng.',
    question:'Cuối trận, điều gì được tỉ số xác nhận?',choices:[
      ['甲队十二分，乙队十分，甲队赢了。','Đúng: 12–10 là tỉ số cuối và A thắng.'],
      ['乙队八分，所以乙队赢了。','8 là điểm của B ở cuối hiệp đầu, không phải chung cuộc.'],
      ['甲队换办法以后马上得分。','Văn bản nói họ không ghi điểm ngay.'],
    ],answer:0,
    cloze:{prompt:'Điền từ chỉ sự tiếp tục dù chưa ghi điểm ngay: 他们没有马上得分，但是一直___这个办法。',answer:'坚持',feedback:'坚持 cho biết vẫn tiếp tục cách chơi sau khi chưa ghi điểm ngay.'},
    transfer:'Trận mới: hết hiệp đầu đội C 6 điểm, đội D 8 điểm. Hiệp sau C ghi thêm 3, D ghi thêm 3; chung cuộc C 9–11 D. C có cải thiện nhưng không thắng. Viết bản tin 3–4 câu gồm điểm đầu, điểm thêm và kết quả, không chép kết quả A thắng.',
    model:['另一场比赛上半场结束时，丙队六分，丁队八分。后来丙队得了三分，丁队也得了三分。最后比分是九比十一，丁队赢了。丙队得分增加了，可是没有赢。','Lìng yì chǎng bǐsài shàng bàn chǎng jiéshù shí, Bǐng duì liù fēn, Dīng duì bā fēn. Hòulái Bǐng duì dé le sān fēn, Dīng duì yě dé le sān fēn. Zuìhòu bǐfēn shì jiǔ bǐ shíyī, Dīng duì yíng le. Bǐng duì dé fēn zēngjiā le, kěshì méiyǒu yíng.','Ở trận khác, hết hiệp đầu C được 6 và D được 8 điểm. Sau đó mỗi đội thêm 3; chung cuộc là 9–11, D thắng. C tăng điểm nhưng không thắng.'],
    criteria:['Tính đúng 6+3=9 và 8+3=11.','Nêu D thắng, C không thắng.','Phân biệt tiến bộ về điểm với thắng trận.'],
  },
];
