import type {SurvivalManuscript} from './survival-batch-manuscripts';
export const referenceManuscripts:SurvivalManuscript[]=[{
 id:'hsk2-reference-description-comparison-lesson-01',focus:'Xác định người, vật, vị trí và đơn vị đếm',
 scene:'Bạn đứng trước cổng nhìn vào trường. Hiệu sách đối diện trường; bệnh viện phía trái trường theo hướng nhìn của bạn. Nhóm có ba giáo viên, mỗi người mua hai gói trà. Ba người đều tự chọn trà, chưa biết tổng số lá trà.',
 support:'书店 shūdiàn: hiệu sách · 医院 yīyuàn: bệnh viện · 茶 chá: trà · 自己选择 zìjǐ xuǎnzé: tự chọn. Đọc điểm nhìn trước khi xác định trái/phải.',
 rule:'Luôn xác định mốc và đối tượng trước: 学校对面 lấy trường làm mốc; 左边 theo điểm nhìn đã cho; 每位老师 xét từng người; 两包茶 đếm gói, không phải lá. Các trang sau luyện từng cách quy chiếu và lượng từ.',
 pitfall:'Ba giáo viên mỗi người hai gói là sáu gói, không phải sáu giáo viên hoặc sáu lá trà. Đối diện không phải trong trường.',
 dialogue:[['书店在哪儿？','Shūdiàn zài nǎr?','Hiệu sách ở đâu?'],['在学校对面，医院在学校左边。','Zài xuéxiào duìmiàn, yīyuàn zài xuéxiào zuǒbian.','Đối diện trường; bệnh viện ở bên trái trường.'],['有几位老师买茶？','Yǒu jǐ wèi lǎoshī mǎi chá?','Có mấy giáo viên mua trà?'],['三位，每位老师买两包。','Sān wèi, měi wèi lǎoshī mǎi liǎng bāo.','Ba người, mỗi người mua hai gói.'],['谁帮他们选茶？','Shéi bāng tāmen xuǎn chá?','Ai giúp họ chọn trà?'],['他们自己选。','Tāmen zìjǐ xuǎn.','Họ tự chọn.']],
 question:'Từ dữ kiện nhóm mua trà, điều nào xác định được?',choices:[['三位老师一共买六包茶。','Đúng: 3 người × 2 gói = 6 gói, giữ đúng đơn vị.'],['一共有六位老师。','Sáu là số gói, không phải số giáo viên.'],['一共买六片茶叶。','Không biết số lá trà trong mỗi gói; không đổi đơn vị.']],answer:0,
 transfer:'Cảnh mới: nhìn vào thư viện, quán trà bên phải, cửa hàng đối diện. Bốn học sinh mỗi người mua một gói trà và tự chọn. Viết ba câu vị trí và số lượng, không dùng lại ba giáo viên/sáu gói.',
 model:['茶店在图书馆右边，商店在图书馆对面。四名学生每人买一包茶，一共四包。他们自己选。','Chádiàn zài túshūguǎn yòubian, shāngdiàn zài túshūguǎn duìmiàn. Sì míng xuésheng měi rén mǎi yì bāo chá, yígòng sì bāo. Tāmen zìjǐ xuǎn.','Quán trà bên phải thư viện, cửa hàng đối diện; bốn học sinh mỗi người một gói, tổng bốn gói; họ tự chọn.'],criteria:['Giữ mốc thư viện và hướng phải theo người nhìn.','Bốn học sinh, không phải giáo viên.','Tổng bốn gói, không suy số lá.','自己 chỉ chính nhóm học sinh tự chọn.']
},{
 id:'hsk2-reference-description-comparison-lesson-02',focus:'Phân biệt số lần, thời gian và người nhận hành động',
 scene:'Linh từng đến Bắc Kinh hai lần; hôm nay làm từ 8 giờ sáng đến 5 giờ chiều rồi gọi cho mẹ. Hôm nay lạnh hơn hôm qua. Các thông tin không cho biết tổng thời gian Linh ở Bắc Kinh hoặc mẹ là người gọi trước.',
 support:'北京 Běijīng: Bắc Kinh · 早上 zǎoshang: buổi sáng · 下午 xiàwǔ: buổi chiều · 次 cì: lần · 小时 xiǎoshí: tiếng.',
 rule:'次数 trả lời mấy lần; 从…到… nêu khoảng mốc; 给/跟 xác định người nhận hoặc người giao tiếp; 比 so hai đối tượng. 地 trước động từ và 得 sau động từ cùng đọc de nhưng không thay chữ cho nhau.',
 pitfall:'Hai lần đến Bắc Kinh không bằng hai năm ở đó; 我给妈妈打电话 không có nghĩa mẹ gọi cho tôi.',
 dialogue:[['你去过北京几次？','Nǐ qùguo Běijīng jǐ cì?','Bạn từng đến Bắc Kinh mấy lần?'],['两次。','Liǎng cì.','Hai lần.'],['你今天从几点工作到几点？','Nǐ jīntiān cóng jǐ diǎn gōngzuò dào jǐ diǎn?','Hôm nay bạn làm từ mấy giờ đến mấy giờ?'],['从早上八点到下午五点，然后给妈妈打电话。','Cóng zǎoshang bā diǎn dào xiàwǔ wǔ diǎn, ránhòu gěi māma dǎ diànhuà.','Từ 8 giờ sáng đến 5 giờ chiều, sau đó gọi cho mẹ.'],['今天天气怎么样？','Jīntiān tiānqì zěnmeyàng?','Hôm nay thời tiết thế nào?'],['今天比昨天冷。','Jīntiān bǐ zuótiān lěng.','Hôm nay lạnh hơn hôm qua.']],
 question:'Điều nào giữ đúng loại thông tin và đối tượng?',choices:[['她在北京住了两年。','Đề chỉ nêu hai lần đến, chưa nêu thời lượng sống.'],['她去过北京两次，今天给妈妈打电话。','Đúng: số lần và người nhận cuộc gọi không bị đổi.'],['昨天比今天冷。','Đảo chiều so sánh, trái dữ kiện.']],answer:1,
 transfer:'Vai mới từng đến Thượng Hải ba lần; hôm nay học từ 9 giờ sáng đến 12 giờ trưa, rồi gọi cho bố; hôm nay nóng hơn hôm qua. Viết bốn câu giữ đúng các quan hệ.',
 model:['我去过上海三次。我今天从早上九点学习到中午十二点。然后我给爸爸打电话。今天比昨天热。','Wǒ qùguo Shànghǎi sān cì. Wǒ jīntiān cóng zǎoshang jiǔ diǎn xuéxí dào zhōngwǔ shíèr diǎn. Ránhòu wǒ gěi bàba dǎ diànhuà. Jīntiān bǐ zuótiān rè.','Đã đến Thượng Hải ba lần; học 9:00–12:00, rồi gọi cho bố; hôm nay nóng hơn hôm qua.'],criteria:['Ba lần không đổi thành ba năm.','Giữ khoảng 9 giờ sáng đến 12 giờ trưa.','Tôi gọi, bố nhận.','Hôm nay nóng hơn, không đảo hai ngày.']
},{
 id:'hsk2-reference-description-comparison-lesson-03',focus:'Theo dõi món được nhắc đến và người sở hữu',
 scene:'Trên bàn có hai chiếc áo: áo đỏ của Mai, áo trắng của Lan. Mai mua áo đỏ hôm qua. Một món cơm đã nấu xong nhưng chưa biết ai nấu. Hai bạn chọn uống trà hay cà phê; đang nói thứ hai hôm nay.',
 support:'红的 hóng de: chiếc màu đỏ đã biết · 白的 bái de: chiếc màu trắng đã biết · 买 mǎi: mua · 做好 zuòhǎo: làm xong/sẵn sàng.',
 rule:'的 thay danh từ chỉ khi đã rõ vật: 红的 là áo đỏ trong cảnh này. 我昨天买的衣服 có mệnh đề đứng trước danh từ. 饭做好了 nói kết quả của cơm, không định danh người nấu. 还是 hỏi lựa chọn, 还是…吧 đề nghị sau cân nhắc.',
 pitfall:'Biết áo đỏ của Mai chưa đủ suy áo trắng cũng của Mai. Biết cơm xong chưa đủ suy Mai nấu.',
 dialogue:[['红的是谁的？','Hóng de shì shéi de?','Chiếc đỏ của ai?'],['是我的，我昨天买的。白的是兰的。','Shì wǒ de, wǒ zuótiān mǎi de. Bái de shì Lán de.','Của tôi, tôi mua hôm qua. Chiếc trắng của Lan.'],['饭做好了吗？谁做的？','Fàn zuòhǎo le ma? Shéi zuò de?','Cơm xong chưa? Ai nấu?'],['做好了，但是我不知道谁做的。','Zuòhǎo le, dànshì wǒ bù zhīdào shéi zuò de.','Xong rồi nhưng tôi không biết ai nấu.'],['你喝茶还是喝咖啡？','Nǐ hē chá háishi hē kāfēi?','Bạn uống trà hay cà phê?'],['我还是喝茶吧。','Wǒ háishi hē chá ba.','Tôi chọn uống trà thì hơn.']],
 question:'Điều nào không thêm thông tin chưa biết?',choices:[['饭是梅做的。','Chưa biết người nấu; không gán cho Mai.'],['两件衣服都是梅的。','Áo trắng là của Lan.'],['红的是梅的，白的是兰的；饭做好了。','Đúng: giữ sở hữu và kết quả, không bịa người nấu.']],answer:2,
 transfer:'Hai quyển sách: quyển xanh của Long, quyển đen của bạn; bạn mua quyển đen tuần trước. Trà đã pha xong, chưa biết ai pha. Viết ba câu đủ sở hữu, mốc mua và điều chưa biết; không giữ danh từ áo.',
 model:['绿色的书是龙的，黑色的是我的。黑色的是我上周买的。茶准备好了，但是我不知道是谁准备的。','Lǜsè de shū shì Lóng de, hēisè de shì wǒ de. Hēisè de shì wǒ shàng zhōu mǎi de. Chá zhǔnbèi hǎo le, dànshì wǒ bù zhīdào shì shéi zhǔnbèi de.','Sách xanh của Long, sách đen của tôi; tôi mua sách đen tuần trước. Trà đã sẵn nhưng chưa biết ai chuẩn bị.'],criteria:['Nêu sách trước khi dùng 的 thay danh từ.','Giữ sách xanh/Long, sách đen/tôi.','Mốc mua tuần trước, không hôm qua.','Không bịa người chuẩn bị trà.']
},{
 id:'hsk2-reference-description-comparison-lesson-04',focus:'So sánh đúng chiều và giữ mức chính xác của số liệu',
 scene:'An 20 tuổi, chị An 23 tuổi. An cao 1,60 m, chị cao 1,70 m. Lớp ở tầng ba và có hơn ba mươi học sinh, chưa kiểm đếm chính xác. Chị chạy nhanh hơn An nhưng không bận bằng An.',
 support:'厘米 límǐ: centimet · 米 mǐ: mét · 岁 suì: tuổi · 三十多 sānshí duō: hơn ba mươi · 准确 zhǔnquè: chính xác.',
 rule:'比…大三岁 nêu chênh ba tuổi, không phải tuổi tuyệt đối. 没有…忙 là không bận bằng, không có nghĩa rảnh hoàn toàn. 三十多 và 十几个 là ước lượng; không tự đổi thành 35 hoặc 15. 三楼 nói tầng ba, không phải ba tòa nhà.',
 pitfall:'Chị hơn ba tuổi không có nghĩa chị ba tuổi. Lớp hơn ba mươi người chưa đủ chứng minh chính xác 35 người.',
 dialogue:[['你姐姐比你大几岁？','Nǐ jiějie bǐ nǐ dà jǐ suì?','Chị hơn bạn mấy tuổi?'],['三岁。我二十岁，她二十三岁。','Sān suì. Wǒ èrshí suì, tā èrshísān suì.','Ba tuổi. Tôi 20, chị 23.'],['她也比你高吗？','Tā yě bǐ nǐ gāo ma?','Chị cũng cao hơn bạn không?'],['对，高十厘米，但是她没有我这么忙。','Duì, gāo shí límǐ, dànshì tā méiyǒu wǒ zhème máng.','Đúng, cao hơn 10 cm nhưng chị không bận bằng tôi.'],['你们的教室在哪儿？有多少学生？','Nǐmen de jiàoshì zài nǎr? Yǒu duōshao xuésheng?','Lớp ở đâu? Có bao nhiêu học sinh?'],['在三楼，有三十多名学生。','Zài sān lóu, yǒu sānshí duō míng xuésheng.','Tầng ba, hơn ba mươi học sinh.']],
 question:'Kết luận nào đúng và không biến số ước lượng thành số chính xác?',choices:[['姐姐二十三岁；班里有三十多名学生。','Đúng: tuổi chị tính được chính xác, sĩ số vẫn giữ ước lượng.'],['姐姐三岁，班里三十五人。','Ba là chênh lệch, còn 35 chưa có dữ kiện.'],['姐姐比安忙。','Đề nói chị không bận bằng An.']],answer:0,
 transfer:'Bạn 18 tuổi, anh 22; bạn cao 1,65 m, anh 1,73 m. Anh chạy chậm hơn bạn và bận hơn bạn. Lớp tầng bốn có hơn hai mươi học sinh. Viết bốn câu giữ chênh lệch, chiều so sánh và ước lượng.',
 model:['哥哥比我大四岁，高八厘米。他跑得没有我快，但是比我忙。我们的教室在四楼。班里有二十多名学生。','Gēge bǐ wǒ dà sì suì, gāo bā límǐ. Tā pǎo de méiyǒu wǒ kuài, dànshì bǐ wǒ máng. Wǒmen de jiàoshì zài sì lóu. Bān lǐ yǒu èrshí duō míng xuésheng.','Anh hơn bốn tuổi, cao hơn 8 cm; chạy không nhanh bằng tôi nhưng bận hơn; lớp tầng bốn, hơn hai mươi học sinh.'],criteria:['Chênh bốn tuổi và 8 cm.','Anh chạy chậm hơn nhưng bận hơn.','Tầng bốn, không phải bốn tòa.','Giữ hơn hai mươi, không tự đặt 25.']
},{
 id:'hsk2-sentence-reconstruction-lesson-01',focus:'Dựng câu từ chủ thể, thời gian, hành động và đối tượng',
 scene:'Bạn sửa tin nhắn cho người bạn sắp tới khách sạn: khách sạn không xa ga; ngày mai bạn có kỳ thi; tan học sẽ về nhà ngay. Trước khi ghép chữ, cần xác định từng câu nói về ai và điều gì.',
 support:'酒店 jiǔdiàn: khách sạn · 离 lí: cách · 车站 chēzhàn: ga/trạm · 下课以后 xiàkè yǐhòu: sau khi tan học.',
 rule:'Tìm chủ thể và vị ngữ trước. Thời gian có thể đứng đầu hoặc sau chủ thể ở nhiều câu; bài order sẽ nói rõ vị trí cần dùng, không tuyên bố chỉ một thứ tự đúng trong tiếng Trung. 离…不远 giữ mốc khoảng cách; 每天 trước động từ giữ tần suất.',
 pitfall:'Không ghép câu chỉ theo thứ tự dịch từng từ Việt. “Khách sạn không xa ga” chưa cho biết cách đi hoặc số phút.',
 dialogue:[['酒店离车站远吗？','Jiǔdiàn lí chēzhàn yuǎn ma?','Khách sạn xa ga không?'],['不远，但是我不知道走几分钟。','Bù yuǎn, dànshì wǒ bù zhīdào zǒu jǐ fēnzhōng.','Không xa, nhưng tôi không biết đi mấy phút.'],['你明天做什么？','Nǐ míngtiān zuò shénme?','Ngày mai bạn làm gì?'],['明天我要考试。','Míngtiān wǒ yào kǎoshì.','Mai tôi phải thi.'],['下课以后呢？','Xiàkè yǐhòu ne?','Sau khi tan học thì sao?'],['下课以后我就回家。','Xiàkè yǐhòu wǒ jiù huí jiā.','Tan học tôi về nhà ngay.']],
 question:'Theo tin nhắn, câu nào không thêm hoặc đổi thông tin?',choices:[['酒店离车站有五分钟的路。','Chưa biết số phút; không tự thêm năm phút.'],['酒店离车站不远，明天我要考试。','Đúng: giữ khoảng cách định tính và lịch ngày mai.'],['我已经考完试了。','Thi ngày mai chưa phải đã thi xong.']],answer:1,
 transfer:'Viết tin nhắn mới ba câu: thư viện xa nhà; ngày mai bạn học tiếng Trung; sau giờ học bạn đến cửa hàng. Đặt 明天 ở đầu câu thứ hai. Không nêu thời gian đi đường vì chưa biết.',
 model:['图书馆离我家很远。明天我要学汉语。下课以后我去商店。','Túshūguǎn lí wǒ jiā hěn yuǎn. Míngtiān wǒ yào xué Hànyǔ. Xiàkè yǐhòu wǒ qù shāngdiàn.','Thư viện xa nhà tôi. Mai tôi học tiếng Trung. Sau giờ học tôi đến cửa hàng.'],criteria:['Thư viện xa nhà, không giữ khách sạn/ga.','明天 đầu câu thứ hai.','Đi cửa hàng sau giờ học, không về nhà.','Không bịa số phút.']
},{
 id:'hsk2-sentence-reconstruction-lesson-02',focus:'Giữ kết quả và trình tự khi dựng câu',
 scene:'Trước chuyến đi tuần sau, bạn đã mua vé máy bay nhưng chưa xếp hành lý. Hiện bạn muốn người bạn nói chậm hơn một chút để nghe rõ. Thói quen chạy bộ mỗi ngày không cho biết bạn đang chạy lúc nói.',
 support:'行李 xíngli: hành lý · 收拾 shōushi: sắp xếp/thu dọn · 以前 yǐqián: trước khi · 慢一点儿 màn yìdiǎnr: chậm hơn chút.',
 rule:'买好了机票 giữ kết quả mua xong. 旅游以前 là mốc trước chuyến đi, chưa chứng minh chuyến đi đã xảy ra. 请说慢一点儿 là yêu cầu thay đổi tốc độ; 有点儿慢 lại là đánh giá hơi chậm. 每天都跑步 là thói quen.',
 pitfall:'Đã mua vé không đồng nghĩa đã đi du lịch hoặc đã chuẩn bị xong mọi thứ. Không đổi lời yêu cầu thành nhận xét trái mục đích.',
 dialogue:[['你下周去旅游，机票买好了吗？','Nǐ xià zhōu qù lǚyóu, jīpiào mǎihǎo le ma?','Tuần sau bạn du lịch, mua xong vé chưa?'],['买好了，但是还没收拾行李。','Mǎihǎo le, dànshì hái méi shōushi xíngli.','Mua xong rồi nhưng chưa xếp hành lý.'],['你现在能听清楚吗？','Nǐ xiànzài néng tīng qīngchu ma?','Bây giờ bạn nghe rõ không?'],['请说慢一点儿。','Qǐng shuō màn yìdiǎnr.','Xin nói chậm hơn một chút.'],['你每天都跑步吗？','Nǐ měitiān dōu pǎobù ma?','Bạn chạy mỗi ngày à?'],['对，但是我现在没在跑步。','Duì, dànshì wǒ xiànzài méi zài pǎobù.','Đúng, nhưng giờ tôi không đang chạy.']],
 question:'Kết luận nào giữ đúng trạng thái?',choices:[['我已经旅游回来了。','Đề nói chuyến đi tuần sau, chưa đi rồi về.'],['我每天跑步，所以现在正在跑步。','Thói quen không chứng minh hành động hiện tại.'],['机票买好了，行李还没收拾。','Đúng: một việc xong, việc khác chưa làm.']],answer:2,
 transfer:'Chuyến tàu ngày mai: đã xếp hành lý, chưa mua vé tàu. Nhờ người bạn nói to hơn chút vì nghe chưa rõ. Viết ba câu, giữ thứ tự thông tin và không chép lại trạng thái cũ.',
 model:['我明天坐火车去旅行。行李收拾好了，但是还没买火车票。请说大声一点儿，我没听清楚。','Wǒ míngtiān zuò huǒchē qù lǚxíng. Xíngli shōushi hǎo le, dànshì hái méi mǎi huǒchēpiào. Qǐng shuō dàshēng yìdiǎnr, wǒ méi tīng qīngchu.','Mai đi tàu; hành lý đã xếp, vé chưa mua. Xin nói to hơn chút, tôi chưa nghe rõ.'],criteria:['Ngày mai đi tàu, không nói đã trở về.','Hành lý xong, vé chưa mua.','Yêu cầu to hơn, không chậm hơn như mẫu.','Giữ lời nhờ lịch sự và lý do nghe chưa rõ.']
},{
 id:'hsk2-sentence-reconstruction-lesson-03',focus:'Dựng chuỗi câu giữ quan hệ và quan điểm của người nói',
 scene:'Minh thấy bóng đá thú vị hơn bóng rổ, đây là sở thích của Minh. Tuy trời mưa Minh vẫn đến lớp. Ngày mai thi nên tối nay Minh học ở nhà và đề nghị giúp bạn ôn bài.',
 support:'我觉得 wǒ juéde: tôi thấy · 有意思 yǒuyìsi: thú vị · 复习 fùxí: ôn bài · 让 ràng: để/cho phép trong lời đề nghị.',
 rule:'Nối câu theo quan hệ: 虽然…但是… cho nhượng bộ, 因为…所以… cho nguyên nhân. 让我帮你 giữ tôi giúp bạn. Với so sánh sở thích, 我觉得 xác định đó là đánh giá của người nói chứ không sự thật chung.',
 pitfall:'Không đảo nguyên nhân và hệ quả. Không bỏ người nói rồi tuyên bố bóng đá khách quan luôn thú vị hơn bóng rổ.',
 dialogue:[['你觉得足球和篮球怎么样？','Nǐ juéde zúqiú hé lánqiú zěnmeyàng?','Bạn thấy bóng đá và bóng rổ thế nào?'],['我觉得足球比篮球有意思。','Wǒ juéde zúqiú bǐ lánqiú yǒuyìsi.','Tôi thấy bóng đá thú vị hơn bóng rổ.'],['今天下雨，你还来上课吗？','Jīntiān xiàyǔ, nǐ hái lái shàngkè ma?','Hôm nay mưa, bạn vẫn đến lớp à?'],['虽然下雨，但是我还是来了。','Suīrán xiàyǔ, dànshì wǒ háishi lái le.','Tuy mưa nhưng tôi vẫn đến.'],['今晚一起出去吗？','Jīnwǎn yìqǐ chūqù ma?','Tối nay cùng ra ngoài không?'],['因为明天考试，所以我要在家学习。让我帮你复习吧。','Yīnwèi míngtiān kǎoshì, suǒyǐ wǒ yào zài jiā xuéxí. Ràng wǒ bāng nǐ fùxí ba.','Vì mai thi nên tôi học ở nhà. Để tôi giúp bạn ôn nhé.']],
 question:'Câu nào giữ đúng phạm vi và quan hệ?',choices:[['他觉得足球更有意思；因为明天考试，所以今晚学习。','Đúng: giữ đánh giá của Minh và lý do học.'],['所有人都觉得足球比篮球有意思。','Đã biến sở thích một người thành tất cả mọi người.'],['因为今晚学习，所以明天才有考试。','Đảo quan hệ nhân quả.']],answer:0,
 transfer:'Vai mới thích bóng rổ hơn bóng đá; tuy mệt vẫn ôn bài; vì ngày mai đi du lịch nên tối nay chuẩn bị hành lý. Đề nghị giúp bạn xếp đồ. Viết bốn câu với quan điểm và quan hệ rõ.',
 model:['我觉得篮球比足球有意思。虽然很累，但是我还是复习了。因为明天去旅行，所以今晚我要准备行李。让我帮你收拾东西吧。','Wǒ juéde lánqiú bǐ zúqiú yǒuyìsi. Suīrán hěn lèi, dànshì wǒ háishi fùxí le. Yīnwèi míngtiān qù lǚxíng, suǒyǐ jīnwǎn wǒ yào zhǔnbèi xíngli. Ràng wǒ bāng nǐ shōushi dōngxi ba.','Tôi thấy bóng rổ thú vị hơn; tuy mệt vẫn ôn; vì mai du lịch nên tối nay chuẩn bị hành lý; để tôi giúp bạn xếp đồ.'],criteria:['Giữ 我觉得 và đảo sở thích sang bóng rổ.','Tuy mệt vẫn ôn là nhượng bộ.','Du lịch là lý do chuẩn bị hành lý.','Tôi giúp bạn, không đảo người giúp/nhận.']
}];
