/** Lesson-specific replacements where the dictionary example did not teach the target use. */
export const survivalExamples:Record<string,[string,string,string]>={
 '请':['请坐。','Qǐng zuò.','Mời ngồi.'],
 '女士':['那位女士是老师。','Nà wèi nǚshì shì lǎoshī.','Người phụ nữ kia là giáo viên.'],
 '岁':['我二十岁。','Wǒ èrshí suì.','Tôi hai mươi tuổi.'],
 '有':['我有一个妹妹。','Wǒ yǒu yí ge mèimei.','Tôi có một em gái.'],
 '爱':['我爱我的家人。','Wǒ ài wǒ de jiārén.','Tôi yêu người nhà của mình.'],
 '大':['这件衣服很大。','Zhè jiàn yīfu hěn dà.','Chiếc áo này lớn.'],
 '小':['这件衣服有点儿小。','Zhè jiàn yīfu yǒudiǎnr xiǎo.','Chiếc áo này hơi nhỏ.'],
 '有点儿':['这件衣服有点儿大。','Zhè jiàn yīfu yǒudiǎnr dà.','Chiếc áo này hơi lớn.'],
 '不':['我不是老师。','Wǒ bú shì lǎoshī.','Tôi không phải giáo viên.'],
 '对':['对，我是学生。','Duì, wǒ shì xuésheng.','Đúng, tôi là học sinh.'],
 '还':['我还没有时间。','Wǒ hái méiyǒu shíjiān.','Tôi vẫn chưa có thời gian.'],
 '会':['我会说汉语。','Wǒ huì shuō Hànyǔ.','Tôi biết nói tiếng Trung.'],
 '没有':['我今天没有时间。','Wǒ jīntiān méiyǒu shíjiān.','Hôm nay tôi không có thời gian.'],
 '说':['我想说汉语。','Wǒ xiǎng shuō Hànyǔ.','Tôi muốn nói tiếng Trung.'],
 '要':['我要去学校。','Wǒ yào qù xuéxiào.','Tôi định đi đến trường.'],
 '再':['我明天再来。','Wǒ míngtiān zài lái.','Ngày mai tôi lại đến.'],
 '呢':['我很好，你呢？','Wǒ hěn hǎo, nǐ ne?','Tôi khỏe, còn bạn?'],
 '问':['我想问你一件事。','Wǒ xiǎng wèn nǐ yí jiàn shì.','Tôi muốn hỏi bạn một việc.'],
 '一下':['我想问一下。','Wǒ xiǎng wèn yíxià.','Tôi muốn hỏi một chút.'],
 '了':['我起床了。','Wǒ qǐchuáng le.','Tôi dậy rồi.'],
 '起床':['我每天七点起床。','Wǒ měitiān qī diǎn qǐchuáng.','Tôi dậy lúc bảy giờ mỗi ngày.'],
};
