/** Original guided practice; every example is editable in the Studio payload. */
export const survivalPractice: Record<string, {
  pattern: string; example: [string,string,string]; prompt: string;
  answers: string[]; explanation: string;
}> = {
  'survival-1': {pattern:'谢谢。→ 不客气。／对不起。→ 没关系。',
    example:['谢谢你！不客气。','Xièxie nǐ! Bú kèqi.','Cảm ơn bạn! Không có gì.'],
    prompt:'Người A: 谢谢你！ Người B: ____。 Điền lời đáp cảm ơn đã học, không phải lời đáp xin lỗi.',
    answers:['不客气'],explanation:'不客气 đáp lời cảm ơn. 没关系 đáp lời xin lỗi hoặc trấn an trong ngữ cảnh khác; không thay cho cặp đang luyện.'},
  'survival-2': {pattern:'Đại từ + 是 + danh từ; đại từ + 也 + 是 + danh từ',
    example:['我们是学生。她们也是学生。','Wǒmen shì xuésheng. Tāmen yě shì xuésheng.','Chúng tôi là học sinh. Họ (nhóm nữ) cũng là học sinh.'],
    prompt:'Nhóm nữ được nhắc tới không có người nói. Điền đại từ: ____也是学生。',
    answers:['她们'],explanation:'她们 chỉ nhóm nữ được nói đến. 我们 phải bao gồm người nói; 你们 chỉ nhóm người nghe.'},
  'survival-3': {pattern:'我叫 + tên。／我 + số tuổi + 岁。',
    example:['我叫李梅。我二十一岁。','Wǒ jiào Lǐ Méi. Wǒ èrshíyī suì.','Tôi tên Lý Mai. Tôi hai mươi mốt tuổi.'],
    prompt:'Điền động từ hỏi cách viết: 你的名字怎么____？',
    answers:['写'],explanation:'怎么写 hỏi viết thế nào. 什么名字 hỏi tên gì; 怎么样 hỏi tình trạng hoặc đánh giá.'},
  'survival-4': {pattern:'这是我的 + quan hệ。／我有 + số lượng + thành viên。',
    example:['这是我的姐姐。我有一个弟弟。','Zhè shì wǒ de jiějie. Wǒ yǒu yí ge dìdi.','Đây là chị gái tôi. Tôi có một em trai.'],
    prompt:'Trong gia đình giả định, cô ấy là chị gái lớn tuổi hơn bạn. Điền từ quan hệ: 她是我的____。',
    answers:['姐姐'],explanation:'姐姐 là chị gái lớn tuổi hơn mình; 妹妹 là em gái. 女儿 dùng từ điểm nhìn cha mẹ.'},
  'survival-5': {pattern:'我有 + số + 只 + 猫／狗。',
    example:['我有两只猫。','Wǒ yǒu liǎng zhī māo.','Tôi có hai con mèo.'],
    prompt:'Điền lượng từ đếm chó trong mẫu đã học: 我有两____狗。',
    answers:['只'],explanation:'Dùng 只 (zhī) cho mèo/chó trong các mẫu này. 两 đứng trước lượng từ khi nói hai con.'},
  'survival-6': {pattern:'我觉得 + chủ ngữ + 很 + tính từ。',
    example:['我觉得这件衣服很漂亮。','Wǒ juéde zhè jiàn yīfu hěn piàoliang.','Tôi thấy chiếc áo này đẹp.'],
    prompt:'Điền 好看 hoặc 好听 để nói giai điệu bài hát nghe hay: 这首歌很____。',
    answers:['好听'],explanation:'Đang nhận xét âm thanh nên dùng 好听. 很 trong câu tính từ không bắt buộc luôn dịch là “rất”.'},
  'survival-7': {pattern:'我会 + kỹ năng。／我没有 + danh từ。',
    example:['我会说汉语，但是今天没有时间。','Wǒ huì shuō Hànyǔ, dànshì jīntiān méiyǒu shíjiān.','Tôi biết nói tiếng Trung nhưng hôm nay không có thời gian.'],
    prompt:'Điền 没有 hoặc 不 để nói không có thời gian: 我今天____时间。',
    answers:['没有'],explanation:'没有 phủ định 有. Không nói 不有; việc không có thời gian không đồng nghĩa không biết nói.'},
  'survival-8': {pattern:'Thời gian + 再 + 给 + người + 打电话 + 吧。',
    example:['我明天再给你打电话吧。','Wǒ míngtiān zài gěi nǐ dǎ diànhuà ba.','Ngày mai tôi gọi lại cho bạn nhé.'],
    prompt:'Điền từ chỉ lần gọi sau, dùng 再 hoặc 在: 我明天____给你打电话吧。',
    answers:['再'],explanation:'再 chỉ một lần tiếp theo trong tương lai ở đây. 在 có cùng âm zài nhưng không thay được 再 trong mẫu này.'},
  'survival-9': {pattern:'我起床了。／我还没起床。',
    example:['我还没起床。','Wǒ hái méi qǐchuáng.','Tôi vẫn chưa dậy.'],
    prompt:'Điền 还没 hoặc 了 để nói vẫn chưa dậy: 我____起床。',
    answers:['还没'],explanation:'还没起床 nói việc vẫn chưa xảy ra; mẫu này không giữ 了 cuối câu. 起床了 lại nói đã dậy trong tình huống đang hỏi.'},
};
