export {
  CURRENT_CONTENT_CLOSED_ALPHA_ELIGIBLE,
  CURRENT_CONTENT_MANIFEST_SHA256,
  CURRENT_CONTENT_PACKAGE_IDENTITY as CURRENT_CONTENT_PACKAGE,
  CURRENT_CONTENT_PRODUCTION_ELIGIBLE,
} from "./currentContentIdentity";
