export const ADVANCED_EXTENSION_VERSION = "advanced-extension-2026.08.1";
export const ADVANCED_EXTENSION_SOURCE_ID = "cc-cedict-2026-08-21-selection";

// Tuple fields: simplified, meaningVi, partOfSpeech, exampleHanzi,
// examplePinyin, exampleMeaningVi, optional CC-CEDICT sense hint.
export const ADVANCED_EXTENSION_GROUPS = [
  {
    id: "digital-life",
    titleVi: "Đời sống số an toàn",
    titleZh: "数字生活",
    objectiveVi: "Thao tác tài khoản, dữ liệu và quyền riêng tư bằng tiếng Trung hiện đại.",
    entries: [
      ["验证码", "mã xác minh", "danh từ", "输入验证码", "Shūrù yànzhèngmǎ", "nhập mã xác minh"],
      ["二维码", "mã QR", "danh từ", "扫描二维码", "Sǎomiáo èrwéimǎ", "quét mã QR"],
      ["社交媒体", "mạng xã hội", "danh từ", "使用社交媒体", "Shǐyòng shèjiāo méitǐ", "sử dụng mạng xã hội"],
      ["应用程序", "ứng dụng; chương trình", "danh từ", "安装应用程序", "Ānzhuāng yìngyòng chéngxù", "cài đặt ứng dụng"],
      ["操作系统", "hệ điều hành", "danh từ", "更新操作系统", "Gēngxīn cāozuò xìtǒng", "cập nhật hệ điều hành"],
      ["浏览器", "trình duyệt", "danh từ", "打开浏览器", "Dǎkāi liúlǎnqì", "mở trình duyệt"],
      ["云端", "đám mây; hệ thống lưu trữ trực tuyến", "danh từ", "保存到云端", "Bǎocún dào yúnduān", "lưu lên đám mây"],
      ["文件夹", "thư mục", "danh từ", "新建文件夹", "Xīnjiàn wénjiànjiā", "tạo thư mục mới"],
      ["备份", "sao lưu; bản sao lưu", "động từ/danh từ", "自动备份", "Zìdòng bèifèn", "tự động sao lưu"],
      ["隐私", "quyền riêng tư; chuyện riêng", "danh từ", "保护个人隐私", "Bǎohù gèrén yǐnsī", "bảo vệ quyền riêng tư cá nhân"],
      ["账号", "tài khoản", "danh từ", "注册账号", "Zhùcè zhànghào", "đăng ký tài khoản"],
      ["登录", "đăng nhập", "động từ", "登录账号", "Dēnglù zhànghào", "đăng nhập tài khoản"],
      ["上传", "tải lên", "động từ", "上传文件", "Shàngchuán wénjiàn", "tải tệp lên"],
      ["下载", "tải xuống", "động từ", "下载资料", "Xiàzǎi zīliào", "tải tài liệu xuống", "to download"],
      ["扫描", "quét; scan", "động từ", "扫描文件", "Sǎomiáo wénjiàn", "quét tài liệu"],
      ["链接", "đường liên kết; liên kết", "danh từ/động từ", "打开链接", "Dǎkāi liànjiē", "mở đường liên kết"],
      ["流量", "dữ liệu di động; lưu lượng", "danh từ", "节省手机流量", "Jiéshěng shǒujī liúliàng", "tiết kiệm dữ liệu di động"],
      ["订阅", "đăng ký theo dõi; gói đăng ký", "động từ/danh từ", "订阅播客", "Dìngyuè bōkè", "đăng ký theo dõi podcast"],
    ],
    grammar: ["先……，再……", "Trước hết làm việc thứ nhất, sau đó mới làm việc thứ hai.", "先备份文件，再更新操作系统。", "Xiān bèifèn wénjiàn, zài gēngxīn cāozuò xìtǒng.", "Hãy sao lưu tệp trước rồi mới cập nhật hệ điều hành."],
    dialogue: [
      ["A", "这个链接打不开，我也收不到验证码。", "Zhège liànjiē dǎbukāi, wǒ yě shōubudào yànzhèngmǎ.", "Liên kết này không mở được, tôi cũng không nhận được mã xác minh."],
      ["B", "先检查手机流量，再重新登录账号。", "Xiān jiǎnchá shǒujī liúliàng, zài chóngxīn dēnglù zhànghào.", "Hãy kiểm tra dữ liệu di động trước rồi đăng nhập lại tài khoản."],
      ["A", "需要先备份文件吗？", "Xūyào xiān bèifèn wénjiàn ma?", "Có cần sao lưu tệp trước không?"],
      ["B", "需要，保存到云端以后再更新系统。", "Xūyào, bǎocún dào yúnduān yǐhòu zài gēngxīn xìtǒng.", "Có, sau khi lưu lên đám mây hãy cập nhật hệ thống."],
    ],
  },
  {
    id: "workplace",
    titleVi: "Công việc và hồ sơ nghề nghiệp",
    titleZh: "职场事务",
    objectiveVi: "Trao đổi về hồ sơ, hợp đồng, chi phí và đánh giá công việc.",
    entries: [
      ["薪水", "lương; tiền công", "danh từ", "讨论薪水", "Tǎolùn xīnshuǐ", "thảo luận về lương"],
      ["简历", "sơ yếu lý lịch; CV", "danh từ", "准备简历", "Zhǔnbèi jiǎnlì", "chuẩn bị CV"],
      ["实习", "thực tập", "động từ/danh từ", "参加实习", "Cānjiā shíxí", "tham gia thực tập"],
      ["合同", "hợp đồng", "danh từ", "签合同", "Qiān hétong", "ký hợp đồng"],
      ["工作量", "khối lượng công việc", "danh từ", "控制工作量", "Kòngzhì gōngzuòliàng", "kiểm soát khối lượng công việc"],
      ["报销", "thanh toán lại; hoàn chi phí", "động từ", "申请报销", "Shēnqǐng bàoxiāo", "đề nghị hoàn chi phí"],
      ["发票", "hoá đơn", "danh từ", "请开发票", "Qǐng kāi fāpiào", "xin hãy xuất hoá đơn"],
      ["预算", "ngân sách; dự toán", "danh từ", "调整预算", "Tiáozhěng yùsuàn", "điều chỉnh ngân sách"],
      ["主管", "người phụ trách; quản lý trực tiếp", "danh từ", "部门主管", "Bùmén zhǔguǎn", "quản lý bộ phận"],
      ["绩效", "hiệu suất; kết quả công việc", "danh từ", "考核绩效", "Kǎohé jìxiào", "đánh giá hiệu suất"],
      ["升职", "thăng chức", "động từ/danh từ", "获得升职", "Huòdé shēngzhí", "được thăng chức"],
    ],
    grammar: ["只要……，就……", "Chỉ cần điều kiện phía trước được đáp ứng thì kết quả phía sau sẽ xảy ra.", "只要准备好简历，就可以申请实习。", "Zhǐyào zhǔnbèi hǎo jiǎnlì, jiù kěyǐ shēnqǐng shíxí.", "Chỉ cần chuẩn bị xong CV là có thể ứng tuyển thực tập."],
    dialogue: [
      ["A", "主管让我明天以前交预算报告。", "Zhǔguǎn ràng wǒ míngtiān yǐqián jiāo yùsuàn bàogào.", "Quản lý yêu cầu tôi nộp báo cáo ngân sách trước ngày mai."],
      ["B", "你的工作量是不是太大了？", "Nǐ de gōngzuòliàng shìbushì tài dà le?", "Khối lượng công việc của bạn có quá lớn không?"],
      ["A", "还好，发票整理完就能申请报销。", "Hái hǎo, fāpiào zhěnglǐ wán jiù néng shēnqǐng bàoxiāo.", "Cũng ổn, sắp xếp xong hoá đơn là có thể đề nghị hoàn chi phí."],
      ["B", "记得签合同以前看清楚薪水和绩效要求。", "Jìde qiān hétong yǐqián kàn qīngchu xīnshuǐ hé jìxiào yāoqiú.", "Nhớ xem kỹ lương và yêu cầu hiệu suất trước khi ký hợp đồng."],
    ],
  },
  {
    id: "services",
    titleVi: "Dịch vụ và thủ tục hằng ngày",
    titleZh: "生活服务",
    objectiveVi: "Xử lý đặt lịch, bảo hành, giao nhận và khiếu nại trong đời sống.",
    entries: [
      ["预约", "đặt lịch; đặt chỗ", "động từ/danh từ", "在线预约", "Zàixiàn yùyuē", "đặt lịch trực tuyến"],
      ["挂号", "đăng ký khám; lấy số khám", "động từ", "医院挂号", "Yīyuàn guàhào", "đăng ký khám ở bệnh viện", "hospital"],
      ["柜台", "quầy giao dịch", "danh từ", "服务柜台", "Fúwù guìtái", "quầy dịch vụ"],
      ["手续费", "phí thủ tục; phí xử lý", "danh từ", "支付手续费", "Zhīfù shǒuxùfèi", "trả phí thủ tục"],
      ["收据", "biên lai; phiếu thu", "danh từ", "保留收据", "Bǎoliú shōujù", "giữ lại biên lai"],
      ["退款", "hoàn tiền; khoản hoàn", "động từ/danh từ", "申请退款", "Shēnqǐng tuìkuǎn", "yêu cầu hoàn tiền"],
      ["保修", "bảo hành", "động từ/danh từ", "一年保修", "Yì nián bǎoxiū", "bảo hành một năm"],
      ["维修", "sửa chữa; bảo trì", "động từ/danh từ", "设备维修", "Shèbèi wéixiū", "sửa chữa thiết bị"],
      ["包裹", "bưu kiện; gói hàng", "danh từ", "领取包裹", "Lǐngqǔ bāoguǒ", "nhận bưu kiện"],
      ["取件", "đến nhận hàng/tài liệu", "động từ", "通知取件", "Tōngzhī qǔjiàn", "thông báo đến nhận hàng"],
      ["配送", "phân phối và giao hàng", "động từ/danh từ", "当天配送", "Dàngtiān pèisòng", "giao trong ngày"],
      ["营业时间", "giờ mở cửa; giờ làm việc", "danh từ", "查看营业时间", "Chákàn yíngyè shíjiān", "xem giờ mở cửa"],
      ["客服", "dịch vụ/chăm sóc khách hàng", "danh từ", "联系客服", "Liánxì kèfú", "liên hệ chăm sóc khách hàng"],
      ["投诉", "khiếu nại", "động từ/danh từ", "正式投诉", "Zhèngshì tóusù", "khiếu nại chính thức"],
      ["评价", "đánh giá; nhận xét", "động từ/danh từ", "用户评价", "Yònghù píngjià", "đánh giá của người dùng"],
    ],
    grammar: ["如果……，可以……", "Nêu một điều kiện thực tế rồi đưa ra phương án có thể thực hiện.", "如果包裹有问题，可以联系客服。", "Rúguǒ bāoguǒ yǒu wèntí, kěyǐ liánxì kèfú.", "Nếu bưu kiện có vấn đề, bạn có thể liên hệ chăm sóc khách hàng."],
    dialogue: [
      ["A", "我的包裹到了，但是机器不能正常使用。", "Wǒ de bāoguǒ dào le, dànshì jīqì bù néng zhèngcháng shǐyòng.", "Bưu kiện của tôi đã tới nhưng máy không dùng bình thường."],
      ["B", "您保留收据了吗？这个产品有一年保修。", "Nín bǎoliú shōujù le ma? Zhège chǎnpǐn yǒu yì nián bǎoxiū.", "Bạn còn giữ biên lai không? Sản phẩm này được bảo hành một năm."],
      ["A", "我应该去柜台申请维修还是退款？", "Wǒ yīnggāi qù guìtái shēnqǐng wéixiū háishi tuìkuǎn?", "Tôi nên tới quầy yêu cầu sửa chữa hay hoàn tiền?"],
      ["B", "先联系客服预约，客服会告诉您具体手续。", "Xiān liánxì kèfú yùyuē, kèfú huì gàosu nín jùtǐ shǒuxù.", "Hãy liên hệ chăm sóc khách hàng đặt lịch trước, họ sẽ báo thủ tục cụ thể."],
    ],
  },
  {
    id: "healthcare",
    titleVi: "Sức khoẻ và khám chữa bệnh",
    titleZh: "健康就医",
    objectiveVi: "Mô tả triệu chứng và hiểu các bước cơ bản trong khám chữa bệnh.",
    entries: [
      ["症状", "triệu chứng", "danh từ", "描述症状", "Miáoshù zhèngzhuàng", "mô tả triệu chứng"],
      ["过敏", "dị ứng; quá mẫn", "động từ/tính từ", "对花粉过敏", "Duì huāfěn guòmǐn", "dị ứng với phấn hoa"],
      ["头晕", "chóng mặt", "tính từ/động từ", "感到头晕", "Gǎndào tóuyūn", "cảm thấy chóng mặt"],
      ["失眠", "mất ngủ", "động từ/danh từ", "长期失眠", "Chángqī shīmián", "mất ngủ kéo dài"],
      ["血压", "huyết áp", "danh từ", "测量血压", "Cèliáng xuèyā", "đo huyết áp"],
      ["处方", "đơn thuốc", "danh từ", "医生开处方", "Yīshēng kāi chǔfāng", "bác sĩ kê đơn"],
      ["药房", "nhà thuốc; quầy dược", "danh từ", "去药房买药", "Qù yàofáng mǎi yào", "đến nhà thuốc mua thuốc"],
      ["急诊", "cấp cứu; khoa cấp cứu", "danh từ", "医院急诊", "Yīyuàn jízhěn", "khoa cấp cứu bệnh viện"],
      ["保险", "bảo hiểm", "danh từ", "医疗保险", "Yīliáo bǎoxiǎn", "bảo hiểm y tế"],
      ["疫苗", "vắc-xin", "danh từ", "接种疫苗", "Jiēzhòng yìmiáo", "tiêm vắc-xin"],
      ["营养", "dinh dưỡng", "danh từ", "均衡营养", "Jūnhéng yíngyǎng", "dinh dưỡng cân bằng"],
      ["恢复", "hồi phục; khôi phục", "động từ", "逐渐恢复", "Zhújiàn huīfù", "dần hồi phục", "to resume"],
    ],
    grammar: ["一旦……，就……", "Nhấn mạnh rằng ngay khi điều kiện xảy ra thì cần thực hiện hành động phía sau.", "一旦症状加重，就去急诊。", "Yídàn zhèngzhuàng jiāzhòng, jiù qù jízhěn.", "Một khi triệu chứng nặng lên thì hãy đi cấp cứu."],
    dialogue: [
      ["A", "我这两天头晕，还一直失眠。", "Wǒ zhè liǎng tiān tóuyūn, hái yìzhí shīmián.", "Hai hôm nay tôi chóng mặt và còn mất ngủ liên tục."],
      ["B", "先测量血压。您对什么药过敏吗？", "Xiān cèliáng xuèyā. Nín duì shénme yào guòmǐn ma?", "Trước hết hãy đo huyết áp. Bạn có dị ứng thuốc gì không?"],
      ["A", "没有。我需要去急诊吗？", "Méiyǒu. Wǒ xūyào qù jízhěn ma?", "Không. Tôi có cần đi cấp cứu không?"],
      ["B", "目前不用，我先开处方；如果症状加重，请马上回来。", "Mùqián bú yòng, wǒ xiān kāi chǔfāng; rúguǒ zhèngzhuàng jiāzhòng, qǐng mǎshàng huílái.", "Hiện tại chưa cần, tôi sẽ kê đơn trước; nếu triệu chứng nặng lên, hãy quay lại ngay."],
    ],
  },
  {
    id: "environment",
    titleVi: "Môi trường và phát triển bền vững",
    titleZh: "环境与发展",
    objectiveVi: "Trình bày hành động bảo vệ tài nguyên và phản ứng trước thiên tai.",
    entries: [
      ["垃圾分类", "phân loại rác", "danh từ/động từ", "做好垃圾分类", "Zuò hǎo lājī fēnlèi", "phân loại rác đúng cách"],
      ["回收", "thu hồi; tái chế", "động từ", "回收塑料", "Huíshōu sùliào", "tái chế nhựa"],
      ["节能", "tiết kiệm năng lượng", "động từ/tính từ", "节能设备", "Jiénéng shèbèi", "thiết bị tiết kiệm năng lượng"],
      ["气候变化", "biến đổi khí hậu", "danh từ", "应对气候变化", "Yìngduì qìhòu biànhuà", "ứng phó biến đổi khí hậu"],
      ["可持续发展", "phát triển bền vững", "danh từ", "推动可持续发展", "Tuīdòng kě chíxù fāzhǎn", "thúc đẩy phát triển bền vững"],
      ["公共交通", "giao thông công cộng", "danh từ", "使用公共交通", "Shǐyòng gōnggòng jiāotōng", "sử dụng giao thông công cộng"],
      ["碳排放", "phát thải carbon", "danh từ", "减少碳排放", "Jiǎnshǎo tàn páifàng", "giảm phát thải carbon"],
      ["资源", "tài nguyên; nguồn lực", "danh từ", "节约资源", "Jiéyuē zīyuán", "tiết kiệm tài nguyên", "resource"],
      ["自然灾害", "thiên tai", "danh từ", "应对自然灾害", "Yìngduì zìrán zāihài", "ứng phó thiên tai"],
      ["洪水", "lũ; lụt", "danh từ", "洪水预警", "Hóngshuǐ yùjǐng", "cảnh báo lũ"],
      ["台风", "bão nhiệt đới; bão", "danh từ", "台风登陆", "Táifēng dēnglù", "bão đổ bộ", "typhoon"],
      ["地震", "động đất", "danh từ", "发生地震", "Fāshēng dìzhèn", "xảy ra động đất"],
      ["预警", "cảnh báo sớm", "danh từ/động từ", "发布预警", "Fābù yùjǐng", "phát cảnh báo sớm"],
      ["湿度", "độ ẩm", "danh từ", "测量湿度", "Cèliáng shīdù", "đo độ ẩm"],
    ],
    grammar: ["不仅……，还……", "Liên kết hai lợi ích hoặc hai đặc điểm cùng đúng, trong đó ý sau bổ sung ý trước.", "公共交通不仅节能，还能减少碳排放。", "Gōnggòng jiāotōng bùjǐ jiénéng, hái néng jiǎnshǎo tàn páifàng.", "Giao thông công cộng không chỉ tiết kiệm năng lượng mà còn giảm phát thải carbon."],
    dialogue: [
      ["A", "社区为什么开始做垃圾分类？", "Shèqū wèishénme kāishǐ zuò lājī fēnlèi?", "Vì sao khu dân cư bắt đầu phân loại rác?"],
      ["B", "因为回收资源可以减少浪费和碳排放。", "Yīnwèi huíshōu zīyuán kěyǐ jiǎnshǎo làngfèi hé tàn páifàng.", "Vì tái chế tài nguyên có thể giảm lãng phí và phát thải carbon."],
      ["A", "最近还有台风和洪水预警，我们该准备什么？", "Zuìjìn hái yǒu táifēng hé hóngshuǐ yùjǐng, wǒmen gāi zhǔnbèi shénme?", "Gần đây còn có cảnh báo bão và lũ, chúng ta nên chuẩn bị gì?"],
      ["B", "先关注预警信息，再准备水、食物和应急用品。", "Xiān guānzhù yùjǐng xìnxī, zài zhǔnbèi shuǐ, shíwù hé yìngjí yòngpǐn.", "Hãy theo dõi cảnh báo trước rồi chuẩn bị nước, thức ăn và đồ khẩn cấp."],
    ],
  },
  {
    id: "communication",
    titleVi: "Giao tiếp và cảm xúc",
    titleZh: "沟通与情绪",
    objectiveVi: "Diễn đạt sự tin tưởng, lo lắng và cách xử lý tình huống khó nói.",
    entries: [
      ["沟通", "giao tiếp; trao đổi", "động từ/danh từ", "有效沟通", "Yǒuxiào gōutōng", "giao tiếp hiệu quả"],
      ["信任", "tin tưởng; sự tin cậy", "động từ/danh từ", "建立信任", "Jiànlì xìnrèn", "xây dựng lòng tin"],
      ["焦虑", "lo âu; lo lắng", "tính từ/danh từ", "缓解焦虑", "Huǎnjiě jiāolǜ", "giảm lo âu"],
      ["惊喜", "niềm bất ngờ vui vẻ", "danh từ/tính từ", "意外惊喜", "Yìwài jīngxǐ", "bất ngờ thú vị"],
      ["尴尬", "ngượng ngùng; khó xử", "tính từ", "场面尴尬", "Chǎngmiàn gāngà", "tình huống khó xử"],
      ["挑战", "thử thách; thách thức", "danh từ/động từ", "接受挑战", "Jiēshòu tiǎozhàn", "chấp nhận thử thách"],
    ],
    grammar: ["与其……，不如……", "So sánh hai lựa chọn và cho rằng phương án phía sau phù hợp hơn.", "与其一个人焦虑，不如主动沟通。", "Yǔqí yí ge rén jiāolǜ, bùrú zhǔdòng gōutōng.", "Thay vì lo lắng một mình, chi bằng chủ động trao đổi."],
    dialogue: [
      ["A", "明天要演讲，我现在特别焦虑。", "Míngtiān yào yǎnjiǎng, wǒ xiànzài tèbié jiāolǜ.", "Ngày mai phải thuyết trình, giờ tôi rất lo."],
      ["B", "与其一个人担心，不如先跟老师沟通。", "Yǔqí yí ge rén dānxīn, bùrú xiān gēn lǎoshī gōutōng.", "Thay vì lo một mình, chi bằng trao đổi với giáo viên trước."],
      ["A", "我怕说错以后场面很尴尬。", "Wǒ pà shuō cuò yǐhòu chǎngmiàn hěn gāngà.", "Tôi sợ nói sai rồi tình huống sẽ khó xử."],
      ["B", "大家信任你。把这次演讲当成一个挑战吧。", "Dàjiā xìnrèn nǐ. Bǎ zhè cì yǎnjiǎng dàngchéng yí ge tiǎozhàn ba.", "Mọi người tin bạn. Hãy coi bài thuyết trình này là một thử thách."],
    ],
  },
  {
    id: "travel",
    titleVi: "Du lịch tự túc",
    titleZh: "自助旅行",
    objectiveVi: "Xử lý sân bay, chỗ ở, thay đổi vé và di chuyển đường dài.",
    entries: [
      ["登机牌", "thẻ lên máy bay", "danh từ", "打印登机牌", "Dǎyìn dēngjīpái", "in thẻ lên máy bay"],
      ["托运行李", "hành lý ký gửi", "danh từ", "办理托运行李", "Bànlǐ tuōyùn xíngli", "làm thủ tục hành lý ký gửi"],
      ["改签", "đổi chuyến; đổi vé", "động từ/danh từ", "办理改签", "Bànlǐ gǎiqiān", "làm thủ tục đổi chuyến"],
      ["退票", "trả vé; hoàn vé", "động từ", "申请退票", "Shēnqǐng tuìpiào", "yêu cầu hoàn vé", "return a ticket"],
      ["退房", "trả phòng", "động từ", "中午退房", "Zhōngwǔ tuìfáng", "trả phòng vào buổi trưa"],
      ["前台", "quầy lễ tân", "danh từ", "酒店前台", "Jiǔdiàn qiántái", "quầy lễ tân khách sạn", "reception"],
      ["民宿", "nhà nghỉ tư nhân; homestay", "danh từ", "预订民宿", "Yùdìng mínsù", "đặt homestay"],
      ["迷路", "lạc đường", "động từ", "在城里迷路", "Zài chénglǐ mílù", "lạc đường trong thành phố"],
      ["路线", "tuyến đường; lộ trình", "danh từ", "规划路线", "Guīhuà lùxiàn", "lập lộ trình"],
      ["租车", "thuê xe", "động từ", "网上租车", "Wǎngshàng zūchē", "thuê xe trực tuyến"],
      ["押金", "tiền đặt cọc", "danh từ", "支付押金", "Zhīfù yājīn", "trả tiền đặt cọc"],
      ["交通堵塞", "tắc nghẽn giao thông", "danh từ", "遇到交通堵塞", "Yùdào jiāotōng dǔsè", "gặp tắc đường"],
      ["高速公路", "đường cao tốc", "danh từ", "高速公路入口", "Gāosù gōnglù rùkǒu", "lối vào đường cao tốc"],
      ["充电站", "trạm sạc", "danh từ", "寻找充电站", "Xúnzhǎo chōngdiànzhàn", "tìm trạm sạc"],
    ],
    grammar: ["由于……，所以……", "Nêu nguyên nhân tương đối trang trọng bằng 由于 rồi đưa kết quả bằng 所以.", "由于航班有变化，所以我要办理改签。", "Yóuyú hángbān yǒu biànhuà, suǒyǐ wǒ yào bànlǐ gǎiqiān.", "Do chuyến bay có thay đổi nên tôi phải làm thủ tục đổi vé."],
    dialogue: [
      ["A", "我的航班改时间了，在哪里办理改签？", "Wǒ de hángbān gǎi shíjiān le, zài nǎlǐ bànlǐ gǎiqiān?", "Chuyến bay của tôi đổi giờ rồi, làm thủ tục đổi chuyến ở đâu?"],
      ["B", "请先出示登机牌，再到三号柜台办理。", "Qǐng xiān chūshì dēngjīpái, zài dào sān hào guìtái bànlǐ.", "Hãy xuất trình thẻ lên máy bay trước rồi tới quầy số ba làm thủ tục."],
      ["A", "托运行李需要重新办理吗？", "Tuōyùn xíngli xūyào chóngxīn bànlǐ ma?", "Hành lý ký gửi có cần làm lại thủ tục không?"],
      ["B", "需要。如果决定退票，也要在这个柜台申请。", "Xūyào. Rúguǒ juédìng tuìpiào, yě yào zài zhège guìtái shēnqǐng.", "Có. Nếu quyết định hoàn vé, bạn cũng phải yêu cầu tại quầy này."],
    ],
  },
  {
    id: "academic",
    titleVi: "Học thuật và quản lý tiến độ",
    titleZh: "学术学习",
    objectiveVi: "Trình bày nguồn, bằng chứng, kết luận và tiến độ học tập.",
    entries: [
      ["课程表", "thời khoá biểu", "danh từ", "查看课程表", "Chákàn kèchéngbiǎo", "xem thời khoá biểu"],
      ["演讲", "bài phát biểu; thuyết trình", "động từ/danh từ", "做演讲", "Zuò yǎnjiǎng", "thuyết trình"],
      ["报告", "báo cáo", "động từ/danh từ", "提交报告", "Tíjiāo bàogào", "nộp báo cáo", "report"],
      ["参考文献", "tài liệu tham khảo", "danh từ", "列出参考文献", "Lièchū cānkǎo wénxiàn", "liệt kê tài liệu tham khảo"],
      ["摘要", "tóm tắt; phần trích yếu", "danh từ", "写摘要", "Xiě zhāiyào", "viết phần tóm tắt"],
      ["论文", "bài luận; luận văn; bài báo học thuật", "danh từ", "发表论文", "Fābiǎo lùnwén", "công bố bài báo"],
      ["结论", "kết luận", "danh từ", "得出结论", "Déchū jiélùn", "rút ra kết luận"],
      ["证据", "bằng chứng", "danh từ", "提供证据", "Tígōng zhèngjù", "cung cấp bằng chứng"],
      ["观点", "quan điểm", "danh từ", "表达观点", "Biǎodá guāndiǎn", "trình bày quan điểm"],
      ["生词本", "sổ từ mới", "danh từ", "整理生词本", "Zhěnglǐ shēngcíběn", "sắp xếp sổ từ mới"],
      ["进度", "tiến độ", "danh từ", "检查进度", "Jiǎnchá jìndù", "kiểm tra tiến độ"],
    ],
    grammar: ["根据……，可以得出……", "Dẫn nguồn hoặc bằng chứng bằng 根据 rồi nêu kết luận có căn cứ.", "根据调查结果，可以得出这个结论。", "Gēnjù diàochá jiéguǒ, kěyǐ déchū zhège jiélùn.", "Dựa trên kết quả khảo sát, có thể rút ra kết luận này."],
    dialogue: [
      ["A", "你的报告写到哪儿了？", "Nǐ de bàogào xiě dào nǎr le?", "Báo cáo của bạn viết tới đâu rồi?"],
      ["B", "摘要已经写完了，正在整理参考文献。", "Zhāiyào yǐjīng xiě wán le, zhèngzài zhěnglǐ cānkǎo wénxiàn.", "Tôi đã viết xong phần tóm tắt và đang sắp xếp tài liệu tham khảo."],
      ["A", "结论有足够的证据支持吗？", "Jiélùn yǒu zúgòu de zhèngjù zhīchí ma?", "Kết luận có đủ bằng chứng hỗ trợ không?"],
      ["B", "有。我会在演讲里先说明证据，再表达自己的观点。", "Yǒu. Wǒ huì zài yǎnjiǎng lǐ xiān shuōmíng zhèngjù, zài biǎodá zìjǐ de guāndiǎn.", "Có. Trong bài thuyết trình tôi sẽ trình bày bằng chứng trước rồi nêu quan điểm của mình."],
    ],
  },
  {
    id: "media-community",
    titleVi: "Truyền thông và cộng đồng",
    titleZh: "媒体与社区",
    objectiveVi: "Hiểu nội dung số, bản quyền và hoạt động cộng đồng.",
    entries: [
      ["头条", "tin nổi bật; tiêu đề chính", "danh từ", "新闻头条", "Xīnwén tóutiáo", "tin nổi bật", "headline"],
      ["直播", "phát trực tiếp; buổi phát trực tiếp", "động từ/danh từ", "观看直播", "Guānkàn zhíbō", "xem phát trực tiếp"],
      ["播客", "podcast", "danh từ", "收听播客", "Shōutīng bōkè", "nghe podcast"],
      ["短视频", "video ngắn", "danh từ", "制作短视频", "Zhìzuò duǎn shìpín", "làm video ngắn"],
      ["评论区", "khu vực bình luận", "danh từ", "查看评论区", "Chákàn pínglùnqū", "xem khu vực bình luận"],
      ["谣言", "tin đồn; thông tin thất thiệt", "danh từ", "传播谣言", "Chuánbō yáoyán", "lan truyền tin đồn"],
      ["版权", "bản quyền", "danh từ", "尊重版权", "Zūnzhòng bǎnquán", "tôn trọng bản quyền"],
      ["社区", "cộng đồng; khu dân cư", "danh từ", "社区活动", "Shèqū huódòng", "hoạt động cộng đồng"],
      ["志愿者", "tình nguyện viên", "danh từ", "招募志愿者", "Zhāomù zhìyuànzhě", "tuyển tình nguyện viên"],
      ["捐款", "quyên góp tiền", "động từ/danh từ", "公开捐款", "Gōngkāi juānkuǎn", "quyên góp công khai"],
      ["生活方式", "lối sống", "danh từ", "健康的生活方式", "Jiànkāng de shēnghuó fāngshì", "lối sống lành mạnh"],
    ],
    grammar: ["对……来说，……", "Đặt một chủ thể hoặc nhóm làm góc nhìn để đánh giá điều phía sau.", "对志愿者来说，信任比流量更重要。", "Duì zhìyuànzhě láishuō, xìnrèn bǐ liúliàng gèng zhòngyào.", "Đối với tình nguyện viên, sự tin cậy quan trọng hơn lượng truy cập."],
    dialogue: [
      ["A", "这个短视频成了今天的新闻头条。", "Zhège duǎn shìpín chéng le jīntiān de xīnwén tóutiáo.", "Video ngắn này đã trở thành tin nổi bật hôm nay."],
      ["B", "评论区有人说内容是谣言。", "Pínglùnqū yǒu rén shuō nèiróng shì yáoyán.", "Có người trong khu bình luận nói nội dung là tin đồn."],
      ["A", "发布以前应该确认来源，也要尊重版权。", "Fābù yǐqián yīnggāi quèrèn láiyuán, yě yào zūnzhòng bǎnquán.", "Trước khi đăng nên xác minh nguồn và cũng phải tôn trọng bản quyền."],
      ["B", "对社区来说，可信的信息比流量更重要。", "Duì shèqū láishuō, kěxìn de xìnxī bǐ liúliàng gèng zhòngyào.", "Đối với cộng đồng, thông tin đáng tin quan trọng hơn lượt truy cập."],
    ],
  },
];
